(function(){'use strict';
const D=document,$=(s,r)=>(r||D).querySelector(s),$$=(s,r)=>Array.from((r||D).querySelectorAll(s));
const VERSION=60,KEY='axis_v60_state',OLD_KEYS=['axis_v51_state','axis_v50_state','axis_v42_state','axis_v40_state'],DB='axis_v42_media';
const MUSCLES=['胸肌','背部','肩部','肱二头肌','肱三头肌','核心','臀部','股四头肌','腘绳肌','小腿','心肺'];
const BASE_EQ=[
{id:'cable',name:'多功能龙门架',type:'strength',pattern:'pull',muscles:['背部','胸肌','肩部','肱二头肌','肱三头肌'],effect:'多方向力量'},
{id:'lat',name:'高位下拉',type:'strength',pattern:'pull',muscles:['背部','肱二头肌'],effect:'背部宽度'},
{id:'row',name:'坐姿 / 胸托划船',type:'strength',pattern:'pull',muscles:['背部','肱二头肌'],effect:'背部厚度'},
{id:'pec',name:'飞鸟 / 后三角',type:'strength',pattern:'push',muscles:['胸肌','肩部'],effect:'胸部与肩后侧'},
{id:'chest',name:'胸推',type:'strength',pattern:'push',muscles:['胸肌','肱三头肌','肩部'],effect:'胸部推力'},
{id:'shoulder',name:'肩推',type:'strength',pattern:'push',muscles:['肩部','肱三头肌'],effect:'肩部推力'},
{id:'dip',name:'双杠 / 抬腿',type:'strength',pattern:'core',muscles:['胸肌','肱三头肌','核心'],effect:'上肢与核心'},
{id:'arms',name:'手臂',type:'strength',pattern:'pull',muscles:['肱二头肌','肱三头肌'],effect:'手臂力量'},
{id:'legpress',name:'坐姿腿推',type:'strength',pattern:'knee',muscles:['股四头肌','臀部','腘绳肌'],effect:'腿部推力'},
{id:'hack',name:'哈克 / 斜腿推',type:'strength',pattern:'knee',muscles:['股四头肌','臀部'],effect:'大腿前侧与臀部'},
{id:'legext',name:'腿屈伸',type:'strength',pattern:'knee',muscles:['股四头肌'],effect:'大腿前侧'},
{id:'legcurl',name:'腿弯举',type:'strength',pattern:'hinge',muscles:['腘绳肌'],effect:'大腿后侧'},
{id:'calf',name:'小腿',type:'strength',pattern:'hinge',muscles:['小腿'],effect:'小腿力量'},
{id:'dumbbell',name:'哑铃',type:'strength',pattern:'push',muscles:['胸肌','背部','肩部','肱二头肌','肱三头肌'],effect:'自由力量'},
{id:'barbell',name:'杠铃',type:'strength',pattern:'hinge',muscles:['背部','臀部','股四头肌','腘绳肌'],effect:'复合力量'},
{id:'bodyweight',name:'徒手',type:'strength',pattern:'core',muscles:['核心','胸肌','股四头肌'],effect:'自重训练'},
{id:'elliptical',name:'椭圆机',type:'cardio',pattern:'cardio',muscles:['心肺','股四头肌','臀部'],effect:'心肺与下肢耐力'},
{id:'rower',name:'划船机',type:'cardio',pattern:'cardio',muscles:['心肺','背部','股四头肌'],effect:'全身心肺'},
{id:'treadmill',name:'跑步机 / 跑步',type:'cardio',pattern:'cardio',muscles:['心肺','股四头肌','臀部','小腿'],effect:'心肺与跑动耐力'},
{id:'walk',name:'步行',type:'cardio',pattern:'cardio',muscles:['心肺','股四头肌','小腿'],effect:'低强度耐力'}
];
const DEFAULT_PREFS={keepClip:true,scanSeconds:3,watermark:{name:true,data:true,time:true,brand:true,pos:'bl',photoMode:'wm',videoMode:'wm'}};
const DEFAULT_PROFILE={name:'',height:'',weight:'',bodyFat:'',years:'',freq:'',goal:'',customEq:[],memories:[]};
let state={sessions:[],active:null,selectedEq:null,frames:[],clip:null,stream:null,ai:null,profile:{...DEFAULT_PROFILE},prefs:JSON.parse(JSON.stringify(DEFAULT_PREFS))};
let timer=null,toastTimer=null,finishRaf=null,finishStart=0,captureMode='3',editCustomId=null,reportRange='last',selectedSessions=new Set();
const eqAll=()=>BASE_EQ.concat(state.profile.customEq||[]),pad=n=>String(n).padStart(2,'0'),uid=p=>p+'-'+Date.now().toString(36).toUpperCase()+Math.random().toString(36).slice(2,6).toUpperCase();
const clone=x=>JSON.parse(JSON.stringify(x));
function load(){try{const cur=JSON.parse(localStorage.getItem(KEY)||'null');if(cur?.version===VERSION){state={...state,...cur,frames:[],clip:null,stream:null,ai:null,profile:{...DEFAULT_PROFILE,...cur.profile},prefs:{...clone(DEFAULT_PREFS),...cur.prefs,watermark:{...DEFAULT_PREFS.watermark,...cur.prefs?.watermark}}};return}for(const k of OLD_KEYS){const old=JSON.parse(localStorage.getItem(k)||'null');if(old){state.sessions=old.sessions||[];state.active=old.active||null;state.profile={...DEFAULT_PROFILE,...old.profile};state.prefs={...clone(DEFAULT_PREFS),...old.prefs,watermark:{...DEFAULT_PREFS.watermark,...old.prefs?.watermark}};save();break}}}catch(e){console.warn(e)}}
function save(){try{localStorage.setItem(KEY,JSON.stringify({version:VERSION,sessions:state.sessions,active:state.active,profile:state.profile,prefs:state.prefs}))}catch{}}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function setText(sel,v){const e=$(sel);if(e)e.textContent=v}
function toast(m){const e=$('#toast');if(!e)return;e.textContent=m;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1500)}
function openSheet(id){$('#'+id)?.classList.add('show')}
function closeSheet(id){$('#'+id)?.classList.remove('show');if(id==='scanSheet')stopCamera()}
function dlabel(t){const d=new Date(t);return `${d.getFullYear()}.${pad(d.getMonth()+1)}.${pad(d.getDate())}`}
function tlabel(t){const d=new Date(t);return `${pad(d.getHours())}:${pad(d.getMinutes())}`}
function mins(s){return Math.max(0,Math.round(((s.end||Date.now())-s.start)/60000))}
function ev(s){return s&&Array.isArray(s.events)?s.events:[]}
function recent(days){const cut=Date.now()-days*864e5;return state.sessions.filter(s=>s.start>=cut).concat(state.active&&state.active.start>=cut?[state.active]:[])}
function allEvents(){return (state.active?[state.active]:[]).concat(state.sessions).flatMap(ev)}
function eqById(id){return eqAll().find(e=>e.id===id)}
function eventEq(e){return eqById(e.equipmentId)||{name:e.name,muscles:e.muscles||[],effect:e.effect||'',type:e.kind,pattern:e.pattern}}
function eventMeta(e){return e.kind==='strength'?`${numFmt(e.weight)}kg · ${e.reps}次 · ${e.sets}组`:`${e.duration}分钟 · 强度${e.intensity}`}
function numFmt(n){return Number(n)%1?Number(n).toFixed(1):String(Number(n)||0)}
function lastEvent(id){return allEvents().filter(e=>e.equipmentId===id).sort((a,b)=>b.time-a.time)[0]||null}
function usage(id){const a=allEvents().filter(e=>e.equipmentId===id);return{n:a.length,last:a.reduce((m,e)=>Math.max(m,e.time),0)}}
function muscleCounts(ss){const c={};MUSCLES.forEach(m=>c[m]=0);ss.forEach(s=>ev(s).forEach(e=>(e.muscles?.length?e.muscles:eventEq(e).muscles||[]).forEach(m=>{if(c[m]!=null)c[m]++})));return c}
function render(){setText('#todayDate',new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',weekday:'short'}).format(new Date()));const r7=recent(7);setText('#weekMins',r7.reduce((a,s)=>a+mins(s),0));setText('#weekSessions',r7.length);setText('#helloTitle',state.profile.name?`${state.profile.name}，今天练吗`:'尚未开始');setText('#lastSession',state.sessions[0]?`${dlabel(state.sessions[0].start)} · ${mins(state.sessions[0])}分钟`:'—');$('#idleHome').classList.toggle('hidden',!!state.active);$('#activeHome').classList.toggle('hidden',!state.active);$('#dock').classList.toggle('show',!!state.active);if(state.active){renderLive();startTimer()}else stopTimer();renderHistory();renderInsights();renderSettings();bindDynamic();hydrateThumbs()}
function renderLive(){const a=ev(state.active);setText('#liveItems',a.length);setText('#liveSets',a.reduce((n,e)=>n+(e.kind==='strength'?Number(e.sets)||0:1),0));setText('#eventCount',a.length);$('#eventList').innerHTML=a.length?a.slice().reverse().map(eventHtml).join(''):'<div class="empty">暂无记录</div>';const last=a.length?a[a.length-1].time:state.active.start,idle=(Date.now()-last)/60000;$('#liveSignalWrap').classList.toggle('hidden',idle<7);if(idle>=7){setText('#pace',idle>=10?'停得有点久':'休息偏久');$('#liveSignal').innerHTML=`<strong>${Math.floor(idle)}分钟没有新记录</strong><small>继续训练或长按结束</small>`}}
function startTimer(){stopTimer();const tick=()=>{if(!state.active)return;const sec=Math.floor((Date.now()-state.active.start)/1000);setText('#liveTimer',`${pad(Math.floor(sec/60))}:${pad(sec%60)}`)};tick();timer=setInterval(tick,1000)}
function stopTimer(){if(timer){clearInterval(timer);timer=null}}
function eventHtml(e){return `<button class="event" data-event="${e.id}"><span class="thumb" ${e.frameRefs?.[0]?`data-photo="${e.frameRefs[0]}"`:''}>${e.frameRefs?.[0]?'':'•'}</span><span><strong>${esc(e.name)}</strong><small>${esc(eventMeta(e))}</small></span><span class="time">${tlabel(e.time)}</span></button>`}
function renderHistory(){setText('#historyCount',state.sessions.length);$('#historyList').innerHTML=state.sessions.length?state.sessions.map(s=>`<button class="history" data-session="${s.id}"><span class="thumb">${mins(s)}′</span><span><strong>${dlabel(s.start)}</strong><small>${ev(s).length}项 · ${mins(s)}分钟</small></span><b>${tlabel(s.start)}</b></button>`).join(''):'<div class="empty">暂无记录</div>'}
function median(arr){if(!arr.length)return 0;const a=[...arr].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:Math.round((a[m-1]+a[m])/2)}
function renderInsights(){const r30=recent(30).filter(Boolean),events=r30.flatMap(ev),unique=new Set(events.map(e=>e.equipmentId)).size,revisited=new Set(events.filter((e,i,a)=>a.findIndex(x=>x.equipmentId===e.equipmentId)!==i).map(e=>e.equipmentId)).size,rate=unique?Math.round(revisited/unique*100):0;setText('#insightSessions',r30.length);setText('#insightMins',r30.reduce((n,s)=>n+mins(s),0));setText('#revisitRate',unique?rate:'—');const c=muscleCounts(r30),major=['胸肌','背部','肩部','股四头肌','腘绳肌','臀部','核心','心肺'],max=Math.max(1,...major.map(m=>c[m])),covered=major.filter(m=>c[m]>0).length;setText('#coverageMeta',`${covered}/${major.length}`);$('#coverageGrid').innerHTML=major.map(m=>{const level=c[m]===0?0:c[m]/max>.75?4:c[m]/max>.45?3:c[m]/max>.2?2:1;return `<div class="coverageCell" data-level="${level}"><span>${m}</span><b>${c[m]}</b></div>`}).join('');const evidence=progressEvidence(events);$('#evidenceList').innerHTML=evidence.length?evidence.map(x=>`<div class="evidence"><b>${esc(x.title)}</b><span class="${x.delta?'delta':''}">${esc(x.meta)}</span></div>`).join(''):'<div class="empty">重复记录同一器械后，这里会出现变化</div>';const durations=r30.map(mins).filter(Boolean),hours=r30.map(s=>new Date(s.start).getHours()),gaps=[];for(let i=0;i<state.sessions.length-1;i++){const g=Math.round((state.sessions[i].start-state.sessions[i+1].start)/864e5);if(g>=0&&g<31)gaps.push(g)}const commonHour=hours.length?Math.round(hours.reduce((a,b)=>a+b,0)/hours.length):null;$('#rhythmGrid').innerHTML=`<div><span>常见时长</span><b>${durations.length?median(durations)+'分':'—'}</b></div><div><span>常见时段</span><b>${commonHour==null?'—':timeBucket(commonHour)}</b></div><div><span>训练间隔</span><b>${gaps.length?median(gaps)+'天':'—'}</b></div>`;const next=nextSuggestion(c,events);$('#nextCard').innerHTML=`<b>${esc(next.title)}</b><span>${esc(next.meta)}</span>`}
function progressEvidence(events){const map={};events.filter(e=>e.kind==='strength').forEach(e=>(map[e.equipmentId]||(map[e.equipmentId]=[])).push(e));const out=[];for(const id in map){const a=map[id].sort((x,y)=>x.time-y.time);if(a.length<2)continue;const first=a[0],last=a[a.length-1],eq=eventEq(last);if(Number(last.weight)>Number(first.weight))out.push({title:eq.name,meta:`${numFmt(first.weight)} → ${numFmt(last.weight)} kg · ${a.length}次记录`,delta:true});else if(Number(last.reps)>Number(first.reps)&&Number(last.weight)>=Number(first.weight))out.push({title:eq.name,meta:`同等负重下 ${first.reps} → ${last.reps} 次`,delta:true});else if(a.length>=3)out.push({title:eq.name,meta:`已形成 ${a.length} 次可比较轨迹`,delta:false})}return out.sort((a,b)=>Number(b.delta)-Number(a.delta)).slice(0,4)}
function timeBucket(h){if(h<6)return'深夜';if(h<11)return'上午';if(h<14)return'中午';if(h<18)return'下午';if(h<22)return'晚上';return'夜间'}
function nextSuggestion(c,events){if(!events.length)return{title:'先留下第一条记录',meta:'下一次训练扫一下即可'};const pool=['胸肌','背部','肩部','股四头肌','腘绳肌','臀部','核心'];pool.sort((a,b)=>c[a]-c[b]);const target=pool[0],last=events.sort((a,b)=>b.time-a.time)[0],lastEq=eventEq(last);return{title:`下一次优先 ${target}`,meta:`近30天覆盖最少；${lastEq.name} 已记录，可直接复用上次数据`}}
function renderSettings(){const ps=[];if(state.profile.name)ps.push(state.profile.name);if(state.profile.weight)ps.push(state.profile.weight+'kg');setText('#profileSummary',ps.join(' · ')||'未填写');setText('#customCount',(state.profile.customEq||[]).length);setSwitch('#keepClipSwitch',!!state.prefs.keepClip);$$('#scanSeconds button').forEach(b=>b.classList.toggle('active',Number(b.dataset.sec)===Number(state.prefs.scanSeconds)));renderWatermarkSettings();updateStorageBrief()}
function setSwitch(sel,on){$(sel)?.setAttribute('aria-checked',String(!!on))}
function renderWatermarkSettings(){const w=state.prefs.watermark;setSwitch('#wmName',w.name);setSwitch('#wmData',w.data);setSwitch('#wmTime',w.time);setSwitch('#wmBrand',w.brand);$('#wmChip')?.setAttribute('data-pos',w.pos||'bl');$$('#photoWmMode button').forEach(b=>b.classList.toggle('active',b.dataset.value===(w.photoMode||'wm')));$$('#videoWmMode button').forEach(b=>b.classList.toggle('active',b.dataset.value===(w.videoMode||'wm')))}
function bindDynamic(){$$('[data-event]').forEach(b=>b.onclick=()=>openEvent(b.dataset.event));$$('[data-session]').forEach(b=>b.onclick=()=>openSession(b.dataset.session))}
function renderMuscles(eq){$('#musclePanel').classList.toggle('hidden',!eq);if(eq){$('#muscleTags').innerHTML=(eq.muscles||[]).slice(0,5).map(m=>`<i>${esc(m)}</i>`).join('');setText('#effectText',eq.effect||'')}}
async function startCamera(){stopCamera();$('#cameraFallback').classList.add('hidden');try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('unsupported');state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:960}},audio:false});$('#cameraVideo').srcObject=state.stream;await $('#cameraVideo').play();setText('#scanState','就绪')}catch(e){console.warn(e);$('#cameraFallback').classList.remove('hidden');setText('#scanState','拍一张')}}
function stopCamera(){if(state.stream){state.stream.getTracks().forEach(t=>t.stop());state.stream=null}if($('#cameraVideo'))$('#cameraVideo').srcObject=null}
function fpFromCanvas(cv){const s=D.createElement('canvas');s.width=9;s.height=8;const c=s.getContext('2d',{willReadFrequently:true});c.drawImage(cv,0,0,9,8);const d=c.getImageData(0,0,9,8).data;let bits='';for(let y=0;y<8;y++)for(let x=0;x<8;x++){const i=(y*9+x)*4,j=i+4,a=d[i]*.299+d[i+1]*.587+d[i+2]*.114,b=d[j]*.299+d[j+1]*.587+d[j+2]*.114;bits+=a>b?'1':'0'}let hex='';for(let i=0;i<64;i+=4)hex+=parseInt(bits.slice(i,i+4),2).toString(16);return hex}
function hamming(a,b){if(!a||!b)return 99;let n=0;for(let i=0;i<Math.min(a.length,b.length);i++){let x=parseInt(a[i],16)^parseInt(b[i],16);while(x){n+=x&1;x>>=1}}return n+Math.abs(a.length-b.length)*4}
function captureSeal(cv){const c=cv.getContext('2d'),ts=Date.now(),w=cv.width,h=cv.height,f=Math.max(12,Math.round(w*.016)),p=Math.max(12,Math.round(w*.018)),text=`AXIS 实时 · ${new Date(ts).toLocaleTimeString('zh-CN',{hour12:false})}`;c.save();c.font=`600 ${f}px -apple-system,BlinkMacSystemFont,Arial`;c.textBaseline='top';const tw=c.measureText(text).width,x=w-tw-p*2,y=p;c.fillStyle='rgba(5,6,8,.58)';roundRect(c,x-p*.6,y-p*.35,tw+p*1.2,f+p*.8,p*.38);c.fill();c.fillStyle='#f5f4f0';c.fillText(text,x,y);c.restore();return ts}
async function frameFromVideo(){const v=$('#cameraVideo');if(!v.videoWidth)throw new Error('camera');const max=960,scale=Math.min(1,max/v.videoWidth),cv=D.createElement('canvas');cv.width=Math.round(v.videoWidth*scale);cv.height=Math.round(v.videoHeight*scale);cv.getContext('2d',{alpha:false}).drawImage(v,0,0,cv.width,cv.height);const fp=fpFromCanvas(cv),ts=captureSeal(cv),blob=await new Promise(r=>cv.toBlob(r,'image/jpeg',.8));return{blob,url:URL.createObjectURL(blob),ts,fp}}
async function frameFromFile(file){const u=URL.createObjectURL(file),img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=u});const max=960,scale=Math.min(1,max/img.naturalWidth),cv=D.createElement('canvas');cv.width=Math.round(img.naturalWidth*scale);cv.height=Math.round(img.naturalHeight*scale);cv.getContext('2d',{alpha:false}).drawImage(img,0,0,cv.width,cv.height);URL.revokeObjectURL(u);const fp=fpFromCanvas(cv),ts=captureSeal(cv),blob=await new Promise(r=>cv.toBlob(r,'image/jpeg',.8));return{blob,url:URL.createObjectURL(blob),ts,fp}}
function mediaMime(){if(!window.MediaRecorder)return'';for(const t of ['video/mp4','video/webm;codecs=vp8','video/webm'])if(MediaRecorder.isTypeSupported?.(t))return t;return''}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function liveScan(sec){if(!state.stream){$('#photoInput').click();return}state.frames=[];state.clip=null;$('#captureNow').disabled=true;let rec=null,chunks=[];try{if(state.prefs.keepClip&&window.MediaRecorder){const mt=mediaMime();rec=new MediaRecorder(state.stream,mt?{mimeType:mt}:undefined);rec.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};rec.start()}const count=sec===5?5:4,step=sec*1000/(count-1);for(let i=0;i<count;i++){setText('#scanState',`${Math.max(0,sec-i*sec/(count-1)).toFixed(1)}秒`);state.frames.push(await frameFromVideo());if(i<count-1)await sleep(step)}if(rec){await new Promise(resolve=>{rec.onstop=resolve;setTimeout(()=>rec.stop(),220)});if(chunks.length){const blob=new Blob(chunks,{type:rec.mimeType||chunks[0].type||'video/webm'});state.clip={blob,url:URL.createObjectURL(blob),type:blob.type}}}reviewFrames()}catch(e){console.error(e);toast('扫描失败');$('#captureNow').disabled=false;setText('#scanState','就绪')}}
async function captureNow(){if(captureMode==='photo'){if(state.stream){try{state.frames=[await frameFromVideo()];state.clip=null;reviewFrames();return}catch{}}$('#photoInput').click();return}await liveScan(Number(captureMode)||state.prefs.scanSeconds||3)}
function memoryGuess(){const mem=state.profile.memories||[];if(!mem.length||!state.frames.length)return null;let best=null;for(const m of mem)for(const f of state.frames){const d=hamming(m.fp,f.fp);if(!best||d<best.d)best={id:m.equipmentId,d}}return best&&best.d<=8?best:null}
function learnMemory(id){if(!id)return;const arr=state.profile.memories||(state.profile.memories=[]);state.frames.slice(0,3).forEach(f=>f.fp&&arr.push({equipmentId:id,fp:f.fp,t:Date.now()}));const by={};for(let i=arr.length-1;i>=0;i--){const m=arr[i];by[m.equipmentId]=by[m.equipmentId]||[];if(by[m.equipmentId].length<10)by[m.equipmentId].push(m)}state.profile.memories=Object.values(by).flat();save()}
function reviewFrames(){stopCamera();$('#captureStage').classList.add('hidden');$('#reviewStage').classList.remove('hidden');$('#film').innerHTML=state.frames.map(f=>`<img src="${f.url}" alt="扫描画面">`).join('');state.selectedEq=null;renderMuscles(null);setText('#equipmentName','待确认');setText('#aiStatus','识别中');$('#lastValue').classList.add('hidden');const g=memoryGuess();if(g){const e=eqById(g.id);if(e){selectEq(e.id,false);setText('#aiStatus','已认出');if(g.d<=5)return}}analyzeFrames()}
async function blobDataUrl(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(blob)})}
async function analyzeFrames(){try{const picks=state.frames.length<=3?state.frames:[state.frames[0],state.frames[Math.floor(state.frames.length/2)],state.frames[state.frames.length-1]],frames=await Promise.all(picks.map(f=>blobDataUrl(f.blob))),recentEquipment=allEvents().slice(0,10).map(e=>e.equipmentId);const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({frames,recentEquipment})}),j=await r.json();if(!r.ok||!j.result){setText('#aiStatus','手动确认');return}state.ai=j.result;if(j.result.equipmentId&&j.result.confidence>=.58){selectEq(j.result.equipmentId,false);setText('#aiStatus',j.result.confidence>=.82?'已识别':'请确认');if(Number.isFinite(Number(j.result.weightKg)))setVal('weight',Number(j.result.weightKg));if(j.result.cardio){if(Number.isFinite(Number(j.result.cardio.durationMin)))setVal('duration',Math.round(Number(j.result.cardio.durationMin)));if(Number.isFinite(Number(j.result.cardio.resistance)))setChoice('intensity',Math.max(1,Math.min(10,Math.round(Number(j.result.cardio.resistance)))))} }else setText('#aiStatus','请确认')}catch(e){console.warn(e);setText('#aiStatus','手动确认')}}
function resetScan(){state.frames.forEach(f=>{try{URL.revokeObjectURL(f.url)}catch{}});if(state.clip?.url)try{URL.revokeObjectURL(state.clip.url)}catch{};state.frames=[];state.clip=null;state.selectedEq=null;state.ai=null;$('#captureStage').classList.remove('hidden');$('#reviewStage').classList.add('hidden');$('#film').innerHTML='';$('#captureNow').disabled=false;setText('#scanState','就绪');setText('#equipmentName','待确认');setText('#aiStatus','识别中');renderMuscles(null);$('#strengthFields').classList.add('hidden');$('#cardioFields').classList.add('hidden');$('#lastValue').classList.add('hidden')}
function setVal(id,v){const el=$('#'+id);if(el&&v!=null)el.value=v}
function nval(id,min,max,def){const n=Number($('#'+id)?.value);return Math.max(min,Math.min(max,Number.isFinite(n)?n:def))}
function buildChoices(){renderChoice('#repsChoices',[6,8,10,12,15],10,'reps');renderChoice('#setsChoices',[2,3,4,5],3,'sets');renderChoice('#intensityChoices',[3,5,6,7,8,9],5,'intensity');renderQuick('#durationQuick',[10,15,20,30,45],15,'duration')}
function renderChoice(sel,vals,current,key){$(sel).innerHTML=vals.map(v=>`<button data-choice="${key}" data-value="${v}" class="${Number(v)===Number(current)?'active':''}">${v}</button>`).join('')}
function setChoice(key,v){if(key==='reps'||key==='sets'||key==='intensity'){$$(`[data-choice="${key}"]`).forEach(b=>b.classList.toggle('active',Number(b.dataset.value)===Number(v)))}}
function choiceVal(key,def){const b=$(`[data-choice="${key}"].active`);return b?Number(b.dataset.value):def}
function renderQuick(sel,vals,current,key){$(sel).innerHTML=vals.map(v=>`<button data-quick="${key}" data-value="${v}" class="${Number(v)===Number(current)?'active':''}">${v}</button>`).join('')}
function weightQuickValues(last){const base=Number(last?.weight)||20,vals=[base-5,base-2.5,base,base+2.5,base+5].filter(v=>v>=0);return [...new Set(vals.map(v=>Math.round(v*10)/10))]}
function applyEqDefaults(eq,last){if(eq.type==='strength'){const w=last?.weight??20,r=last?.reps??10,s=last?.sets??3;setVal('weight',w);renderQuick('#weightQuick',weightQuickValues(last),w,'weight');setText('#weightHint',last?`上次 ${numFmt(last.weight)}kg`:'');renderChoice('#repsChoices',uniqueChoices([6,8,10,12,15,r]),r,'reps');renderChoice('#setsChoices',uniqueChoices([2,3,4,5,s]),s,'sets')}else{const d=last?.duration??15,i=last?.intensity??5;setVal('duration',d);renderQuick('#durationQuick',uniqueChoices([10,15,20,30,45,d]),d,'duration');setText('#durationHint',last?`上次 ${last.duration}分钟`:'');renderChoice('#intensityChoices',uniqueChoices([3,5,6,7,8,9,i]).filter(v=>v<=10),i,'intensity')}}
function uniqueChoices(a){return [...new Set(a.map(Number).filter(Number.isFinite))].sort((x,y)=>x-y)}
function selectEq(id,manual=true){const e=eqById(id);if(!e)return;state.selectedEq=id;setText('#equipmentName',e.name);$('#strengthFields').classList.toggle('hidden',e.type!=='strength');$('#cardioFields').classList.toggle('hidden',e.type!=='cardio');renderMuscles(e);const last=lastEvent(id);$('#lastValue').classList.toggle('hidden',!last);if(last)setText('#lastValue','上次 '+eventMeta(last));applyEqDefaults(e,last);if(manual)setText('#aiStatus','已确认')}
function renderEqList(q=''){const all=eqAll(),low=q.trim().toLowerCase(),filtered=all.filter(e=>!low||e.name.toLowerCase().includes(low)||(e.muscles||[]).some(m=>m.includes(low))),recentEq=all.map(e=>({e,u:usage(e.id)})).filter(x=>x.u.n).sort((a,b)=>b.u.last-a.u.last).slice(0,5);$('#quickEq').innerHTML=recentEq.map(x=>`<button data-eq="${x.e.id}">${esc(x.e.name)}</button>`).join('');$('#eqList').innerHTML=filtered.map(e=>`<button class="eqItem" data-eq="${e.id}"><b>${esc(e.name)}</b><span>${esc((e.muscles||[]).slice(0,2).join(' · '))}${e.custom?' · 自定义':''}</span></button>`).join('');$$('[data-eq]',$('#eqSheet')).forEach(b=>b.onclick=()=>{selectEq(b.dataset.eq,true);closeSheet('eqSheet')})}
function derivePattern(type,muscles){if(type==='cardio')return'cardio';if(muscles.includes('胸肌')||muscles.includes('肩部')||muscles.includes('肱三头肌'))return'push';if(muscles.includes('背部')||muscles.includes('肱二头肌'))return'pull';if(muscles.includes('股四头肌'))return'knee';if(muscles.includes('臀部')||muscles.includes('腘绳肌')||muscles.includes('小腿'))return'hinge';return'core'}
function renderCustomMuscles(selected=[]){const set=new Set(selected);$('#customMuscles').innerHTML=MUSCLES.map(m=>`<button data-muscle="${m}" class="${set.has(m)?'active':''}">${m}</button>`).join('')}
function openCustomEditor(id=null){editCustomId=id;const e=id?state.profile.customEq.find(x=>x.id===id):null;setText('#customEqTitle',e?'编辑自定义':'自定义运动');$('#customName').value=e?.name||'';$$('#customType button').forEach(b=>b.classList.toggle('active',(e?.type||'strength')===b.dataset.type));renderCustomMuscles(e?.muscles||[]);$('#deleteCustomEq').classList.toggle('hidden',!e);openSheet('customEqSheet')}
function saveCustomEq(){const name=$('#customName').value.trim(),type=$('#customType .active')?.dataset.type||'strength',muscles=$$('#customMuscles .active').map(b=>b.dataset.muscle);if(!name)return toast('请输入名称');if(!muscles.length)return toast('请选择锻炼部位');if(editCustomId){const e=state.profile.customEq.find(x=>x.id===editCustomId);if(e){e.name=name;e.type=type;e.muscles=muscles;e.pattern=derivePattern(type,muscles);e.effect=muscles.slice(0,2).join(' · ')}}else state.profile.customEq.push({id:'custom-'+uid('').replace(/^-/, '').toLowerCase(),name,type,pattern:derivePattern(type,muscles),muscles,effect:muscles.slice(0,2).join(' · '),custom:true});save();closeSheet('customEqSheet');renderManageEq();render();toast('已保存')}
function deleteCustomEq(){if(!editCustomId)return;const used=allEvents().some(e=>e.equipmentId===editCustomId);if(used&&!confirm('历史记录会保留名称，但此自定义项将从选择列表移除。继续？'))return;state.profile.customEq=state.profile.customEq.filter(e=>e.id!==editCustomId);state.profile.memories=(state.profile.memories||[]).filter(m=>m.equipmentId!==editCustomId);save();closeSheet('customEqSheet');renderManageEq();render();toast('已删除')}
function renderManageEq(){const a=state.profile.customEq||[];$('#manageEqList').innerHTML=a.length?a.map(e=>`<button class="manageEq" data-edit-eq="${e.id}"><span><b>${esc(e.name)}</b><span>${esc((e.muscles||[]).slice(0,3).join(' · '))}</span></span><i>›</i></button>`).join(''):'<div class="empty">暂无自定义器械</div>';$$('[data-edit-eq]').forEach(b=>b.onclick=()=>openCustomEditor(b.dataset.editEq))}
function overlayLines(e,eq,ts){const w=state.prefs.watermark,lines=[];if(w.brand)lines.push({t:'AXIS',strong:true});if(w.name)lines.push({t:eq.name,strong:true});if(w.data)lines.push({t:eventMeta(e)});if(w.time)lines.push({t:`${dlabel(ts)} ${tlabel(ts)}`});return lines}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x,y,w,h,r);else ctx.rect(x,y,w,h)}
function drawFinalWatermark(ctx,w,h,e,eq,ts){const lines=overlayLines(e,eq,ts);if(!lines.length)return;const pos=state.prefs.watermark.pos||'bl',font=Math.max(16,Math.round(w*.022)),small=Math.round(font*.82),padv=Math.max(16,Math.round(w*.02)),lineH=Math.round(font*1.36);ctx.save();ctx.textBaseline='top';let maxW=0;lines.forEach(x=>{ctx.font=`${x.strong?'650':'500'} ${x.strong?font:small}px -apple-system,BlinkMacSystemFont,Arial`;maxW=Math.max(maxW,ctx.measureText(x.t).width)});const boxW=maxW+padv*1.6,boxH=lineH*lines.length+padv*.9,avoidTopRight=pos==='tr',x=pos.endsWith('r')?w-boxW-padv:padv,y=pos.startsWith('t')?(avoidTopRight?padv*4.2:padv):h-boxH-padv;ctx.fillStyle='rgba(6,7,9,.78)';roundRect(ctx,x,y,boxW,boxH,Math.round(padv*.45));ctx.fill();let ty=y+padv*.45;lines.forEach(item=>{ctx.font=`${item.strong?'650':'500'} ${item.strong?font:small}px -apple-system,BlinkMacSystemFont,Arial`;ctx.fillStyle=item.strong?'#f5f4f0':'#c7cbd2';ctx.fillText(item.t,x+padv*.8,ty);ty+=lineH});ctx.restore()}
async function imageFromBlob(blob){const u=URL.createObjectURL(blob),img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=u});return{img,url:u}}
async function finalizeFrame(frame,e,eq){if((state.prefs.watermark.photoMode||'wm')==='raw')return frame.blob;const {img,url}=await imageFromBlob(frame.blob),cv=D.createElement('canvas');cv.width=img.naturalWidth;cv.height=img.naturalHeight;const c=cv.getContext('2d',{alpha:false});c.drawImage(img,0,0,cv.width,cv.height);URL.revokeObjectURL(url);drawFinalWatermark(c,cv.width,cv.height,e,eq,frame.ts||e.time);return await new Promise(r=>cv.toBlob(r,'image/jpeg',.88))}
async function watermarkVideoBlob(blob,e,eq){if((state.prefs.watermark.videoMode||'wm')==='raw')return blob;if(!HTMLCanvasElement.prototype.captureStream||!window.MediaRecorder)return blob;const u=URL.createObjectURL(blob),v=D.createElement('video');v.src=u;v.muted=true;v.playsInline=true;await new Promise((res,rej)=>{v.onloadedmetadata=res;v.onerror=rej});const max=720,scale=Math.min(1,max/v.videoWidth),cv=D.createElement('canvas');cv.width=Math.max(2,Math.round(v.videoWidth*scale));cv.height=Math.max(2,Math.round(v.videoHeight*scale));const c=cv.getContext('2d',{alpha:false}),stream=cv.captureStream(15),mt=mediaMime(),rec=new MediaRecorder(stream,mt?{mimeType:mt}:undefined),chunks=[];rec.ondataavailable=x=>x.data?.size&&chunks.push(x.data);const done=new Promise(resolve=>rec.onstop=resolve);rec.start();const draw=()=>{if(v.ended||v.paused)return;c.drawImage(v,0,0,cv.width,cv.height);drawFinalWatermark(c,cv.width,cv.height,e,eq,e.time+v.currentTime*1000);requestAnimationFrame(draw)};await v.play();draw();await new Promise(resolve=>v.onended=resolve);rec.stop();await done;URL.revokeObjectURL(u);return chunks.length?new Blob(chunks,{type:rec.mimeType||blob.type}):blob}
async function openDb(){return new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains('media'))q.result.createObjectStore('media')};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function putMedia(k,b){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction('media','readwrite');tx.objectStore('media').put(b,k);tx.oncomplete=()=>{db.close();res()};tx.onerror=()=>{db.close();rej(tx.error)}})}
async function getMedia(k){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction('media','readonly'),q=tx.objectStore('media').get(k);q.onsuccess=()=>{db.close();res(q.result||null)};q.onerror=()=>{db.close();rej(q.error)}})}
async function deleteMedia(k){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction('media','readwrite');tx.objectStore('media').delete(k);tx.oncomplete=()=>{db.close();res()};tx.onerror=()=>{db.close();rej(tx.error)}})}
async function mediaUrl(k){try{const b=await getMedia(k);return b?URL.createObjectURL(b):null}catch{return null}}
async function saveScan(){if(!state.active)return toast('请先开始训练');const eq=eqById(state.selectedEq);if(!eq){renderEqList();openSheet('eqSheet');return}const e={id:uid('E'),equipmentId:eq.id,name:eq.name,pattern:eq.pattern,kind:eq.type,muscles:eq.muscles||[],effect:eq.effect||'',time:Date.now(),frameRefs:[],photoBytes:0,videoBytes:0,fingerprints:state.frames.map(f=>f.fp).filter(Boolean),ai:state.ai?{confidence:state.ai.confidence,model:state.ai.model}:null};if(eq.type==='strength'){e.weight=nval('weight',0,1000,0);e.reps=choiceVal('reps',10);e.sets=choiceVal('sets',3)}else{e.duration=nval('duration',1,600,15);e.intensity=choiceVal('intensity',5)}try{for(let i=0;i<state.frames.length;i++){const blob=await finalizeFrame(state.frames[i],e,eq),ref=`F-${e.id}-${i}`;await putMedia(ref,blob);e.frameRefs.push(ref);e.photoBytes+=blob.size}if(state.prefs.keepClip&&state.clip?.blob){let vb=state.clip.blob;if((state.prefs.watermark.videoMode||'wm')==='wm')vb=await watermarkVideoBlob(vb,e,eq);e.clipRef=`V-${e.id}`;e.clipType=vb.type;e.videoBytes=vb.size;e.videoWatermarked=(state.prefs.watermark.videoMode||'wm')==='wm';await putMedia(e.clipRef,vb)}}catch(err){console.error(err);return toast('保存失败')}learnMemory(eq.id);state.active.events.push(e);save();closeSheet('scanSheet');resetScan();render();toast('已记下')}
async function hydrateThumbs(){for(const el of $$('[data-photo]')){if(el.dataset.loaded)continue;el.dataset.loaded='1';const u=await mediaUrl(el.dataset.photo);if(u)el.innerHTML=`<img src="${u}" alt="记录">`}}
async function shareBlob(blob,name,type){try{const f=new File([blob],name,{type});if(navigator.canShare?.({files:[f]})&&navigator.share)return await navigator.share({files:[f]});const a=D.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;D.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),800)}catch(e){if(e?.name!=='AbortError')console.warn(e)}}
async function openEvent(id){const e=allEvents().find(x=>x.id===id);if(!e)return;const eq=eventEq(e);setText('#detailTitle',e.name);let media='';if(e.clipRef){const v=await mediaUrl(e.clipRef),poster=e.frameRefs?.[0]?await mediaUrl(e.frameRefs[0]):'';if(v)media+=`<div class="videoCard"><div class="mediaTop"><b>现场片段</b><span>${e.videoWatermarked?'带水印':'原片'}</span></div><video class="detailVideo" src="${v}" ${poster?`poster="${poster}"`:''} controls playsinline muted></video><button class="mediaSave" id="saveDetailVideo">保存视频</button></div>`}if(e.frameRefs?.length){const imgs=[];for(const r of e.frameRefs){const u=await mediaUrl(r);if(u)imgs.push(`<img src="${u}" alt="现场照片">`)}media+=`<div class="mediaTop photoTop"><b>现场照片</b><span>${imgs.length}张 · ${state.prefs.watermark.photoMode==='raw'?'原片':'带水印'}</span></div><div class="detailFilm">${imgs.join('')}</div>`}const rows=e.kind==='strength'?[['重量',numFmt(e.weight)+' kg'],['次数',e.reps+' 次'],['组数',e.sets+' 组']]:[['时间',e.duration+' 分钟'],['强度',e.intensity+' / 10']];rows.unshift(['主要锻炼',(e.muscles||eq.muscles||[]).join(' · ')||'—']);rows.push(['记录时间',dlabel(e.time)+' '+tlabel(e.time)]);$('#detail').innerHTML=media+`<div class="detailList">${rows.map(r=>`<div class="detailRow"><span>${r[0]}</span><span>${esc(r[1])}</span></div>`).join('')}</div>${e.frameRefs?.[0]?'<div class="detailActions"><button id="saveDetailPhoto">保存图片</button><button id="makeSessionReport">训练报告</button></div>':''}`;openSheet('detailSheet');if($('#saveDetailPhoto'))$('#saveDetailPhoto').onclick=async()=>{const b=await getMedia(e.frameRefs[0]);if(b)shareBlob(b,`AXIS-${e.name}-${dlabel(e.time)}.jpg`,'image/jpeg')};if($('#saveDetailVideo'))$('#saveDetailVideo').onclick=async()=>{const b=await getMedia(e.clipRef);if(b)shareBlob(b,`AXIS-${e.name}-${dlabel(e.time)}.${(b.type||'video/mp4').includes('webm')?'webm':'mp4'}`,b.type||'video/mp4')};if($('#makeSessionReport'))$('#makeSessionReport').onclick=()=>{const s=(state.active?[state.active]:[]).concat(state.sessions).find(s=>ev(s).some(x=>x.id===e.id));if(s){reportRange='session:'+s.id;renderReport();openSheet('reportSheet')}}}
function openSession(id){const s=state.sessions.find(x=>x.id===id);if(!s)return;setText('#detailTitle',dlabel(s.start));$('#detail').innerHTML=`<div class="detailList"><div class="detailRow"><span>训练时间</span><span>${mins(s)} 分钟</span></div><div class="detailRow"><span>项目</span><span>${ev(s).length}</span></div><div class="detailRow"><span>组数</span><span>${ev(s).reduce((n,e)=>n+(e.kind==='strength'?Number(e.sets)||0:1),0)}</span></div></div><div class="events">${ev(s).slice().reverse().map(eventHtml).join('')}</div><div class="detailActions"><button id="sessionReportBtn">训练报告</button><button id="sessionDeleteBtn">删除本次</button></div>`;openSheet('detailSheet');bindDynamic();hydrateThumbs();$('#sessionReportBtn').onclick=()=>{reportRange='session:'+s.id;renderReport();openSheet('reportSheet')};$('#sessionDeleteBtn').onclick=async()=>{if(!confirm('删除这次训练？'))return;await deleteSessions([s.id]);closeSheet('detailSheet');render();toast('已删除')}}
function finishStartHold(){if(!state.active)return;finishStart=performance.now();const dur=1000,step=now=>{const p=Math.min(1,(now-finishStart)/dur);$('#finishHold').style.setProperty('--hold',Math.round(p*100)+'%');if(p<1)finishRaf=requestAnimationFrame(step);else completeFinish()};finishRaf=requestAnimationFrame(step)}
function finishCancelHold(){if(finishRaf)cancelAnimationFrame(finishRaf);finishRaf=null;$('#finishHold').style.setProperty('--hold','0%')}
function completeFinish(){finishCancelHold();if(!state.active)return;state.active.end=Date.now();const s=state.active;state.sessions.unshift(s);state.active=null;save();setText('#finishDuration',mins(s)+'分钟');setText('#finishItems',ev(s).length);setText('#finishSets',ev(s).reduce((n,e)=>n+(e.kind==='strength'?Number(e.sets)||0:1),0));openSheet('finishSheet');render()}
async function aiHealth(){try{const r=await fetch('/api/analyze'),j=await r.json();setText('#aiHealth',j.available?'已连接':'未连接')}catch{setText('#aiHealth','未连接')}}
function fillProfile(){$('#profileName').value=state.profile.name||'';setVal('profileHeight',state.profile.height);setVal('profileWeight',state.profile.weight);setVal('profileBodyFat',state.profile.bodyFat);setVal('profileYears',state.profile.years);$$('#profileFreq button').forEach(b=>b.classList.toggle('active',String(state.profile.freq)===b.dataset.value));$$('#profileGoal button').forEach(b=>b.classList.toggle('active',state.profile.goal===b.dataset.value))}
function saveProfile(){state.profile.name=$('#profileName').value.trim();state.profile.height=$('#profileHeight').value.trim();state.profile.weight=$('#profileWeight').value.trim();state.profile.bodyFat=$('#profileBodyFat').value.trim();state.profile.years=$('#profileYears').value.trim();state.profile.freq=$('#profileFreq .active')?.dataset.value||'';state.profile.goal=$('#profileGoal .active')?.dataset.value||'';save();closeSheet('profileSheet');render();toast('已保存')}
function fmtBytes(n){if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(n<10240?1:0)+' KB';return(n/1048576).toFixed(n<10485760?1:0)+' MB'}
async function storageInfo(){let photos=0,videos=0;try{const db=await openDb();const data=await new Promise((res,rej)=>{const tx=db.transaction('media','readonly'),store=tx.objectStore('media'),kr=store.getAllKeys(),vr=store.getAll();let keys,vals;kr.onsuccess=()=>{keys=kr.result;if(vals)done()};vr.onsuccess=()=>{vals=vr.result;if(keys)done()};kr.onerror=vr.onerror=()=>rej(tx.error);function done(){db.close();res({keys,vals})}});data.keys.forEach((k,i)=>{const z=data.vals[i]?.size||0;if(String(k).startsWith('V-'))videos+=z;else photos+=z})}catch{}const raw=localStorage.getItem(KEY)||'',recordBytes=new Blob([raw]).size;return{photos,videos,recordBytes,total:photos+videos+recordBytes}}
async function updateStorageBrief(){const i=await storageInfo();setText('#storageBrief',fmtBytes(i.total))}
async function renderStorage(){const i=await storageInfo();setText('#storageTotal',fmtBytes(i.total));setText('#photoSize',fmtBytes(i.photos));setText('#videoSize',fmtBytes(i.videos));setText('#dataSize',fmtBytes(i.recordBytes));const media=i.photos+i.videos||1;$('#photoBar').style.width=`${Math.round(i.photos/media*100)}%`;$('#videoBar').style.width=`${Math.round(i.videos/media*100)}%`;selectedSessions.clear();const rows=[];for(const s of state.sessions){let bytes=0;for(const e of ev(s))bytes+=(e.photoBytes||0)+(e.videoBytes||0);rows.push(`<button class="deleteSession" data-delete-session="${s.id}"><i>✓</i><span><b>${dlabel(s.start)}</b><small>${mins(s)}分钟 · ${ev(s).length}项</small></span><span>${fmtBytes(bytes)}</span></button>`)}$('#sessionDeleteList').innerHTML=rows.join('')||'<div class="empty">暂无记录</div>';$$('[data-delete-session]').forEach(b=>b.onclick=()=>{const id=b.dataset.deleteSession;if(selectedSessions.has(id)){selectedSessions.delete(id);b.classList.remove('selected')}else{selectedSessions.add(id);b.classList.add('selected')}})}
async function deleteSessions(ids){const set=new Set(ids);for(const s of state.sessions.filter(x=>set.has(x.id)))for(const e of ev(s)){for(const r of e.frameRefs||[])await deleteMedia(r);if(e.clipRef)await deleteMedia(e.clipRef)}state.sessions=state.sessions.filter(s=>!set.has(s.id));save()}
async function clearVideos(){for(const s of state.sessions)for(const e of ev(s))if(e.clipRef){await deleteMedia(e.clipRef);delete e.clipRef;delete e.clipType;e.videoBytes=0}save();await renderStorage();render();toast('视频已清理')}
async function clearAll(){if(!confirm('清空全部记录？'))return;localStorage.removeItem(KEY);OLD_KEYS.forEach(k=>localStorage.removeItem(k));await new Promise(res=>{const q=indexedDB.deleteDatabase(DB);q.onsuccess=q.onerror=q.onblocked=()=>res()});state={sessions:[],active:null,selectedEq:null,frames:[],clip:null,stream:null,ai:null,profile:{...DEFAULT_PROFILE},prefs:clone(DEFAULT_PREFS)};closeSheet('storageSheet');render();toast('已清空')}
function reportSessions(){if(reportRange.startsWith('session:')){const s=state.sessions.find(x=>x.id===reportRange.split(':')[1]);return s?[s]:[]}if(reportRange==='last')return state.sessions.slice(0,1);const cut=Date.now()-Number(reportRange)*864e5;return state.sessions.filter(s=>s.start>=cut)}
function reportStats(){const ss=reportSessions(),events=ss.flatMap(ev),minutes=ss.reduce((n,s)=>n+mins(s),0),sets=events.reduce((n,e)=>n+(e.kind==='strength'?Number(e.sets)||0:1),0),freq={};events.forEach(e=>freq[e.name]=(freq[e.name]||0)+1);const top=Object.entries(freq).sort((a,b)=>b[1]-a[1]).slice(0,4),mc=muscleCounts(ss),topMuscles=Object.entries(mc).filter(([,v])=>v).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([m])=>m);return{ss,events,minutes,sets,top,topMuscles}}
function renderReport(){const r=reportStats();$$('#reportRange button').forEach(b=>b.classList.toggle('active',b.dataset.range===reportRange));const dates=r.ss.length?`${dlabel(r.ss[r.ss.length-1].start)} — ${dlabel(r.ss[0].start)}`:dlabel(Date.now());$('#reportPreview').innerHTML=`<div class="reportBrand">AXIS${state.profile.name?' · '+esc(state.profile.name):''}</div><div class="reportDate">${dates}</div><div class="reportBig">${r.minutes}<span> 分钟</span></div><div class="reportStats"><div><b>${r.ss.length}</b><span>训练</span></div><div><b>${r.events.length}</b><span>项目</span></div><div><b>${r.sets}</b><span>组</span></div></div><div class="reportList">${r.top.map(([n,c])=>`<div><b>${esc(n)}</b><span>${c}次</span></div>`).join('')}${r.topMuscles.length?`<div><b>主要锻炼</b><span>${r.topMuscles.join(' · ')}</span></div>`:''}</div>`}
async function makeReportImage(){const r=reportStats();if(!r.ss.length){toast('暂无记录');return null}const cv=D.createElement('canvas');cv.width=1080;cv.height=1350;const c=cv.getContext('2d');c.fillStyle='#f1f0ec';c.fillRect(0,0,1080,1350);c.fillStyle='#0d0f12';c.font='700 38px -apple-system,BlinkMacSystemFont,Arial';c.fillText('AXIS'+(state.profile.name?' · '+state.profile.name:''),80,92);c.font='500 28px -apple-system,BlinkMacSystemFont,Arial';c.fillStyle='#777b82';c.fillText(`${dlabel(r.ss[r.ss.length-1].start)} — ${dlabel(r.ss[0].start)}`,80,190);c.fillStyle='#0d0f12';c.font='650 128px -apple-system,BlinkMacSystemFont,Arial';c.fillText(String(r.minutes),80,355);c.font='500 32px -apple-system,BlinkMacSystemFont,Arial';c.fillStyle='#777b82';c.fillText('分钟',350,350);c.strokeStyle='#d5d4d0';c.lineWidth=2;c.beginPath();c.moveTo(80,430);c.lineTo(1000,430);c.stroke();[[r.ss.length,'训练'],[r.events.length,'项目'],[r.sets,'组']].forEach((x,i)=>{const x0=80+i*305;c.fillStyle='#0d0f12';c.font='650 50px -apple-system,BlinkMacSystemFont,Arial';c.fillText(String(x[0]),x0,520);c.fillStyle='#777b82';c.font='500 25px -apple-system,BlinkMacSystemFont,Arial';c.fillText(x[1],x0,560)});let y=690;c.fillStyle='#0d0f12';c.font='650 30px -apple-system,BlinkMacSystemFont,Arial';c.fillText('训练记录',80,y);y+=60;r.top.slice(0,5).forEach(([n,count])=>{c.fillStyle='#0d0f12';c.font='600 29px -apple-system,BlinkMacSystemFont,Arial';c.fillText(n.slice(0,18),80,y);c.fillStyle='#777b82';c.font='500 26px -apple-system,BlinkMacSystemFont,Arial';c.fillText(count+'次',880,y);c.strokeStyle='#deddd9';c.beginPath();c.moveTo(80,y+28);c.lineTo(1000,y+28);c.stroke();y+=82});if(r.topMuscles.length){c.fillStyle='#777b82';c.font='500 26px -apple-system,BlinkMacSystemFont,Arial';c.fillText('主要锻炼',80,1180);c.fillStyle='#0d0f12';c.font='600 31px -apple-system,BlinkMacSystemFont,Arial';c.fillText(r.topMuscles.join(' · '),80,1230)}c.fillStyle='#737cff';c.fillRect(80,1285,120,8);return new Promise(res=>cv.toBlob(res,'image/jpeg',.92))}
async function backupData(){const blob=new Blob([JSON.stringify({version:VERSION,exportedAt:new Date().toISOString(),sessions:state.sessions,profile:state.profile,prefs:state.prefs},null,2)],{type:'application/json'});await shareBlob(blob,`AXIS-备份-${dlabel(Date.now())}.json`,'application/json')}
function bind(){
$('#startBtn').onclick=()=>{state.active={id:uid('S'),start:Date.now(),events:[]};save();render();toast('已开始')};
$('#settingsBtn').onclick=()=>{openSheet('settingsSheet');aiHealth();updateStorageBrief()};
$('#scanBtn').onclick=()=>{resetScan();captureMode=String(state.prefs.scanSeconds||3);$$('#captureModes button').forEach(b=>b.classList.toggle('active',b.dataset.mode===captureMode));setText('#captureNow',captureMode==='photo'?'拍照':`开始扫描 ${captureMode} 秒`);openSheet('scanSheet');startCamera()};
$$('[data-close]').forEach(b=>b.onclick=()=>closeSheet(b.dataset.close));$$('.sheetWrap').forEach(w=>w.onclick=e=>{if(e.target===w&&w.id!=='finishSheet')closeSheet(w.id)});
$('#captureModes').onclick=e=>{const b=e.target.closest('[data-mode]');if(!b)return;captureMode=b.dataset.mode;$$('#captureModes button').forEach(x=>x.classList.toggle('active',x===b));setText('#captureNow',captureMode==='photo'?'拍照':`开始扫描 ${captureMode} 秒`)};
$('#captureNow').onclick=captureNow;
$('#photoInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;state.frames=[await frameFromFile(f)];state.clip=null;reviewFrames();e.target.value=''};
$('#equipmentRow').onclick=()=>{renderEqList();openSheet('eqSheet')};$('#eqSearch').oninput=e=>renderEqList(e.target.value);$('#addCustomEq').onclick=()=>{closeSheet('eqSheet');openCustomEditor()};
$('#customType').onclick=e=>{const b=e.target.closest('[data-type]');if(!b)return;$$('#customType button').forEach(x=>x.classList.remove('active'));b.classList.add('active')};$('#customMuscles').onclick=e=>e.target.closest('[data-muscle]')?.classList.toggle('active');$('#saveCustomEq').onclick=saveCustomEq;$('#deleteCustomEq').onclick=deleteCustomEq;
D.addEventListener('click',e=>{const b=e.target.closest('[data-step],[data-choice],[data-quick]');if(!b)return;if(b.dataset.step){const id=b.dataset.step,el=$('#'+id),min=id==='weight'?0:1,max=id==='weight'?1000:600;let n=Number(el.value)||0;n=Math.max(min,Math.min(max,n+Number(b.dataset.delta||0)));el.value=id==='weight'?Math.round(n*10)/10:Math.round(n);if(id==='weight')renderQuick('#weightQuick',weightQuickValues({weight:n}),n,'weight');return}if(b.dataset.choice){$$(`[data-choice="${b.dataset.choice}"]`).forEach(x=>x.classList.remove('active'));b.classList.add('active');return}if(b.dataset.quick){setVal(b.dataset.quick,Number(b.dataset.value));$$(`[data-quick="${b.dataset.quick}"]`).forEach(x=>x.classList.toggle('active',x===b))}});
$('#saveScan').onclick=saveScan;
$('#finishHold').addEventListener('pointerdown',e=>{e.preventDefault();e.currentTarget.setPointerCapture?.(e.pointerId);finishStartHold()});['pointerup','pointercancel','pointerleave'].forEach(t=>$('#finishHold').addEventListener(t,finishCancelHold));$('#finishDone').onclick=()=>{closeSheet('finishSheet');render()};
$$('.nav button').forEach(b=>b.onclick=()=>{$$('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.view).classList.add('active');render()});
$('#profileBtn').onclick=()=>{fillProfile();openSheet('profileSheet')};$('#saveProfile').onclick=saveProfile;$$('#profileFreq button').forEach(b=>b.onclick=()=>{$$('#profileFreq button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});$$('#profileGoal button').forEach(b=>b.onclick=()=>{$$('#profileGoal button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
$('#myEqBtn').onclick=()=>{renderManageEq();openSheet('myEqSheet')};$('#newCustomEq').onclick=()=>openCustomEditor();
$('#watermarkBtn').onclick=()=>{renderWatermarkSettings();openSheet('watermarkSheet')};[['wmName','name'],['wmData','data'],['wmTime','time'],['wmBrand','brand']].forEach(([id,k])=>$('#'+id).onclick=()=>{state.prefs.watermark[k]=!state.prefs.watermark[k];save();renderWatermarkSettings()});$('#watermarkPreview').onclick=e=>{const b=e.target.closest('[data-pos]');if(!b)return;state.prefs.watermark.pos=b.dataset.pos;save();renderWatermarkSettings()};$$('#photoWmMode button').forEach(b=>b.onclick=()=>{state.prefs.watermark.photoMode=b.dataset.value;save();renderWatermarkSettings()});$$('#videoWmMode button').forEach(b=>b.onclick=()=>{state.prefs.watermark.videoMode=b.dataset.value;save();renderWatermarkSettings()});
$('#keepClipSwitch').onclick=()=>{state.prefs.keepClip=!state.prefs.keepClip;save();renderSettings()};$$('#scanSeconds button').forEach(b=>b.onclick=()=>{state.prefs.scanSeconds=Number(b.dataset.sec);save();renderSettings()});
$('#storageBtn').onclick=async()=>{openSheet('storageSheet');await renderStorage()};$('#clearVideos').onclick=clearVideos;$('#backupBtn').onclick=backupData;$('#selectAllSessions').onclick=()=>{$$('[data-delete-session]').forEach(b=>{selectedSessions.add(b.dataset.deleteSession);b.classList.add('selected')})};$('#deleteSelected').onclick=async()=>{if(!selectedSessions.size)return toast('请选择训练');if(!confirm(`删除 ${selectedSessions.size} 次训练？`))return;await deleteSessions([...selectedSessions]);selectedSessions.clear();await renderStorage();render();toast('已删除')};$('#clearAll').onclick=clearAll;
$('#reportBtn').onclick=()=>{reportRange='last';renderReport();openSheet('reportSheet')};$$('#reportRange button').forEach(b=>b.onclick=()=>{reportRange=b.dataset.range;renderReport()});$('#shareReport').onclick=async()=>{const blob=await makeReportImage();if(blob)shareBlob(blob,`AXIS-训练报告-${dlabel(Date.now())}.jpg`,'image/jpeg')};
D.addEventListener('contextmenu',e=>{if(e.target.closest('button'))e.preventDefault()});D.addEventListener('selectstart',e=>{if(e.target.closest('button'))e.preventDefault()});window.addEventListener('pageshow',render);D.addEventListener('visibilitychange',()=>{if(!D.hidden)render()})
}
load();buildChoices();bind();render();aiHealth();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
})();