(function(){'use strict';
var D=document,$=function(s,r){return(r||D).querySelector(s)},$$=function(s,r){return Array.from((r||D).querySelectorAll(s))};
var VERSION=40,KEY='axis_v40_state',DB='axis_v40_media';
var PAT={push:'推',pull:'拉',knee:'腿',hinge:'後鏈',cardio:'有氧',core:'核心'};
var EQ=[
{id:'cable',name:'多功能龍門架',pattern:'pull',type:'strength'},{id:'lat',name:'高位下拉',pattern:'pull',type:'strength'},{id:'row',name:'坐姿 / 胸托划船',pattern:'pull',type:'strength'},{id:'pec',name:'飛鳥 / 後三角',pattern:'push',type:'strength'},{id:'chest',name:'胸推',pattern:'push',type:'strength'},{id:'shoulder',name:'肩推',pattern:'push',type:'strength'},{id:'dip',name:'雙槓 / 抬腿',pattern:'core',type:'strength'},{id:'arms',name:'手臂',pattern:'pull',type:'strength'},{id:'legpress',name:'坐姿腿推',pattern:'knee',type:'strength'},{id:'hack',name:'哈克 / 斜腿推',pattern:'knee',type:'strength'},{id:'legext',name:'腿屈伸',pattern:'knee',type:'strength'},{id:'legcurl',name:'腿彎舉',pattern:'hinge',type:'strength'},{id:'calf',name:'小腿',pattern:'hinge',type:'strength'},{id:'dumbbell',name:'啞鈴',pattern:'push',type:'strength'},{id:'barbell',name:'槓鈴',pattern:'hinge',type:'strength'},{id:'bodyweight',name:'徒手',pattern:'core',type:'cardio'},{id:'elliptical',name:'橢圓機',pattern:'cardio',type:'cardio'},{id:'rower',name:'划船機',pattern:'cardio',type:'cardio'},{id:'treadmill',name:'跑步機 / 跑步',pattern:'cardio',type:'cardio'},{id:'walk',name:'步行',pattern:'cardio',type:'cardio'}];
var state={sessions:[],active:null,selectedEq:null,frames:[],stream:null,ai:null},timer=null,toastTimer=null;
function load(){try{var x=JSON.parse(localStorage.getItem(KEY)||'null');if(x&&x.version===VERSION){state.sessions=Array.isArray(x.sessions)?x.sessions:[];state.active=x.active||null}}catch(e){}}
function save(){try{localStorage.setItem(KEY,JSON.stringify({version:VERSION,sessions:state.sessions,active:state.active}))}catch(e){}}
function uid(p){return p+'-'+Date.now().toString(36).toUpperCase()+Math.random().toString(36).slice(2,6).toUpperCase()}function pad(n){return String(n).padStart(2,'0')}function dlabel(t){var d=new Date(t);return d.getFullYear()+'.'+pad(d.getMonth()+1)+'.'+pad(d.getDate())}function tlabel(t){var d=new Date(t);return pad(d.getHours())+':'+pad(d.getMinutes())}function mins(s){return Math.max(0,Math.round(((s.end||Date.now())-s.start)/60000))}function ev(s){return s&&Array.isArray(s.events)?s.events:[]}function setText(s,v){var e=$(s);if(e)e.textContent=v}function esc(s){return String(s).replace(/[&<>"']/g,function(m){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]})}function recent(days){var cut=Date.now()-days*864e5;return state.sessions.filter(function(s){return s.start>=cut}).concat(state.active&&state.active.start>=cut?[state.active]:[])}
function toast(msg){var e=$('#toast');e.textContent=msg;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(function(){e.classList.remove('show')},1600)}function openSheet(id){$('#'+id).classList.add('show')}function closeSheet(id){var e=$('#'+id);if(e)e.classList.remove('show');if(id==='scanSheet')stopCamera()}
function countPatterns(ss){var c={push:0,pull:0,knee:0,hinge:0,cardio:0,core:0};ss.forEach(function(s){ev(s).forEach(function(e){if(c[e.pattern]!=null)c[e.pattern]++})});return c}
function lastEvent(id){var all=(state.active?[state.active]:[]).concat(state.sessions);for(var i=0;i<all.length;i++){var a=ev(all[i]);for(var j=0;j<a.length;j++)if(a[j].equipmentId===id)return a[j]}return null}
function usage(id){var n=0,last=0;state.sessions.forEach(function(s){ev(s).forEach(function(e){if(e.equipmentId===id){n++;last=Math.max(last,e.time)}})});if(state.active)ev(state.active).forEach(function(e){if(e.equipmentId===id){n++;last=Math.max(last,e.time)}});return{n:n,last:last}}
function concreteSignal(){if(!state.sessions.length)return null;var all=[];state.sessions.forEach(function(s){ev(s).forEach(function(e){all.push(e)})});var groups={};all.forEach(function(e){(groups[e.equipmentId]||(groups[e.equipmentId]=[])).push(e)});for(var id in groups){var g=groups[id].filter(function(e){return e.kind==='strength'}).sort(function(a,b){return b.time-a.time});if(g.length>=2&&Number(g[0].weight)>Number(g[1].weight)&&g[0].reps>=g[1].reps-2){return '<strong>'+esc(g[0].name)+' '+g[1].weight+' → '+g[0].weight+' kg</strong><small>最近兩次負重提高</small>'}}var c=countPatterns(recent(30)),keys=['push','pull','knee','hinge','cardio'].sort(function(a,b){return c[a]-c[b]});if(c[keys[0]]===0&&all.length>=3)return '<strong>最近沒有'+PAT[keys[0]]+'</strong><small>近 30 天尚未出現這類紀錄</small>';return '<strong>'+state.sessions.length+' 次訓練已留下</strong><small>AXIS 會只在有明確變化時提示</small>'}
function liveSignal(){if(!state.active)return null;var a=ev(state.active),last=a.length?a[a.length-1].time:state.active.start,idle=(Date.now()-last)/60000;if(idle>10)return '<strong>已停 '+Math.floor(idle)+' 分鐘</strong><small>如果還在休息，可以直接掃下一台</small>';if(a.length>=2){var c=countPatterns([state.active]),missing=['push','pull','knee','hinge','cardio'].filter(function(k){return c[k]===0});if(missing.length)return '<strong>今天還沒有'+PAT[missing[0]]+'</strong><small>只是一個缺口提示，不是課表</small>'}return null}
function render(){setText('#todayDate',new Intl.DateTimeFormat('zh-Hant',{month:'2-digit',day:'2-digit',weekday:'short'}).format(new Date()));var r7=recent(7),wm=r7.reduce(function(a,s){return a+mins(s)},0),ws=r7.filter(function(s){return s!==state.active}).length+(state.active?1:0);setText('#weekMins',wm);setText('#weekSessions',ws);setText('#lastSession',state.sessions[0]?dlabel(state.sessions[0].start)+' · '+mins(state.sessions[0])+' MIN':'—');$('#idleHome').classList.toggle('hidden',!!state.active);$('#activeHome').classList.toggle('hidden',!state.active);$('#dock').classList.toggle('show',!!state.active);var sig=concreteSignal();$('#idleSignalWrap').classList.toggle('hidden',!sig);if(sig)$('#idleSignal').innerHTML=sig;if(state.active){renderLive();startTimer()}else stopTimer();renderHistory();renderInsights();bindDynamic();hydrateThumbs()}
function renderLive(){var a=ev(state.active);setText('#liveItems',a.length);setText('#liveSets',a.reduce(function(n,e){return n+(e.kind==='strength'?Number(e.sets)||0:1)},0));setText('#eventCount',a.length);$('#eventList').innerHTML=a.length?a.slice().reverse().map(eventHtml).join(''):'<div class="empty">掃一下，留下第一個紀錄</div>';var s=liveSignal();$('#liveSignalWrap').classList.toggle('hidden',!s);if(s)$('#liveSignal').innerHTML=s;var last=a.length?a[a.length-1].time:state.active.start,idle=(Date.now()-last)/60000;setText('#pace',idle>10?'已停 '+Math.floor(idle)+'m':idle>6?'休息偏久':'正常')}
function startTimer(){stopTimer();function tick(){if(!state.active)return;var sec=Math.floor((Date.now()-state.active.start)/1000);setText('#liveTimer',pad(Math.floor(sec/60))+':'+pad(sec%60));if(sec%15===0)renderLive()}tick();timer=setInterval(tick,1000)}function stopTimer(){if(timer){clearInterval(timer);timer=null}}
function eventHtml(e){var meta=e.kind==='strength'?e.weight+'kg · '+e.reps+'×'+e.sets:e.duration+'min · '+e.intensity+'/10';return '<button class="card event" data-event="'+e.id+'"><span class="thumb" '+(e.frameRefs&&e.frameRefs[0]?'data-photo="'+e.frameRefs[0]+'"':'')+'>'+(e.frameRefs&&e.frameRefs[0]?'':'•')+'</span><span><strong>'+esc(e.name)+'</strong><small>'+esc(meta)+'</small></span><span class="time">'+tlabel(e.time)+'</span></button>'}
function renderHistory(){setText('#historyCount',state.sessions.length);$('#historyList').innerHTML=state.sessions.length?state.sessions.map(function(s){return '<button class="card history" data-session="'+s.id+'"><span><strong>'+dlabel(s.start)+'</strong><small>'+mins(s)+' 分鐘 · '+ev(s).length+' 項</small></span><b>'+tlabel(s.start)+'</b></button>'}).join(''):'<div class="empty">尚無紀錄</div>'}
function renderInsights(){var r7=recent(7),r30=recent(30);setText('#insightMins',r7.reduce(function(a,s){return a+mins(s)},0));setText('#insightSessions',r30.filter(function(s){return s!==state.active}).length+(state.active?1:0));var c=countPatterns(r30),keys=['push','pull','knee','hinge','cardio'],max=Math.max(1,c.push,c.pull,c.knee,c.hinge,c.cardio);$('#patternBars').innerHTML=keys.map(function(k){return '<div class="bar"><span>'+PAT[k]+'</span><div class="track"><i style="width:'+Math.round(c[k]/max*100)+'%"></i></div><span>'+c[k]+'</span></div>'}).join('');var items=[];var s=concreteSignal();if(s)items.push('<div class="card signal">'+s+'</div>');var fav=EQ.map(function(e){return{e:e,u:usage(e.id)}}).sort(function(a,b){return b.u.n-a.u.n})[0];if(fav&&fav.u.n>1)items.push('<div class="card signal"><strong>'+esc(fav.e.name)+' · '+fav.u.n+' 次</strong><small>近來最常留下的器械</small></div>');$('#signals').innerHTML=items.join('')||'<div class="empty">有足夠紀錄後才顯示訊號</div>'}
function bindDynamic(){$$('[data-event]').forEach(function(b){b.onclick=function(){openEvent(b.dataset.event)}});$$('[data-session]').forEach(function(b){b.onclick=function(){openSession(b.dataset.session)}})}
async function startCamera(){stopCamera();var video=$('#cameraVideo'),fb=$('#cameraFallback');fb.classList.add('hidden');try{if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia)throw new Error('unsupported');state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:960}},audio:false});video.srcObject=state.stream;await video.play();setText('#scanState','READY')}catch(e){console.error(e);fb.classList.remove('hidden');setText('#scanState','PHOTO')}}function stopCamera(){if(state.stream){state.stream.getTracks().forEach(function(t){t.stop()});state.stream=null}var v=$('#cameraVideo');if(v)v.srcObject=null}
function digest(buf){if(window.crypto&&crypto.subtle)return crypto.subtle.digest('SHA-256',buf).then(function(h){return Array.from(new Uint8Array(h)).map(function(b){return b.toString(16).padStart(2,'0')}).join('')});var a=new Uint8Array(buf),h=2166136261;for(var i=0;i<a.length;i++)h=Math.imul(h^a[i],16777619)>>>0;return Promise.resolve(('00000000'+h.toString(16)).slice(-8).repeat(8))}
function watermarkCanvas(cv,idx){var ctx=cv.getContext('2d'),w=cv.width,h=cv.height,ts=Date.now(),sid=state.active?state.active.id:'NOSESSION',code=(sid.slice(-5)+'-'+String(ts).slice(-5)+'-'+idx).toUpperCase(),font=Math.max(15,Math.round(w*.019)),p=Math.max(16,Math.round(w*.022)),line=Math.round(font*1.4);ctx.save();ctx.textBaseline='bottom';ctx.font='650 '+font+'px -apple-system,BlinkMacSystemFont,Arial';var a='AXIS  LIVE',b=dlabel(ts)+'  '+new Date(ts).toLocaleTimeString('en-GB',{hour12:false}),tw=Math.max(ctx.measureText(a).width,ctx.measureText(b).width),bw=tw+p*1.45,bh=line*2+p;ctx.fillStyle='rgba(6,7,9,.78)';ctx.fillRect(p,h-bh-p,bw,bh);ctx.fillStyle='#f6f5f1';ctx.fillText(a,p*1.45,h-p-line);ctx.font='500 '+Math.round(font*.82)+'px -apple-system,BlinkMacSystemFont,Arial';ctx.fillText(b,p*1.45,h-p);ctx.fillStyle='#aeb4ff';ctx.fillText(code,p*1.45,h-p+line*.72);ctx.restore();return{ts:ts,proof:code}}
async function frameFromVideo(idx){var v=$('#cameraVideo');if(!v.videoWidth)throw new Error('camera-not-ready');var max=960,scale=Math.min(1,max/v.videoWidth),cv=D.createElement('canvas');cv.width=Math.round(v.videoWidth*scale);cv.height=Math.round(v.videoHeight*scale);cv.getContext('2d',{alpha:false}).drawImage(v,0,0,cv.width,cv.height);var m=watermarkCanvas(cv,idx),blob=await new Promise(function(r){cv.toBlob(r,'image/jpeg',.76)}),hash=await digest(await blob.arrayBuffer()),url=URL.createObjectURL(blob);return{blob:blob,url:url,hash:hash,ts:m.ts,proof:m.proof}}
async function frameFromFile(file,idx){var u=URL.createObjectURL(file),img=new Image();await new Promise(function(res,rej){img.onload=res;img.onerror=rej;img.src=u});var max=960,scale=Math.min(1,max/img.naturalWidth),cv=D.createElement('canvas');cv.width=Math.round(img.naturalWidth*scale);cv.height=Math.round(img.naturalHeight*scale);cv.getContext('2d',{alpha:false}).drawImage(img,0,0,cv.width,cv.height);URL.revokeObjectURL(u);var m=watermarkCanvas(cv,idx),blob=await new Promise(function(r){cv.toBlob(r,'image/jpeg',.76)}),hash=await digest(await blob.arrayBuffer()),url=URL.createObjectURL(blob);return{blob:blob,url:url,hash:hash,ts:m.ts,proof:m.proof}}
function sleep(ms){return new Promise(function(r){setTimeout(r,ms)})}
async function liveScan(){if(!state.stream){$('#photoInput').click();return}var b=$('#liveScanBtn');b.disabled=true;state.frames=[];try{for(var i=0;i<4;i++){setText('#scanState',String(3-i*.7).slice(0,3)+'s');state.frames.push(await frameFromVideo(i));if(i<3)await sleep(650)}reviewFrames()}catch(e){console.error(e);toast('掃描失敗');b.disabled=false;setText('#scanState','READY')}}
function reviewFrames(){stopCamera();$('#captureStage').classList.add('hidden');$('#reviewStage').classList.remove('hidden');$('#film').innerHTML=state.frames.map(function(f){return '<img src="'+f.url+'">'}).join('');state.selectedEq=null;state.ai=null;setText('#equipmentName','未識別');setText('#aiStatus','辨識中');updateFields();analyzeFrames()}
function blobData(blob){return new Promise(function(res,rej){var r=new FileReader();r.onload=function(){res(r.result)};r.onerror=rej;r.readAsDataURL(blob)})}
async function analyzeFrames(){try{var frames=await Promise.all(state.frames.map(function(f){return blobData(f.blob)})),recentEq=[];state.sessions.slice(0,8).forEach(function(s){ev(s).forEach(function(e){if(recentEq.indexOf(e.equipmentId)<0)recentEq.push(e.equipmentId)})});var resp=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({frames:frames,recentEquipment:recentEq})});var data=await resp.json();if(!resp.ok||!data.available){setText('#aiStatus','手動確認');return}state.ai=data.result||null;if(state.ai&&state.ai.equipmentId&&EQ.some(function(e){return e.id===state.ai.equipmentId})){selectEq(state.ai.equipmentId,false);if(Number.isFinite(Number(state.ai.weightKg))&&$('#weight'))$('#weight').value=String(Math.round(Number(state.ai.weightKg)*2)/2);if(state.ai.cardio&&Number.isFinite(Number(state.ai.cardio.durationMin)))$('#duration').value=String(Math.max(1,Math.round(Number(state.ai.cardio.durationMin))));syncViews();setText('#aiStatus','百煉 · '+Math.round((Number(state.ai.confidence)||0)*100)+'%')}else setText('#aiStatus','手動確認')}catch(e){console.error(e);setText('#aiStatus','手動確認')}}
function openScan(){if(!state.active){toast('先開始訓練');return}state.frames=[];state.selectedEq=null;state.ai=null;$('#captureStage').classList.remove('hidden');$('#reviewStage').classList.add('hidden');$('#liveScanBtn').disabled=false;setText('#scanState','READY');openSheet('scanSheet');startCamera()}
function renderEqList(){var q=$('#eqSearch').value.trim().toLowerCase(),arr=EQ.slice().sort(function(a,b){var ua=usage(a.id),ub=usage(b.id);return ub.last-ua.last||ub.n-ua.n||a.name.localeCompare(b.name)}).filter(function(e){return !q||e.name.toLowerCase().includes(q)});$('#eqList').innerHTML=arr.map(function(e){var u=usage(e.id);return '<button class="eq" data-eq="'+e.id+'"><strong>'+esc(e.name)+'</strong><small>'+(u.n?u.n+' 次':'')+'</small></button>'}).join('');$$('[data-eq]',$('#eqList')).forEach(function(b){b.onclick=function(){selectEq(b.dataset.eq,true)}})}
function selectEq(id,close){state.selectedEq=id;var e=EQ.find(function(x){return x.id===id});setText('#equipmentName',e?e.name:'未識別');updateFields();if(close)closeSheet('eqSheet')}
function updateFields(){var e=EQ.find(function(x){return x.id===state.selectedEq});$('#strengthFields').classList.toggle('hidden',!e||e.type!=='strength');$('#cardioFields').classList.toggle('hidden',!e||e.type==='strength');if(e){var last=lastEvent(e.id);if(last&&e.type==='strength'){$('#weight').value=last.weight||20;$('#reps').value=last.reps||10;$('#sets').value=last.sets||3}if(last&&e.type!=='strength'){$('#duration').value=last.duration||15;$('#intensity').value=last.intensity||5}}syncViews()}
function syncViews(){[['weight','weightView'],['reps','repsView'],['sets','setsView'],['duration','durationView'],['intensity','intensityView']].forEach(function(p){var i=$('#'+p[0]),v=$('#'+p[1]);if(i&&v)v.textContent=i.value})}
function nval(id,min,max,def){var n=Number($('#'+id).value);if(!Number.isFinite(n))n=def;return Math.max(min,Math.min(max,n))}
function db(){return new Promise(function(res,rej){var q=indexedDB.open(DB,1);q.onupgradeneeded=function(){if(!q.result.objectStoreNames.contains('media'))q.result.createObjectStore('media')};q.onsuccess=function(){res(q.result)};q.onerror=function(){rej(q.error)}})}
async function putMedia(k,b){var d=await db();return new Promise(function(res,rej){var tx=d.transaction('media','readwrite');tx.objectStore('media').put(b,k);tx.oncomplete=function(){d.close();res()};tx.onerror=function(){d.close();rej(tx.error)}})}async function getMedia(k){var d=await db();return new Promise(function(res,rej){var tx=d.transaction('media','readonly'),q=tx.objectStore('media').get(k);q.onsuccess=function(){d.close();res(q.result||null)};q.onerror=function(){d.close();rej(q.error)}})}async function mediaUrl(k){try{var b=await getMedia(k);return b?URL.createObjectURL(b):null}catch(e){return null}}
async function saveScan(){var eq=EQ.find(function(x){return x.id===state.selectedEq});if(!eq){openSheet('eqSheet');renderEqList();toast('先確認器械');return}if(!state.frames.length){toast('先掃一下');return}var e={id:uid('E'),equipmentId:eq.id,name:eq.name,pattern:eq.pattern,kind:eq.type==='strength'?'strength':'cardio',time:Date.now(),source:state.frames.length>1?'live-scan':'photo',frameRefs:[],frameProofs:state.frames.map(function(f){return f.proof}),frameHashes:state.frames.map(function(f){return f.hash}),ai:state.ai?{confidence:state.ai.confidence||0,model:state.ai.model||'bailian'}:null};if(e.kind==='strength'){e.weight=nval('weight',0,1000,20);e.reps=nval('reps',1,100,10);e.sets=nval('sets',1,20,3)}else{e.duration=nval('duration',1,300,15);e.intensity=nval('intensity',1,10,5)}try{for(var i=0;i<state.frames.length;i++){var ref=e.id+'-F'+i;e.frameRefs.push(ref);await putMedia(ref,state.frames[i].blob)}}catch(err){console.error(err);toast('照片儲存失敗');return}state.active.events.push(e);save();closeSheet('scanSheet');state.frames=[];state.selectedEq=null;render();toast('已記下')}
async function hydrateThumbs(){var boxes=$$('[data-photo]');for(var i=0;i<boxes.length;i++){var b=boxes[i];if(b.dataset.loaded)continue;b.dataset.loaded='1';var u=await mediaUrl(b.dataset.photo);if(u)b.innerHTML='<img src="'+u+'">'}}
async function openEvent(id){var all=(state.active?[state.active]:[]).concat(state.sessions),f=null;for(var i=0;i<all.length;i++){f=ev(all[i]).find(function(e){return e.id===id});if(f)break}if(!f)return;setText('#detailTitle',f.name);var imgs=[];for(var j=0;j<(f.frameRefs||[]).length;j++){var u=await mediaUrl(f.frameRefs[j]);if(u)imgs.push('<img src="'+u+'">')}var rows=f.kind==='strength'?[['重量',f.weight+' kg'],['次數',f.reps],['組數',f.sets]]:[['時間',f.duration+' 分鐘'],['強度',f.intensity+' / 10']];rows.push(['Capture',f.source==='live-scan'?'Live Scan':'Photo'],['時間',dlabel(f.time)+' '+tlabel(f.time)]);$('#detail').innerHTML=(imgs.length?'<div class="detailFilm">'+imgs.join('')+'</div>':'')+'<div class="detailList">'+rows.map(function(r){return '<div class="detailRow"><span>'+r[0]+'</span><span>'+r[1]+'</span></div>'}).join('')+'</div>';openSheet('detailSheet')}
function openSession(id){var s=state.sessions.find(function(x){return x.id===id});if(!s)return;setText('#detailTitle',dlabel(s.start));$('#detail').innerHTML='<div class="events">'+ev(s).map(eventHtml).join('')+'</div>';openSheet('detailSheet');bindDynamic();hydrateThumbs()}
function finishOpen(){if(!state.active)return;var a=ev(state.active);$('#finishSummary').innerHTML='<strong>'+mins(state.active)+' 分鐘 · '+a.length+' 項</strong><small>'+ (a.length?'這就是今天真實留下的紀錄。':'今天還沒有留下任何項目。') +'</small>';openSheet('finishSheet')}
function finish(){if(!state.active)return;state.active.end=Date.now();state.sessions.unshift(state.active);state.active=null;save();closeSheet('finishSheet');render();toast('已結束')}
async function health(){try{var r=await fetch('/api/analyze',{cache:'no-store'}),j=await r.json();setText('#aiHealth',j.available?'百煉 · '+(j.model||'Qwen'):'未配置')}catch(e){setText('#aiHealth','未配置')}}
function clearDb(){return new Promise(function(res){var q=indexedDB.deleteDatabase(DB);q.onsuccess=q.onerror=q.onblocked=function(){res()}})}
function bind(){
$('#startBtn').onclick=function(){state.active={id:uid('S'),start:Date.now(),mode:'gym',events:[]};save();render();toast('已開始')};$('#finishBtn').onclick=finishOpen;$('#confirmFinish').onclick=finish;$('#scanBtn').onclick=openScan;$('#settingsBtn').onclick=function(){openSheet('settingsSheet');health()};
$$('[data-close]').forEach(function(b){b.onclick=function(){closeSheet(b.dataset.close)}});$$('.sheetWrap').forEach(function(w){w.addEventListener('click',function(e){if(e.target===w)closeSheet(w.id)})});
$('#liveScanBtn').onclick=liveScan;$('#photoBtn').onclick=function(){$('#photoInput').click()};$('#photoInput').onchange=async function(){var f=this.files&&this.files[0];if(!f)return;try{state.frames=[await frameFromFile(f,0)];reviewFrames()}catch(e){console.error(e);toast('照片處理失敗')}this.value=''};$('#equipmentRow').onclick=function(){openSheet('eqSheet');$('#eqSearch').value='';renderEqList()};$('#eqSearch').oninput=renderEqList;$('#saveScan').onclick=saveScan;
D.addEventListener('click',function(e){var b=e.target.closest('[data-step]');if(!b)return;var id=b.dataset.step,i=$('#'+id);if(!i)return;var min=id==='weight'?0:1,max=id==='weight'?1000:(id==='reps'?100:(id==='sets'?20:(id==='duration'?300:10))),n=Number(i.value)||0;n=Math.max(min,Math.min(max,n+Number(b.dataset.delta||0)));i.value=id==='weight'?String(Math.round(n*2)/2):String(Math.round(n));syncViews()});
$$('.nav button').forEach(function(b){b.onclick=function(){$$('.nav button').forEach(function(x){x.classList.remove('active')});b.classList.add('active');$$('.view').forEach(function(v){v.classList.remove('active')});$('#'+b.dataset.view).classList.add('active');render()}});
$('#exportBtn').onclick=function(){var blob=new Blob([JSON.stringify({version:VERSION,exportedAt:new Date().toISOString(),sessions:state.sessions,active:state.active},null,2)],{type:'application/json'}),a=D.createElement('a');a.href=URL.createObjectURL(blob);a.download='AXIS-'+dlabel(Date.now())+'.json';D.body.appendChild(a);a.click();a.remove();toast('已匯出')};$('#clearBtn').onclick=async function(){if(!confirm('清除本機 AXIS 資料？'))return;localStorage.removeItem(KEY);await clearDb();state={sessions:[],active:null,selectedEq:null,frames:[],stream:null,ai:null};closeSheet('settingsSheet');render();toast('已清除')};window.addEventListener('pageshow',render);D.addEventListener('visibilitychange',function(){if(!D.hidden)render()})}
load();bind();render();health();if('serviceWorker'in navigator&&location.protocol.indexOf('http')===0){window.addEventListener('load',function(){navigator.serviceWorker.register('/sw.js').catch(function(){})})}
})();
