(function(){'use strict';
const D=document,$=(s,r)=>(r||D).querySelector(s),$$=(s,r)=>Array.from((r||D).querySelectorAll(s));
const VERSION=50,KEY='axis_v50_state',OLD42='axis_v42_state',OLD40='axis_v40_state',DB='axis_v42_media';
const MUSCLES=['胸肌','背部','肩部','肱二头肌','肱三头肌','核心','臀部','股四头肌','腘绳肌','小腿','心肺'];
const BASE_EQ=[
{id:'cable',name:'多功能龙门架',type:'strength',pattern:'pull',muscles:['背部','胸肌','肩部','肱二头肌','肱三头肌'],effect:'多方向力量'},
{id:'lat',name:'高位下拉',type:'strength',pattern:'pull',muscles:['背部','肱二头肌'],effect:'背部宽度'},
{id:'row',name:'坐姿 / 胸托划船',type:'strength',pattern:'pull',muscles:['背部','肱二头肌'],effect:'背部厚度'},
{id:'pec',name:'飞鸟 / 后三角',type:'strength',pattern:'push',muscles:['胸肌','肩部'],effect:'胸部与肩后侧'},
{id:'chest',name:'胸推',type:'strength',pattern:'push',muscles:['胸肌','肱三头肌','肩部'],effect:'胸部推力'},
{id:'shoulder',name:'肩推',type:'strength',pattern:'push',muscles:['肩部','肱三头肌'],effect:'肩部推力'},
{id:'dip',name:'双杠 / 抬腿',type:'strength',pattern:'core',muscles:['胸肌','肱三头肌','核心'],effect:'上肢与核心'},
{id:'arms',name:'手臂',type:'strength',pattern:'pull',muscles:['肱二头肌','肱三头肌'],effect:'手臂力量'},
{id:'legpress',name:'坐姿腿推',type:'strength',pattern:'knee',muscles:['股四头肌','臀部','腘绳肌'],effect:'腿部推力'},
{id:'hack',name:'哈克 / 斜腿推',type:'strength',pattern:'knee',muscles:['股四头肌','臀部'],effect:'大腿前侧与臀部'},
{id:'legext',name:'腿屈伸',type:'strength',pattern:'knee',muscles:['股四头肌'],effect:'大腿前侧'},
{id:'legcurl',name:'腿弯举',type:'strength',pattern:'hinge',muscles:['腘绳肌'],effect:'大腿后侧'},
{id:'calf',name:'小腿',type:'strength',pattern:'hinge',muscles:['小腿'],effect:'小腿力量'},
{id:'dumbbell',name:'哑铃',type:'strength',pattern:'push',muscles:['胸肌','背部','肩部','肱二头肌','肱三头肌'],effect:'自由力量'},
{id:'barbell',name:'杠铃',type:'strength',pattern:'hinge',muscles:['背部','臀部','股四头肌','腘绳肌'],effect:'复合力量'},
{id:'bodyweight',name:'徒手',type:'strength',pattern:'core',muscles:['核心','胸肌','股四头肌'],effect:'自重训练'},
{id:'elliptical',name:'椭圆机',type:'cardio',pattern:'cardio',muscles:['心肺','股四头肌','臀部'],effect:'心肺与下肢耐力'},
{id:'rower',name:'划船机',type:'cardio',pattern:'cardio',muscles:['心肺','背部','股四头肌'],effect:'全身心肺'},
{id:'treadmill',name:'跑步机 / 跑步',type:'cardio',pattern:'cardio',muscles:['心肺','股四头肌','臀部','小腿'],effect:'心肺与跑动耐力'},
{id:'walk',name:'步行',type:'cardio',pattern:'cardio',muscles:['心肺','股四头肌','小腿'],effect:'低强度耐力'}
].map(e=>({...e,muscles:e.muscles.filter(m=>MUSCLES.includes(m))}));
const ALIASES={lat:['高位下拉','下拉','拉背'],row:['划船','坐姿划船','胸托划船'],pec:['飞鸟','夹胸','后束','后三角'],chest:['胸推','推胸'],shoulder:['肩推','推肩'],legpress:['腿推','坐姿腿推'],hack:['哈克','斜腿推'],legext:['腿屈伸','腿伸展'],legcurl:['腿弯举','腿弯曲'],calf:['小腿','提踵'],elliptical:['椭圆机'],rower:['划船机'],treadmill:['跑步机','跑步'],walk:['步行','走路'],dumbbell:['哑铃'],barbell:['杠铃'],bodyweight:['徒手','俯卧撑','深蹲'],cable:['龙门架','绳索'],arms:['手臂','弯举','臂屈伸'],dip:['双杠','抬腿']};
const DEFAULT_PREFS={keepClip:true,watermark:{name:true,data:true,time:true,brand:true,pos:'bl'}};
const DEFAULT_PROFILE={name:'我',height:'',weight:'',bodyFat:'',years:'',freq:'',goal:'',customEq:[],memories:[]};
let state={sessions:[],active:null,selectedEq:null,frames:[],clip:null,stream:null,ai:null,profile:{...DEFAULT_PROFILE},prefs:JSON.parse(JSON.stringify(DEFAULT_PREFS))};
let timer=null,toastTimer=null,finishRaf=null,finishStart=0,recognition=null,voiceText='',voicePending=null,eqContext='scan',reportRange='last',selectedSessions=new Set();
const eqAll=()=>BASE_EQ.concat(state.profile.customEq||[]);
function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{const cur=JSON.parse(localStorage.getItem(KEY)||'null');if(cur?.version===VERSION){state={...state,...cur,frames:[],clip:null,stream:null,ai:null,profile:{...DEFAULT_PROFILE,...cur.profile},prefs:{...clone(DEFAULT_PREFS),...cur.prefs,watermark:{...DEFAULT_PREFS.watermark,...cur.prefs?.watermark}}};return}const old=JSON.parse(localStorage.getItem(OLD42)||'null')||JSON.parse(localStorage.getItem(OLD40)||'null');if(old){state.sessions=old.sessions||[];state.active=old.active||null;state.profile={...DEFAULT_PROFILE,...old.profile};state.prefs={...clone(DEFAULT_PREFS),...old.prefs,watermark:{...DEFAULT_PREFS.watermark,...old.prefs?.watermark}};save()}}catch(e){console.warn(e)}}
function save(){try{localStorage.setItem(KEY,JSON.stringify({version:VERSION,sessions:state.sessions,active:state.active,profile:state.profile,prefs:state.prefs}))}catch(e){}}
const uid=p=>p+'-'+Date.now().toString(36).toUpperCase()+Math.random().toString(36).slice(2,6).toUpperCase(),pad=n=>String(n).padStart(2,'0');
function dlabel(t){const d=new Date(t);return `${d.getFullYear()}.${pad(d.getMonth()+1)}.${pad(d.getDate())}`}function tlabel(t){const d=new Date(t);return `${pad(d.getHours())}:${pad(d.getMinutes())}`}function mins(s){return Math.max(0,Math.round(((s.end||Date.now())-s.start)/60000))}function ev(s){return s&&Array.isArray(s.events)?s.events:[]}function recent(days){const cut=Date.now()-days*864e5;return state.sessions.filter(s=>s.start>=cut).concat(state.active&&state.active.start>=cut?[state.active]:[])}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function setText(s,v){const e=$(s);if(e)e.textContent=v}function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1600)}function openSheet(id){$('#'+id)?.classList.add('show')}function closeSheet(id){$('#'+id)?.classList.remove('show');if(id==='scanSheet')stopCamera()}
function allEvents(){return (state.active?[state.active]:[]).concat(state.sessions).flatMap(ev)}function usage(id){let n=0,last=0;allEvents().forEach(e=>{if(e.equipmentId===id){n++;last=Math.max(last,e.time)}});return{n,last}}function lastEvent(id){return allEvents().find(e=>e.equipmentId===id)||null}
function eventEq(e){return eqAll().find(x=>x.id===e.equipmentId)||{name:e.name,muscles:e.muscles||[],effect:e.effect||'',type:e.kind,pattern:e.pattern}}
function muscleCounts(ss){const c={};MUSCLES.forEach(m=>c[m]=0);ss.forEach(s=>ev(s).forEach(e=>{const ms=e.muscles?.length?e.muscles:eventEq(e).muscles||[];ms.forEach(m=>{if(c[m]!=null)c[m]++})}));return c}
function concreteSignal(){if(!state.sessions.length)return null;const all=state.sessions.flatMap(ev),groups={};all.forEach(e=>(groups[e.equipmentId]||(groups[e.equipmentId]=[])).push(e));for(const id in groups){const g=groups[id].filter(e=>e.kind==='strength').sort((a,b)=>b.time-a.time);if(g.length>=2&&Number(g[0].weight)>Number(g[1].weight)&&Number(g[0].reps)>=Number(g[1].reps)-2)return `<strong>${esc(g[0].name)} ${g[1].weight} → ${g[0].weight} kg</strong><small>最近两次负重</small>`}const c=muscleCounts(recent(30)),major=['胸肌','背部','肩部','股四头肌','腘绳肌','臀部','核心'];const min=major.slice().sort((a,b)=>c[a]-c[b])[0];if(all.length>=4&&c[min]===0)return `<strong>${min} · 0次</strong><small>近30天</small>`;return null}
function liveSignal(){if(!state.active)return null;const a=ev(state.active),last=a.length?a[a.length-1].time:state.active.start,idle=(Date.now()-last)/60000;if(idle>10)return `<strong>已停 ${Math.floor(idle)} 分钟</strong><small>本次训练</small>`;return null}
function eventMeta(e){return e.kind==='strength'?`${e.weight}kg · ${e.reps}次 · ${e.sets}组`:`${e.duration}分钟 · 强度${e.intensity}`}
function eventHtml(e){return `<button class="event" data-event="${e.id}"><span class="thumb" ${e.frameRefs?.[0]?`data-photo="${e.frameRefs[0]}"`:''}>${e.frameRefs?.[0]?'':'•'}</span><span><strong>${esc(e.name)}</strong><small>${esc(eventMeta(e))}</small></span><span class="time">${tlabel(e.time)}</span></button>`}
function render(){setText('#todayDate',new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',weekday:'short'}).format(new Date()));const r7=recent(7);setText('#weekMins',r7.reduce((a,s)=>a+mins(s),0));setText('#weekSessions',r7.filter(s=>s!==state.active).length+(state.active?1:0));setText('#lastSession',state.sessions[0]?`${dlabel(state.sessions[0].start)} · ${mins(state.sessions[0])}分钟`:'—');$('#idleHome').classList.toggle('hidden',!!state.active);$('#activeHome').classList.toggle('hidden',!state.active);$('#dock').classList.toggle('show',!!state.active);const sig=concreteSignal();$('#idleSignalWrap').classList.toggle('hidden',!sig);if(sig)$('#idleSignal').innerHTML=sig;if(state.active){renderLive();startTimer()}else stopTimer();renderHistory();renderInsights();renderSettings();bindDynamic();hydrateThumbs()}
function renderLive(){const a=ev(state.active);setText('#liveItems',a.length);setText('#liveSets',a.reduce((n,e)=>n+(e.kind==='strength'?Number(e.sets)||0:1),0));setText('#eventCount',a.length);$('#eventList').innerHTML=a.length?a.slice().reverse().map(eventHtml).join(''):'<div class="empty">暂无记录</div>';const sig=liveSignal();$('#liveSignalWrap').classList.toggle('hidden',!sig);if(sig)$('#liveSignal').innerHTML=sig;const last=a.length?a[a.length-1].time:state.active.start,idle=(Date.now()-last)/60000;setText('#pace',idle>10?`已停 ${Math.floor(idle)}分`:idle>6?'休息偏久':'正常')}
function startTimer(){stopTimer();const tick=()=>{if(!state.active)return;const sec=Math.floor((Date.now()-state.active.start)/1000);setText('#liveTimer',`${pad(Math.floor(sec/60))}:${pad(sec%60)}`);if(sec%20===0)renderLive()};tick();timer=setInterval(tick,1000)}function stopTimer(){if(timer){clearInterval(timer);timer=null}}
function renderHistory(){setText('#historyCount',state.sessions.length);$('#historyList').innerHTML=state.sessions.length?state.sessions.map(s=>`<button class="history" data-session="${s.id}"><span class="thumb">${mins(s)}′</span><span><strong>${dlabel(s.start)}</strong><small>${ev(s).length}项 · ${mins(s)}分钟</small></span><b>${tlabel(s.start)}</b></button>`).join(''):'<div class="empty">暂无记录</div>'}
function renderInsights(){const r7=recent(7),r30=recent(30);setText('#insightMins',r7.reduce((a,s)=>a+mins(s),0));setText('#insightSessions',r30.filter(s=>s!==state.active).length+(state.active?1:0));const c=muscleCounts(r30),shown=['胸肌','背部','肩部','股四头肌','腘绳肌','臀部','核心','心肺'].filter(m=>c[m]>0||r30.length).slice(0,8),max=Math.max(1,...shown.map(m=>c[m]));$('#patternBars').innerHTML=shown.map(m=>`<div class="bar"><span>${m}</span><div class="track"><i style="width:${Math.round(c[m]/max*100)}%"></i></div><span>${c[m]}</span></div>`).join('')||'<div class="empty">暂无记录</div>';const items=[];const sig=concreteSignal();if(sig)items.push(`<div class="signal">${sig}</div>`);const fav=eqAll().map(e=>({e,u:usage(e.id)})).sort((a,b)=>b.u.n-a.u.n)[0];if(fav?.u.n>1)items.push(`<div class="signal"><strong>${esc(fav.e.name)} · ${fav.u.n}次</strong><small>最常记录</small></div>`);$('#signals').innerHTML=items.join('')||'<div class="empty">暂无明显变化</div>'}
function renderSettings(){setText('#memoryCount',(state.profile.memories||[]).length);const ps=[];if(state.profile.height)ps.push(state.profile.height+'cm');if(state.profile.weight)ps.push(state.profile.weight+'kg');setText('#profileSummary',ps.join(' · ')||'未填写');setSwitch('#keepClipSwitch',!!state.prefs.keepClip);renderWatermarkSettings();updateStorageBrief()}
function setSwitch(sel,on){$(sel)?.setAttribute('aria-checked',String(!!on))}
function renderWatermarkSettings(){const w=state.prefs.watermark;setSwitch('#wmName',w.name);setSwitch('#wmData',w.data);setSwitch('#wmTime',w.time);setSwitch('#wmBrand',w.brand);$$('#wmPosition button').forEach(b=>b.classList.toggle('active',b.dataset.pos===w.pos))}
function bindDynamic(){$$('[data-event]').forEach(b=>b.onclick=()=>openEvent(b.dataset.event));$$('[data-session]').forEach(b=>b.onclick=()=>openSession(b.dataset.session))}
function renderMuscles(eq,prefix=''){const p=prefix?`#${prefix}MusclePanel`:'#musclePanel',tags=prefix?`#${prefix}MuscleTags`:'#muscleTags',eff=prefix?`#${prefix}EffectText`:'#effectText';$(p)?.classList.toggle('hidden',!eq);if(eq){$(tags).innerHTML=(eq.muscles||[]).slice(0,4).map(m=>`<i>${esc(m)}</i>`).join('');setText(eff,eq.effect||'')}}
async function startCamera(){stopCamera();$('#cameraFallback').classList.add('hidden');try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('unsupported');state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:960}},audio:false});$('#cameraVideo').srcObject=state.stream;await $('#cameraVideo').play();setText('#scanState','就绪')}catch(e){console.error(e);$('#cameraFallback').classList.remove('hidden');setText('#scanState','拍一张')}}function stopCamera(){if(state.stream){state.stream.getTracks().forEach(t=>t.stop());state.stream=null}if($('#cameraVideo'))$('#cameraVideo').srcObject=null}
function digest(buf){if(window.crypto?.subtle)return crypto.subtle.digest('SHA-256',buf).then(h=>Array.from(new Uint8Array(h)).map(b=>b.toString(16).padStart(2,'0')).join(''));let a=new Uint8Array(buf),h=2166136261;for(let i=0;i<a.length;i++)h=Math.imul(h^a[i],16777619)>>>0;return Promise.resolve(('00000000'+h.toString(16)).slice(-8).repeat(8))}
function fpFromCanvas(cv){const s=D.createElement('canvas');s.width=9;s.height=8;const c=s.getContext('2d',{willReadFrequently:true});c.drawImage(cv,0,0,9,8);const d=c.getImageData(0,0,9,8).data;let bits='';for(let y=0;y<8;y++)for(let x=0;x<8;x++){const i=(y*9+x)*4,j=i+4,a=d[i]*.299+d[i+1]*.587+d[i+2]*.114,b=d[j]*.299+d[j+1]*.587+d[j+2]*.114;bits+=a>b?'1':'0'}let hex='';for(let i=0;i<64;i+=4)hex+=parseInt(bits.slice(i,i+4),2).toString(16);return hex}
function hamming(a,b){if(!a||!b||a.length!==b.length)return 99;let n=0;for(let i=0;i<a.length;i++){let x=parseInt(a[i],16)^parseInt(b[i],16);n+=(x&1)+((x>>1)&1)+((x>>2)&1)+((x>>3)&1)}return n}
function captureSeal(cv){const ctx=cv.getContext('2d'),w=cv.width,h=cv.height,ts=Date.now(),font=Math.max(13,Math.round(w*.017)),p=Math.max(14,Math.round(w*.019));ctx.save();ctx.font=`600 ${font}px -apple-system,BlinkMacSystemFont,Arial`;ctx.textBaseline='bottom';const text=`AXIS · ${dlabel(ts)} ${new Date(ts).toLocaleTimeString('zh-CN',{hour12:false})}`,tw=ctx.measureText(text).width;ctx.fillStyle='rgba(5,6,8,.62)';ctx.fillRect(p,h-p-font*2,tw+p,font*2);ctx.fillStyle='#f5f4f0';ctx.fillText(text,p*1.5,h-p-font*.52);ctx.restore();return ts}
async function frameFromVideo(){const v=$('#cameraVideo');if(!v.videoWidth)throw new Error('camera');const max=960,scale=Math.min(1,max/v.videoWidth),cv=D.createElement('canvas');cv.width=Math.round(v.videoWidth*scale);cv.height=Math.round(v.videoHeight*scale);cv.getContext('2d',{alpha:false}).drawImage(v,0,0,cv.width,cv.height);const fp=fpFromCanvas(cv),ts=captureSeal(cv),blob=await new Promise(r=>cv.toBlob(r,'image/jpeg',.79)),hash=await digest(await blob.arrayBuffer());return{blob,url:URL.createObjectURL(blob),hash,ts,fp}}
async function frameFromFile(file){const u=URL.createObjectURL(file),img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=u});const max=960,scale=Math.min(1,max/img.naturalWidth),cv=D.createElement('canvas');cv.width=Math.round(img.naturalWidth*scale);cv.height=Math.round(img.naturalHeight*scale);cv.getContext('2d',{alpha:false}).drawImage(img,0,0,cv.width,cv.height);URL.revokeObjectURL(u);const fp=fpFromCanvas(cv),ts=captureSeal(cv),blob=await new Promise(r=>cv.toBlob(r,'image/jpeg',.79)),hash=await digest(await blob.arrayBuffer());return{blob,url:URL.createObjectURL(blob),hash,ts,fp}}
function mediaMime(){if(!window.MediaRecorder)return'';for(const t of ['video/mp4','video/webm;codecs=vp8','video/webm'])if(MediaRecorder.isTypeSupported?.(t))return t;return''}const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function liveScan(){if(!state.stream){$('#photoInput').click();return}const b=$('#liveScanBtn');b.disabled=true;state.frames=[];state.clip=null;let rec=null,chunks=[];try{if(state.prefs.keepClip&&window.MediaRecorder){const mt=mediaMime();rec=new MediaRecorder(state.stream,mt?{mimeType:mt}:undefined);rec.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};rec.start()}for(let i=0;i<4;i++){setText('#scanState',`${(3-i*.7).toFixed(1)}秒`);state.frames.push(await frameFromVideo());if(i<3)await sleep(680)}if(rec){await new Promise(resolve=>{rec.onstop=resolve;setTimeout(()=>rec.stop(),600)});if(chunks.length){const blob=new Blob(chunks,{type:rec.mimeType||chunks[0].type||'video/webm'});state.clip={blob,url:URL.createObjectURL(blob),type:blob.type}}}reviewFrames()}catch(e){console.error(e);toast('扫描失败');b.disabled=false;setText('#scanState','就绪')}}
async function singlePhoto(){if(state.stream){try{state.frames=[await frameFromVideo()];state.clip=null;reviewFrames();return}catch{}}$('#photoInput').click()}
function memoryGuess(){const mem=state.profile.memories||[];if(!mem.length||!state.frames.length)return null;let best=null;for(const m of mem)for(const f of state.frames){const d=hamming(m.fp,f.fp);if(!best||d<best.d)best={id:m.equipmentId,d}}return best&&best.d<=8?best:null}
function learnMemory(id){if(!id)return;const arr=state.profile.memories||(state.profile.memories=[]);state.frames.slice(0,3).forEach(f=>{if(f.fp)arr.push({equipmentId:id,fp:f.fp,t:Date.now()})});const by={};for(let i=arr.length-1;i>=0;i--){const m=arr[i];by[m.equipmentId]=by[m.equipmentId]||[];if(by[m.equipmentId].length<10)by[m.equipmentId].push(m)}state.profile.memories=Object.values(by).flat();save()}
function reviewFrames(){stopCamera();$('#captureStage').classList.add('hidden');$('#reviewStage').classList.remove('hidden');$('#film').innerHTML=state.frames.map(f=>`<img src="${f.url}" alt="扫描画面">`).join('');state.selectedEq=null;renderMuscles(null);setText('#equipmentName','待确认');setText('#aiStatus','识别中');$('#lastValue').classList.add('hidden');const g=memoryGuess();if(g){const e=eqAll().find(x=>x.id===g.id);if(e){selectEq(e.id,false,'scan');setText('#aiStatus','已认出');if(g.d<=5)return}}analyzeFrames()}
function setVal(id,v){const el=$('#'+id);if(el&&v!=null)el.value=v}
function selectEq(id,manual=true,context=eqContext){const e=eqAll().find(x=>x.id===id);if(!e)return;if(context==='voice'){voicePending=voicePending||{};voicePending.equipmentId=id;setText('#voiceEquipmentName',e.name);$('#voiceStrengthFields').classList.toggle('hidden',e.type!=='strength');$('#voiceCardioFields').classList.toggle('hidden',e.type!=='cardio');renderMuscles(e,'voice');const last=lastEvent(id);if(last){if(e.type==='strength'){setVal('vWeight',last.weight??20);setVal('vReps',last.reps??10);setVal('vSets',last.sets??3)}else{setVal('vDuration',last.duration??15);setVal('vIntensity',last.intensity??5)}}return}state.selectedEq=id;setText('#equipmentName',e.name);$('#strengthFields').classList.toggle('hidden',e.type!=='strength');$('#cardioFields').classList.toggle('hidden',e.type!=='cardio');renderMuscles(e);const last=lastEvent(id);if(last){$('#lastValue').classList.remove('hidden');setText('#lastValue','上次 '+eventMeta(last));if(e.type==='strength'){setVal('weight',last.weight??20);setVal('reps',last.reps??10);setVal('sets',last.sets??3)}else{setVal('duration',last.duration??15);setVal('intensity',last.intensity??5)}}else $('#lastValue').classList.add('hidden');if(manual)setText('#aiStatus','已确认')}
async function blobDataUrl(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(blob)})}
async function analyzeFrames(){try{const picks=state.frames.length<=3?state.frames:[state.frames[0],state.frames[2],state.frames[state.frames.length-1]],frames=await Promise.all(picks.map(f=>blobDataUrl(f.blob))),recentIds=allEvents().slice(0,10).map(e=>e.equipmentId);const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({frames,recentEquipment:recentIds})}),j=await r.json();if(!r.ok||!j.result){setText('#aiStatus',j.error==='not_configured'?'手动确认':'识别失败');return}state.ai=j.result;if(j.result.equipmentId&&j.result.confidence>=.58){selectEq(j.result.equipmentId,false,'scan');setText('#aiStatus',j.result.confidence>=.82?'已识别':'请确认');if(Number.isFinite(Number(j.result.weightKg)))setVal('weight',Number(j.result.weightKg));if(j.result.cardio){if(Number.isFinite(Number(j.result.cardio.durationMin)))setVal('duration',Math.round(Number(j.result.cardio.durationMin)));if(Number.isFinite(Number(j.result.cardio.resistance)))setVal('intensity',Math.max(1,Math.min(10,Math.round(Number(j.result.cardio.resistance)))))} }else setText('#aiStatus','请确认')}catch(e){console.error(e);setText('#aiStatus','手动确认')}}
function resetScan(){state.frames.forEach(f=>{try{URL.revokeObjectURL(f.url)}catch{}});if(state.clip?.url)try{URL.revokeObjectURL(state.clip.url)}catch{};state.frames=[];state.clip=null;state.selectedEq=null;state.ai=null;$('#captureStage').classList.remove('hidden');$('#reviewStage').classList.add('hidden');$('#film').innerHTML='';$('#liveScanBtn').disabled=false;setText('#scanState','就绪');setText('#equipmentName','待确认');setText('#aiStatus','手动确认');renderMuscles(null);$('#strengthFields').classList.add('hidden');$('#cardioFields').classList.add('hidden');$('#lastValue').classList.add('hidden');setVal('weight',20);setVal('reps',10);setVal('sets',3);setVal('duration',15);setVal('intensity',5)}
function renderEqList(q=''){const all=eqAll(),low=q.trim().toLowerCase(),filtered=all.filter(e=>!low||e.name.toLowerCase().includes(low)||(e.muscles||[]).some(m=>m.includes(low))),recentEq=all.map(e=>({e,u:usage(e.id)})).filter(x=>x.u.n).sort((a,b)=>b.u.last-a.u.last).slice(0,5);$('#quickEq').innerHTML=recentEq.map(x=>`<button data-eq="${x.e.id}">${esc(x.e.name)}</button>`).join('');$('#eqList').innerHTML=filtered.map(e=>`<button class="eqItem" data-eq="${e.id}"><b>${esc(e.name)}</b><span>${esc((e.muscles||[]).slice(0,2).join(' · '))}</span></button>`).join('');$$('[data-eq]',$('#eqSheet')).forEach(b=>b.onclick=()=>{selectEq(b.dataset.eq,true,eqContext);closeSheet('eqSheet')})}
function derivePattern(type,muscles){if(type==='cardio')return'cardio';if(muscles.includes('胸肌')||muscles.includes('肩部')||muscles.includes('肱三头肌'))return'push';if(muscles.includes('背部')||muscles.includes('肱二头肌'))return'pull';if(muscles.includes('股四头肌'))return'knee';if(muscles.includes('臀部')||muscles.includes('腘绳肌')||muscles.includes('小腿'))return'hinge';return'core'}
function renderCustomMuscles(){const picked=new Set($$('#customMuscles .active').map(b=>b.dataset.muscle));$('#customMuscles').innerHTML=MUSCLES.map(m=>`<button data-muscle="${m}" class="${picked.has(m)?'active':''}">${m}</button>`).join('')}
function nval(id,min,max,def){const n=Number($('#'+id)?.value);return Math.max(min,Math.min(max,Number.isFinite(n)?n:def))}
async function imageFromBlob(blob){const u=URL.createObjectURL(blob),img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=u});return{img,url:u}}
function overlayLines(e,eq,ts){const w=state.prefs.watermark,lines=[];if(w.brand)lines.push({t:'AXIS',strong:true});if(w.name)lines.push({t:eq.name,strong:true});if(w.data)lines.push({t:eventMeta(e)});if(w.time)lines.push({t:`${dlabel(ts)} ${tlabel(ts)}`});return lines}
async function finalizeFrame(frame,e,eq){const {img,url}=await imageFromBlob(frame.blob),cv=D.createElement('canvas');cv.width=img.naturalWidth;cv.height=img.naturalHeight;const ctx=cv.getContext('2d',{alpha:false});ctx.drawImage(img,0,0,cv.width,cv.height);URL.revokeObjectURL(url);const lines=overlayLines(e,eq,frame.ts||e.time);if(lines.length){const pos=state.prefs.watermark.pos||'bl',font=Math.max(16,Math.round(cv.width*.022)),small=Math.round(font*.82),padv=Math.max(16,Math.round(cv.width*.02)),lineH=Math.round(font*1.36);ctx.save();ctx.textBaseline='top';let maxW=0;lines.forEach(x=>{ctx.font=`${x.strong?'650':'500'} ${x.strong?font:small}px -apple-system,BlinkMacSystemFont,Arial`;maxW=Math.max(maxW,ctx.measureText(x.t).width)});const boxW=maxW+padv*1.6,boxH=lineH*lines.length+padv*.9,x=pos.endsWith('r')?cv.width-boxW-padv:padv,y=pos.startsWith('t')?padv:cv.height-boxH-padv;ctx.fillStyle='rgba(6,7,9,.78)';ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x,y,boxW,boxH,Math.round(padv*.45));else ctx.rect(x,y,boxW,boxH);ctx.fill();let ty=y+padv*.45;lines.forEach(item=>{ctx.font=`${item.strong?'650':'500'} ${item.strong?font:small}px -apple-system,BlinkMacSystemFont,Arial`;ctx.fillStyle=item.strong?'#f5f4f0':'#c7cbd2';ctx.fillText(item.t,x+padv*.8,ty);ty+=lineH});ctx.restore()}const blob=await new Promise(r=>cv.toBlob(r,'image/jpeg',.86));return blob}
async function openDb(){return new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains('media'))q.result.createObjectStore('media')};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function putMedia(k,b){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction('media','readwrite');tx.objectStore('media').put(b,k);tx.oncomplete=()=>{db.close();res()};tx.onerror=()=>{db.close();rej(tx.error)}})}
async function getMedia(k){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction('media','readonly'),q=tx.objectStore('media').get(k);q.onsuccess=()=>{db.close();res(q.result||null)};q.onerror=()=>{db.close();rej(q.error)}})}
async function deleteMedia(k){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction('media','readwrite');tx.objectStore('media').delete(k);tx.oncomplete=()=>{db.close();res()};tx.onerror=()=>{db.close();rej(tx.error)}})}
async function mediaUrl(k){try{const b=await getMedia(k);return b?URL.createObjectURL(b):null}catch{return null}}
async function saveScan(){if(!state.active){toast('请先开始训练');return}const eq=eqAll().find(e=>e.id===state.selectedEq);if(!eq){eqContext='scan';renderEqList();openSheet('eqSheet');return}const e={id:uid('E'),equipmentId:eq.id,name:eq.name,pattern:eq.pattern,kind:eq.type,muscles:eq.muscles||[],effect:eq.effect||'',time:Date.now(),frameRefs:[],photoBytes:0,videoBytes:0,fingerprints:state.frames.map(f=>f.fp).filter(Boolean),ai:state.ai?{confidence:state.ai.confidence,model:state.ai.model}:null};if(eq.type==='strength'){e.weight=nval('weight',0,1000,0);e.reps=nval('reps',1,100,10);e.sets=nval('sets',1,30,3)}else{e.duration=nval('duration',1,600,15);e.intensity=nval('intensity',1,10,5)}try{for(let i=0;i<state.frames.length;i++){const blob=await finalizeFrame(state.frames[i],e,eq),ref=`F-${e.id}-${i}`;await putMedia(ref,blob);e.frameRefs.push(ref);e.photoBytes+=blob.size}if(state.prefs.keepClip&&state.clip?.blob){e.clipRef=`V-${e.id}`;e.clipType=state.clip.type;e.videoBytes=state.clip.blob.size;await putMedia(e.clipRef,state.clip.blob)}}catch(err){console.error(err);toast('保存失败');return}learnMemory(eq.id);state.active.events.push(e);save();closeSheet('scanSheet');resetScan();render();toast('已记下')}
async function hydrateThumbs(){for(const el of $$('[data-photo]')){if(el.dataset.loaded)continue;el.dataset.loaded='1';const u=await mediaUrl(el.dataset.photo);if(u)el.innerHTML=`<img src="${u}" alt="记录">`}}
async function shareBlob(blob,name,type){try{const f=new File([blob],name,{type});if(navigator.canShare?.({files:[f]})&&navigator.share)return await navigator.share({files:[f]});const a=D.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;D.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),800)}catch(e){if(e?.name!=='AbortError')console.warn(e)}}
async function openEvent(id){const e=allEvents().find(x=>x.id===id);if(!e)return;const eq=eventEq(e);setText('#detailTitle',e.name);let media='';if(e.frameRefs?.[0]){const u=await mediaUrl(e.frameRefs[0]);if(u)media+=`<img class="detailPhoto" src="${u}" alt="记录照片" data-detail-photo="${e.frameRefs[0]}">`}if(e.clipRef){const v=await mediaUrl(e.clipRef);if(v)media+=`<video class="detailVideo" src="${v}" controls playsinline muted></video>`}const rows=e.kind==='strength'?[['重量',e.weight+' kg'],['次数',e.reps+' 次'],['组数',e.sets+' 组']]:[['时间',e.duration+' 分钟'],['强度',e.intensity+' / 10']];rows.unshift(['主要锻炼',(e.muscles||eq.muscles||[]).join(' · ')||'—']);rows.push(['记录时间',dlabel(e.time)+' '+tlabel(e.time)]);$('#detail').innerHTML=media+`<div class="detailList">${rows.map(r=>`<div class="detailRow"><span>${r[0]}</span><span>${esc(r[1])}</span></div>`).join('')}</div>${e.frameRefs?.[0]?'<div class="detailActions"><button id="saveDetailPhoto">保存图片</button><button id="makeSessionReport">训练报告</button></div>':''}`;openSheet('detailSheet');if($('#saveDetailPhoto'))$('#saveDetailPhoto').onclick=async()=>{const b=await getMedia(e.frameRefs[0]);if(b)shareBlob(b,`AXIS-${e.name}-${dlabel(e.time)}.jpg`,'image/jpeg')};if($('#makeSessionReport'))$('#makeSessionReport').onclick=()=>{const s=(state.active?[state.active]:[]).concat(state.sessions).find(s=>ev(s).some(x=>x.id===e.id));if(s){reportRange='session:'+s.id;renderReport();openSheet('reportSheet')}}}
function openSession(id){const s=state.sessions.find(x=>x.id===id);if(!s)return;setText('#detailTitle',dlabel(s.start));$('#detail').innerHTML=`<div class="detailList"><div class="detailRow"><span>训练时间</span><span>${mins(s)} 分钟</span></div><div class="detailRow"><span>项目</span><span>${ev(s).length}</span></div><div class="detailRow"><span>组数</span><span>${ev(s).reduce((n,e)=>n+(e.kind==='strength'?Number(e.sets)||0:1),0)}</span></div></div><div class="events">${ev(s).slice().reverse().map(eventHtml).join('')}</div><div class="detailActions"><button id="sessionReportBtn">训练报告</button><button id="sessionDeleteBtn">删除本次</button></div>`;openSheet('detailSheet');bindDynamic();hydrateThumbs();$('#sessionReportBtn').onclick=()=>{reportRange='session:'+s.id;renderReport();openSheet('reportSheet')};$('#sessionDeleteBtn').onclick=async()=>{if(!confirm('删除这次训练？'))return;await deleteSessions([s.id]);closeSheet('detailSheet');render();toast('已删除')}}
function finishStartHold(){if(!state.active)return;finishStart=performance.now();const dur=1050,step=now=>{const p=Math.min(1,(now-finishStart)/dur);$('#finishHold').style.setProperty('--hold',Math.round(p*100)+'%');if(p<1)finishRaf=requestAnimationFrame(step);else completeFinish()};finishRaf=requestAnimationFrame(step)}function finishCancelHold(){if(finishRaf)cancelAnimationFrame(finishRaf);finishRaf=null;$('#finishHold').style.setProperty('--hold','0%')}
function completeFinish(){finishCancelHold();if(!state.active)return;state.active.end=Date.now();const s=state.active;state.sessions.unshift(s);state.active=null;save();setText('#finishDuration',mins(s)+'分钟');setText('#finishItems',ev(s).length);setText('#finishSets',ev(s).reduce((n,e)=>n+(e.kind==='strength'?Number(e.sets)||0:1),0));openSheet('finishSheet');render()}
function cnNum(s){if(!s)return NaN;if(/^\d+(\.\d+)?$/.test(s))return Number(s);const d={'零':0,'一':1,'二':2,'两':2,'三':3,'四':4,'五':5,'六':6,'七':7,'八':8,'九':9};if(s==='十')return 10;if(s.includes('十')){const[a,b]=s.split('十');return(a?d[a]||0:1)*10+(b?d[b]||0:0)}return d[s]??NaN}function pickNum(text,rx){const m=text.match(rx);return m?cnNum(m[1]):NaN}
function findEqInText(text){for(const e of eqAll()){const names=[e.name,...(ALIASES[e.id]||[])].map(x=>x.replace(/\s*\/.*$/,''));if(names.some(n=>n&&text.includes(n)))return e}return null}
function parseVoiceLocal(text){const eq=findEqInText(text),w=pickNum(text,/([零一二两三四五六七八九十\d.]+)\s*(?:公斤|千克|kg)/i),r=pickNum(text,/([零一二两三四五六七八九十\d]+)\s*次/),s=pickNum(text,/([零一二两三四五六七八九十\d]+)\s*组/),m=pickNum(text,/([零一二两三四五六七八九十\d]+)\s*分钟/),it=pickNum(text,/(?:强度|阻力)\s*([零一二两三四五六七八九十\d]+)/);return{equipmentId:eq?.id||null,weight:Number.isFinite(w)?w:null,reps:Number.isFinite(r)?r:null,sets:Number.isFinite(s)?s:null,duration:Number.isFinite(m)?m:null,intensity:Number.isFinite(it)?it:null}}
async function parseVoiceAI(text){try{const r=await fetch('/api/parse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,recentEquipment:allEvents().slice(0,8).map(e=>e.equipmentId)})}),j=await r.json();return r.ok?j.result:null}catch{return null}}
async function prepareVoice(text){$('#voiceOverlay').classList.remove('show');$('#talkHold').classList.remove('listening');if(!text.trim())return;setText('#voiceTranscript',text);let p=parseVoiceLocal(text);if(!p.equipmentId){const ai=await parseVoiceAI(text);if(ai)p={...p,...Object.fromEntries(Object.entries(ai).filter(([,v])=>v!=null))}}voicePending={text,...p};setText('#voiceEquipmentName','待确认');renderMuscles(null,'voice');$('#voiceStrengthFields').classList.add('hidden');$('#voiceCardioFields').classList.add('hidden');if(p.equipmentId)selectEq(p.equipmentId,false,'voice');const eq=eqAll().find(e=>e.id===p.equipmentId);if(eq?.type==='strength'){if(p.weight!=null)setVal('vWeight',p.weight);if(p.reps!=null)setVal('vReps',p.reps);if(p.sets!=null)setVal('vSets',p.sets)}else if(eq?.type==='cardio'){if(p.duration!=null)setVal('vDuration',p.duration);if(p.intensity!=null)setVal('vIntensity',p.intensity)}openSheet('voiceSheet')}
function setupVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return;$('#talkHold').classList.remove('hidden');recognition=new SR();recognition.lang='zh-CN';recognition.continuous=false;recognition.interimResults=true;recognition.onstart=()=>{voiceText='';$('#voiceOverlay').classList.add('show');$('#talkHold').classList.add('listening');setText('#voiceLiveText','正在听')};recognition.onresult=e=>{let final='',interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)final+=t;else interim+=t}if(final)voiceText+=final;setText('#voiceLiveText',(voiceText||interim||'正在听').slice(0,40))};recognition.onerror=()=>{$('#voiceOverlay').classList.remove('show');$('#talkHold').classList.remove('listening');toast('没有听清')};recognition.onend=()=>{const t=voiceText.trim();$('#voiceOverlay').classList.remove('show');$('#talkHold').classList.remove('listening');if(t)prepareVoice(t)}}
function startVoice(){if(!state.active||!recognition)return;try{recognition.start()}catch{}}function stopVoice(){try{recognition?.stop()}catch{}}
async function saveVoice(){if(!state.active)return;const eq=eqAll().find(e=>e.id===voicePending?.equipmentId);if(!eq){eqContext='voice';renderEqList();openSheet('eqSheet');return}const e={id:uid('E'),equipmentId:eq.id,name:eq.name,pattern:eq.pattern,kind:eq.type,muscles:eq.muscles||[],effect:eq.effect||'',time:Date.now(),frameRefs:[],source:'voice',voiceText:voicePending.text,photoBytes:0,videoBytes:0};if(eq.type==='strength'){e.weight=nval('vWeight',0,1000,0);e.reps=nval('vReps',1,100,10);e.sets=nval('vSets',1,30,3)}else{e.duration=nval('vDuration',1,600,15);e.intensity=nval('vIntensity',1,10,5)}state.active.events.push(e);save();closeSheet('voiceSheet');voicePending=null;render();toast('已记下')}
async function aiHealth(){try{const r=await fetch('/api/analyze'),j=await r.json();setText('#aiHealth',j.available?'已连接':'未连接')}catch{setText('#aiHealth','未连接')}}
function fillProfile(){setVal('profileHeight',state.profile.height);setVal('profileWeight',state.profile.weight);setVal('profileBodyFat',state.profile.bodyFat);setVal('profileYears',state.profile.years);$$('#profileFreq button').forEach(b=>b.classList.toggle('active',String(state.profile.freq)===b.dataset.value));$$('#profileGoal button').forEach(b=>b.classList.toggle('active',state.profile.goal===b.dataset.value))}
function saveProfile(){state.profile.height=$('#profileHeight').value.trim();state.profile.weight=$('#profileWeight').value.trim();state.profile.bodyFat=$('#profileBodyFat').value.trim();state.profile.years=$('#profileYears').value.trim();state.profile.freq=$('#profileFreq .active')?.dataset.value||'';state.profile.goal=$('#profileGoal .active')?.dataset.value||'';save();closeSheet('profileSheet');render();toast('已保存')}
function fmtBytes(n){if(n<1024)return n+' B';if(n<1024*1024)return(n/1024).toFixed(n<10240?1:0)+' KB';return(n/1024/1024).toFixed(n<10*1024*1024?1:0)+' MB'}
async function storageInfo(){let photos=0,videos=0;try{const db=await openDb();const data=await new Promise((res,rej)=>{const tx=db.transaction('media','readonly'),store=tx.objectStore('media'),kr=store.getAllKeys(),vr=store.getAll();let keys,vals;kr.onsuccess=()=>{keys=kr.result;if(vals)done()};vr.onsuccess=()=>{vals=vr.result;if(keys)done()};kr.onerror=vr.onerror=()=>rej(tx.error);function done(){db.close();res({keys,vals})}});data.keys.forEach((k,i)=>{const size=data.vals[i]?.size||0;if(String(k).startsWith('V-'))videos+=size;else photos+=size})}catch{}const raw=localStorage.getItem(KEY)||'',recordBytes=new Blob([raw]).size;return{photos,videos,recordBytes,total:photos+videos+recordBytes}}
async function updateStorageBrief(){const i=await storageInfo();setText('#storageBrief',fmtBytes(i.total))}
async function renderStorage(){const i=await storageInfo();setText('#storageTotal',fmtBytes(i.total));setText('#photoSize',fmtBytes(i.photos));setText('#videoSize',fmtBytes(i.videos));setText('#dataSize',fmtBytes(i.recordBytes));const media=i.photos+i.videos||1;$('#photoBar').style.width=`${Math.round(i.photos/media*100)}%`;$('#videoBar').style.width=`${Math.round(i.videos/media*100)}%`;selectedSessions.clear();const rows=[];for(const s of state.sessions){let bytes=0;for(const e of ev(s)){bytes+=(e.photoBytes||0)+(e.videoBytes||0);if(!e.photoBytes&&!e.videoBytes){for(const r of e.frameRefs||[])bytes+=(await getMedia(r))?.size||0;if(e.clipRef)bytes+=(await getMedia(e.clipRef))?.size||0}}rows.push(`<button class="deleteSession" data-delete-session="${s.id}"><i>✓</i><span><b>${dlabel(s.start)}</b><small>${mins(s)}分钟 · ${ev(s).length}项</small></span><span>${fmtBytes(bytes)}</span></button>`)}$('#sessionDeleteList').innerHTML=rows.join('')||'<div class="empty">暂无记录</div>';$$('[data-delete-session]').forEach(b=>b.onclick=()=>{const id=b.dataset.deleteSession;if(selectedSessions.has(id)){selectedSessions.delete(id);b.classList.remove('selected')}else{selectedSessions.add(id);b.classList.add('selected')}})}
async function deleteSessions(ids){const set=new Set(ids);for(const s of state.sessions.filter(x=>set.has(x.id)))for(const e of ev(s)){for(const r of e.frameRefs||[])await deleteMedia(r);if(e.clipRef)await deleteMedia(e.clipRef)}state.sessions=state.sessions.filter(s=>!set.has(s.id));save()}
async function clearVideos(){for(const s of state.sessions)for(const e of ev(s))if(e.clipRef){await deleteMedia(e.clipRef);delete e.clipRef;delete e.clipType;e.videoBytes=0}if(state.active)for(const e of ev(state.active))if(e.clipRef){await deleteMedia(e.clipRef);delete e.clipRef;delete e.clipType;e.videoBytes=0}save();await renderStorage();render();toast('视频已清理')}
async function clearAll(){if(!confirm('清空全部记录？'))return;localStorage.removeItem(KEY);localStorage.removeItem(OLD42);localStorage.removeItem(OLD40);await new Promise(res=>{const q=indexedDB.deleteDatabase(DB);q.onsuccess=q.onerror=q.onblocked=()=>res()});state={sessions:[],active:null,selectedEq:null,frames:[],clip:null,stream:null,ai:null,profile:{...DEFAULT_PROFILE},prefs:clone(DEFAULT_PREFS)};closeSheet('storageSheet');render();toast('已清空')}
function reportSessions(){if(reportRange.startsWith('session:')){const s=state.sessions.find(x=>x.id===reportRange.split(':')[1]);return s?[s]:[]}if(reportRange==='last')return state.sessions.slice(0,1);const cut=Date.now()-Number(reportRange)*864e5;return state.sessions.filter(s=>s.start>=cut)}
function reportStats(){const ss=reportSessions(),events=ss.flatMap(ev),minutes=ss.reduce((n,s)=>n+mins(s),0),sets=events.reduce((n,e)=>n+(e.kind==='strength'?Number(e.sets)||0:1),0),freq={};events.forEach(e=>freq[e.name]=(freq[e.name]||0)+1);const top=Object.entries(freq).sort((a,b)=>b[1]-a[1]).slice(0,4),mc=muscleCounts(ss),topMuscles=Object.entries(mc).filter(([,v])=>v).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([m])=>m);return{ss,events,minutes,sets,top,topMuscles}}
function renderReport(){const r=reportStats();$$('#reportRange button').forEach(b=>b.classList.toggle('active',b.dataset.range===reportRange));const dates=r.ss.length?`${dlabel(r.ss[r.ss.length-1].start)} — ${dlabel(r.ss[0].start)}`:dlabel(Date.now());$('#reportPreview').innerHTML=`<div class="reportBrand">AXIS</div><div class="reportDate">${dates}</div><div class="reportBig">${r.minutes}<span> 分钟</span></div><div class="reportStats"><div><b>${r.ss.length}</b><span>训练</span></div><div><b>${r.events.length}</b><span>项目</span></div><div><b>${r.sets}</b><span>组</span></div></div><div class="reportList">${r.top.map(([n,c])=>`<div><b>${esc(n)}</b><span>${c}次</span></div>`).join('')}${r.topMuscles.length?`<div><b>主要锻炼</b><span>${r.topMuscles.join(' · ')}</span></div>`:''}</div>`}
async function makeReportImage(){const r=reportStats();if(!r.ss.length){toast('暂无记录');return null}const cv=D.createElement('canvas');cv.width=1080;cv.height=1350;const c=cv.getContext('2d');c.fillStyle='#f1f0ec';c.fillRect(0,0,cv.width,cv.height);c.fillStyle='#0d0f12';c.font='700 38px -apple-system,BlinkMacSystemFont,Arial';c.fillText('AXIS',80,92);c.font='500 28px -apple-system,BlinkMacSystemFont,Arial';c.fillStyle='#777b82';const dates=`${dlabel(r.ss[r.ss.length-1].start)} — ${dlabel(r.ss[0].start)}`;c.fillText(dates,80,190);c.fillStyle='#0d0f12';c.font='650 128px -apple-system,BlinkMacSystemFont,Arial';c.fillText(String(r.minutes),80,355);c.font='500 32px -apple-system,BlinkMacSystemFont,Arial';c.fillStyle='#777b82';c.fillText('分钟',350,350);c.strokeStyle='#d5d4d0';c.lineWidth=2;c.beginPath();c.moveTo(80,430);c.lineTo(1000,430);c.stroke();const stats=[[r.ss.length,'训练'],[r.events.length,'项目'],[r.sets,'组']];stats.forEach((x,i)=>{const x0=80+i*305;c.fillStyle='#0d0f12';c.font='650 50px -apple-system,BlinkMacSystemFont,Arial';c.fillText(String(x[0]),x0,520);c.fillStyle='#777b82';c.font='500 25px -apple-system,BlinkMacSystemFont,Arial';c.fillText(x[1],x0,560)});let y=690;c.fillStyle='#0d0f12';c.font='650 30px -apple-system,BlinkMacSystemFont,Arial';c.fillText('训练记录',80,y);y+=60;c.font='600 29px -apple-system,BlinkMacSystemFont,Arial';r.top.slice(0,5).forEach(([n,count])=>{c.fillStyle='#0d0f12';c.fillText(n.slice(0,18),80,y);c.fillStyle='#777b82';c.font='500 26px -apple-system,BlinkMacSystemFont,Arial';c.fillText(count+'次',880,y);c.strokeStyle='#deddd9';c.beginPath();c.moveTo(80,y+28);c.lineTo(1000,y+28);c.stroke();c.font='600 29px -apple-system,BlinkMacSystemFont,Arial';y+=82});if(r.topMuscles.length){c.fillStyle='#777b82';c.font='500 26px -apple-system,BlinkMacSystemFont,Arial';c.fillText('主要锻炼',80,1180);c.fillStyle='#0d0f12';c.font='600 31px -apple-system,BlinkMacSystemFont,Arial';c.fillText(r.topMuscles.join(' · '),80,1230)}c.fillStyle='#737cff';c.fillRect(80,1285,120,8);return new Promise(res=>cv.toBlob(res,'image/jpeg',.92))}
async function backupData(){const blob=new Blob([JSON.stringify({version:VERSION,exportedAt:new Date().toISOString(),sessions:state.sessions,profile:state.profile,prefs:state.prefs},null,2)],{type:'application/json'});await shareBlob(blob,`AXIS-备份-${dlabel(Date.now())}.json`,'application/json')}
function bind(){
$('#startBtn').onclick=()=>{state.active={id:uid('S'),start:Date.now(),events:[]};save();render();toast('已开始')};$('#settingsBtn').onclick=()=>{openSheet('settingsSheet');aiHealth();updateStorageBrief()};$('#scanBtn').onclick=()=>{resetScan();openSheet('scanSheet');startCamera()};
$$('[data-close]').forEach(b=>b.onclick=()=>closeSheet(b.dataset.close));$$('.sheetWrap').forEach(w=>w.onclick=e=>{if(e.target===w&&w.id!=='finishSheet')closeSheet(w.id)});
$('#liveScanBtn').onclick=liveScan;$('#photoBtn').onclick=singlePhoto;$('#photoInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;state.frames=[await frameFromFile(f)];state.clip=null;reviewFrames();e.target.value=''};
$('#equipmentRow').onclick=()=>{eqContext='scan';renderEqList();openSheet('eqSheet')};$('#voiceEquipmentRow').onclick=()=>{eqContext='voice';renderEqList();openSheet('eqSheet')};$('#eqSearch').oninput=e=>renderEqList(e.target.value);$('#addCustomEq').onclick=()=>{closeSheet('eqSheet');renderCustomMuscles();openSheet('customEqSheet')};
$$('#customType button').forEach(b=>b.onclick=()=>{$$('#customType button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});$('#customMuscles').onclick=e=>{const b=e.target.closest('[data-muscle]');if(b)b.classList.toggle('active')};$('#saveCustomEq').onclick=()=>{const name=$('#customName').value.trim(),type=$('#customType .active')?.dataset.type||'strength',muscles=$$('#customMuscles .active').map(b=>b.dataset.muscle);if(!name){toast('请输入名称');return}if(!muscles.length){toast('请选择锻炼部位');return}const id='custom-'+uid('').replace(/^-/, '').toLowerCase(),eq={id,name,type,pattern:derivePattern(type,muscles),muscles,effect:muscles.slice(0,2).join(' · '),custom:true};state.profile.customEq.push(eq);save();selectEq(id,true,eqContext);$('#customName').value='';$$('#customMuscles .active').forEach(b=>b.classList.remove('active'));closeSheet('customEqSheet');toast('已保存')};
D.addEventListener('click',e=>{const b=e.target.closest('[data-step],[data-vstep]');if(!b)return;const id=b.dataset.step||b.dataset.vstep,el=$('#'+id);if(!el)return;const base=id.replace(/^v/,'').toLowerCase(),min=base==='weight'?0:1,max=base==='weight'?1000:base==='duration'?600:base==='reps'?100:base==='sets'?30:10;let n=Number(el.value)||0;n=Math.max(min,Math.min(max,n+Number(b.dataset.delta||0)));el.value=base==='weight'?Math.round(n*10)/10:Math.round(n)});
$('#saveScan').onclick=saveScan;$('#saveVoice').onclick=saveVoice;$('#finishHold').addEventListener('pointerdown',e=>{e.preventDefault();finishStartHold()});['pointerup','pointercancel','pointerleave'].forEach(t=>$('#finishHold').addEventListener(t,finishCancelHold));$('#finishDone').onclick=()=>{closeSheet('finishSheet');render()};
$$('.nav button').forEach(b=>b.onclick=()=>{$$('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.view).classList.add('active');render()});
$('#talkHold').addEventListener('pointerdown',e=>{e.preventDefault();startVoice()});['pointerup','pointercancel','pointerleave'].forEach(t=>$('#talkHold').addEventListener(t,stopVoice));
$('#keepClipSwitch').onclick=()=>{state.prefs.keepClip=!state.prefs.keepClip;save();renderSettings()};$('#profileBtn').onclick=()=>{fillProfile();openSheet('profileSheet')};$('#customEqBtn').onclick=()=>{eqContext='scan';renderEqList();openSheet('eqSheet')};$('#watermarkBtn').onclick=()=>{renderWatermarkSettings();openSheet('watermarkSheet')};$('#storageBtn').onclick=async()=>{openSheet('storageSheet');await renderStorage()};$('#reportBtn').onclick=()=>{reportRange='last';renderReport();openSheet('reportSheet')};
$$('#profileFreq button').forEach(b=>b.onclick=()=>{$$('#profileFreq button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});$$('#profileGoal button').forEach(b=>b.onclick=()=>{$$('#profileGoal button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});$('#saveProfile').onclick=saveProfile;
[['wmName','name'],['wmData','data'],['wmTime','time'],['wmBrand','brand']].forEach(([id,k])=>$('#'+id).onclick=()=>{state.prefs.watermark[k]=!state.prefs.watermark[k];save();renderWatermarkSettings()});$$('#wmPosition button').forEach(b=>b.onclick=()=>{state.prefs.watermark.pos=b.dataset.pos;save();renderWatermarkSettings()});
$('#clearVideos').onclick=clearVideos;$('#backupBtn').onclick=backupData;$('#selectAllSessions').onclick=()=>{$$('[data-delete-session]').forEach(b=>{selectedSessions.add(b.dataset.deleteSession);b.classList.add('selected')})};$('#deleteSelected').onclick=async()=>{if(!selectedSessions.size){toast('请选择训练');return}if(!confirm(`删除 ${selectedSessions.size} 次训练？`))return;await deleteSessions([...selectedSessions]);selectedSessions.clear();await renderStorage();render();toast('已删除')};$('#clearAll').onclick=clearAll;
$$('#reportRange button').forEach(b=>b.onclick=()=>{reportRange=b.dataset.range;renderReport()});$('#shareReport').onclick=async()=>{const blob=await makeReportImage();if(blob)shareBlob(blob,`AXIS-训练报告-${dlabel(Date.now())}.jpg`,'image/jpeg')};
D.addEventListener('visibilitychange',()=>{if(!D.hidden)render()});window.addEventListener('pageshow',render)
}
load();bind();renderCustomMuscles();setupVoice();render();aiHealth();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
})();
