(()=>{'use strict';
const D=document,$=(s,r=D)=>r.querySelector(s),$$=(s,r=D)=>Array.from(r.querySelectorAll(s));
const CORE='axis_v60_state',META='axis_v8_meta';
const CURATED=['chest','lat','legpress','row','dumbbell','treadmill'];
let draftSets=[],selectedSet=0,saveDraft=null,saving=false;
function readCore(){try{return JSON.parse(localStorage.getItem(CORE)||'null')||{version:60,sessions:[],active:null,profile:{customEq:[]}}}catch{return{version:60,sessions:[],active:null,profile:{customEq:[]}}}}
function readMeta(){try{return JSON.parse(localStorage.getItem(META)||'null')||{events:{},sessions:{},prefs:{}}}catch{return{events:{},sessions:{},prefs:{}}}}
function writeMeta(m){try{localStorage.setItem(META,JSON.stringify(m))}catch{}}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmt(n){n=Number(n)||0;return n%1?n.toFixed(1):String(n)}
function pad(n){return String(n).padStart(2,'0')}
function mm(ms){return Math.max(0,Math.round(ms/60000))}
function coreEvents(c=readCore()){return (c.active?[c.active]:[]).concat(c.sessions||[]).flatMap(s=>Array.isArray(s.events)?s.events:[])}
function lastEvent(id){return coreEvents().filter(e=>e.equipmentId===id).sort((a,b)=>(b.time||0)-(a.time||0))[0]||null}
function eventSets(e){const m=readMeta();const side=m.events?.[e?.id]?.sets;if(Array.isArray(side)&&side.length)return side;const n=Math.max(1,Number(e?.sets)||1),w=Number(e?.weight)||0,r=Number(e?.reps)||0;return Array.from({length:n},()=>({weight:w,reps:r,doneAt:null}))}
function setSummary(e){if(!e||e.kind!=='strength')return e?.duration?`${e.duration}分钟 · 强度${e.intensity||0}`:'';const sets=eventSets(e),weights=[...new Set(sets.map(s=>fmt(s.weight)))],reps=sets.map(s=>Number(s.reps)||0);return `${weights.length===1?weights[0]+'kg':'分组重量'} · ${reps.join(' / ')}`}
function ensureSessionForCommit(){const c=readCore();if(c.active)return false;const b=$('#startBtn');if(!b)return false;b.click();$('#toast')?.classList.remove('show');return true}
function activeEventIds(){const c=readCore();return new Set((c.active?.events||[]).map(e=>e.id))}
function findNewEvent(before){const c=readCore(),a=c.active?.events||[];return a.find(e=>!before.has(e.id))||null}
function waitForNewEvent(before,attempt=0){const e=findNewEvent(before);if(e){attachDraft(e);return}if(attempt<60)setTimeout(()=>waitForNewEvent(before,attempt+1),80);else saving=false}
function attachDraft(e){if(!saveDraft||e.kind!=='strength'){saving=false;renderTimeIntelligence();return}const m=readMeta();m.events=m.events||{};m.events[e.id]={...(m.events[e.id]||{}),sets:saveDraft.sets.map(x=>({...x})),source:saveDraft.source||'record',savedAt:Date.now()};writeMeta(m);saveDraft=null;saving=false;decorateTimeline();renderTimeIntelligence()}
function openQuick(){renderQuick();$('#quickRecordSheet')?.classList.add('show');syncDock()}
function eqCatalog(){const c=readCore(),base=[
['cable','多功能龙门架','strength',['背部','胸肌','肩部']],['lat','高位下拉','strength',['背部','肱二头肌']],['row','坐姿 / 胸托划船','strength',['背部','肱二头肌']],['pec','飞鸟 / 后三角','strength',['胸肌','肩部']],['chest','胸推','strength',['胸肌','肱三头肌']],['shoulder','肩推','strength',['肩部','肱三头肌']],['dip','双杠 / 抬腿','strength',['胸肌','肱三头肌','核心']],['arms','手臂','strength',['肱二头肌','肱三头肌']],['legpress','坐姿腿推','strength',['股四头肌','臀部']],['hack','哈克 / 斜腿推','strength',['股四头肌','臀部']],['legext','腿屈伸','strength',['股四头肌']],['legcurl','腿弯举','strength',['腘绳肌']],['calf','小腿','strength',['小腿']],['dumbbell','哑铃','strength',['胸肌','背部','肩部']],['barbell','杠铃','strength',['背部','臀部','股四头肌']],['bodyweight','徒手','strength',['核心','胸肌','股四头肌']],['elliptical','椭圆机','cardio',['心肺','股四头肌','臀部']],['rower','划船机','cardio',['心肺','背部','股四头肌']],['treadmill','跑步机 / 跑步','cardio',['心肺','股四头肌','臀部']],['walk','步行','cardio',['心肺','股四头肌']]
].map(x=>({id:x[0],name:x[1],type:x[2],muscles:x[3]}));const custom=(c.profile?.customEq||[]).map(e=>({...e,custom:true}));return base.concat(custom)}
function renderQuick(){const all=eqCatalog(),by=new Map(all.map(x=>[x.id,x])),events=coreEvents(),usage=new Map();for(const e of events){const x=usage.get(e.equipmentId)||{n:0,last:0,event:null};x.n++;if((e.time||0)>=x.last){x.last=e.time||0;x.event=e}usage.set(e.equipmentId,x)}let recent=[...usage.entries()].sort((a,b)=>b[1].last-a[1].last).map(([id,u])=>({eq:by.get(id),u})).filter(x=>x.eq).slice(0,5);if(!recent.length)recent=CURATED.map(id=>({eq:by.get(id),u:{}})).filter(x=>x.eq);let mine=[...usage.entries()].sort((a,b)=>b[1].n-a[1].n||b[1].last-a[1].last).map(([id,u])=>({eq:by.get(id),u})).filter(x=>x.eq&&!recent.some(r=>r.eq.id===x.eq.id)).slice(0,4);for(const eq of all.filter(e=>e.custom)){if(!mine.some(x=>x.eq.id===eq.id)&&!recent.some(x=>x.eq.id===eq.id))mine.push({eq,u:{}})}mine=mine.slice(0,5);const row=x=>`<button class="v8QuickItem" data-v8eq="${esc(x.eq.id)}"><span><b>${esc(x.eq.name)}</b><small>${x.u.event?esc(setSummary(x.u.event)):esc((x.eq.muscles||[]).slice(0,2).join(' · '))}</small></span>${x.u.event?'<em>上次</em>':'<i>›</i>'}</button>`;$('#v8Recent').innerHTML=recent.map(row).join('');$('#v8MineWrap').classList.toggle('hidden',!mine.length);$('#v8Mine').innerHTML=mine.map(row).join('')}
function chooseQuick(id){$('#quickRecordSheet')?.classList.remove('show');$('#equipmentRow')?.click();setTimeout(()=>{const target=$$(`#eqSheet [data-eq]`).find(b=>b.dataset.eq===id);if(!target)return;target.click();setTimeout(()=>openQuickEditor(id),0)},0)}
function openQuickEditor(id){const s=$('#scanSheet');s?.classList.add('show','v8-quick-mode');$('#captureStage')?.classList.add('hidden');$('#reviewStage')?.classList.remove('hidden');if($('#film'))$('#film').innerHTML='';const h=$('#scanSheet .sheetHead>b');if(h)h.textContent='快速记录';prepareSetEditor(id);syncDock()}
function injectQuick(){if($('#quickRecordBtn'))return;const dock=$('#dock');if(!dock)return;dock.classList.add('v8-dual');$('#scanBtn span').textContent='拍摄记录';dock.insertAdjacentHTML('beforeend','<button class="v8QuickBtn" id="quickRecordBtn"><span>＋</span><b>快速记录</b></button>');D.body.insertAdjacentHTML('beforeend',`<div class="sheetWrap" id="quickRecordSheet"><div class="sheet v8QuickSheet"><div class="grabber"></div><div class="sheetHead"><b>快速记录</b><button class="closeBtn" data-v8close="quickRecordSheet">×</button></div><div class="v8Block"><span>最近</span><div id="v8Recent"></div></div><div class="v8Block" id="v8MineWrap"><span>我的器械</span><div id="v8Mine"></div></div><button class="v8Other" id="v8Other">其他器械 / 运动 <i>›</i></button><button class="v8New" id="v8New">＋ 新建自定义</button></div></div>`);$('#quickRecordBtn').onclick=openQuick;$('[data-v8close="quickRecordSheet"]').onclick=()=>{$('#quickRecordSheet').classList.remove('show');syncDock()};$('#v8Recent').onclick=$('#v8Mine').onclick=e=>{const b=e.target.closest('[data-v8eq]');if(b)chooseQuick(b.dataset.v8eq)};$('#v8Other').onclick=()=>{$('#quickRecordSheet').classList.remove('show');$('#equipmentRow')?.click()};$('#v8New').onclick=()=>{$('#quickRecordSheet').classList.remove('show');$('#addCustomEq')?.click()}}
function currentSelectedEq(){const name=$('#equipmentName')?.textContent?.trim(),all=eqCatalog();return all.find(e=>e.name===name)||null}
function defaultSetsFor(id){const last=lastEvent(id);if(last?.kind==='strength'){const s=eventSets(last);return s.map(x=>({weight:Number(x.weight)||0,reps:Number(x.reps)||0,doneAt:null}))}const w=Number($('#weight')?.value)||20,r=Number($('#repsChoices .active')?.dataset.value)||10,n=Number($('#setsChoices .active')?.dataset.value)||3;return Array.from({length:n},()=>({weight:w,reps:r,doneAt:null}))}
function prepareSetEditor(id){const eq=eqCatalog().find(e=>e.id===id)||currentSelectedEq();if(!eq||eq.type!=='strength'){hideSetEditor();return}draftSets=defaultSetsFor(eq.id);selectedSet=0;renderSetEditor(eq)}
function hideSetEditor(){$('#v8SetEditor')?.classList.add('hidden');$('#strengthFields')?.classList.remove('v8-hidden-core')}
function ensureSetEditor(){let e=$('#v8SetEditor');if(e)return e;e=D.createElement('div');e.id='v8SetEditor';e.className='v8SetEditor';$('#strengthFields')?.insertAdjacentElement('beforebegin',e);return e}
function syncCoreFromSets(){if(!draftSets.length)return;const active=draftSets[selectedSet]||draftSets[0],weight=$('#weight');if(weight)weight.value=active.weight;const reps=Math.max(1,Number(active.reps)||1),sets=draftSets.length;let rb=$(`#repsChoices [data-value="${reps}"]`);if(!rb){$('#repsChoices')?.insertAdjacentHTML('beforeend',`<button data-choice="reps" data-value="${reps}">${reps}</button>`);rb=$(`#repsChoices [data-value="${reps}"]`)}rb?.click();let sb=$(`#setsChoices [data-value="${sets}"]`);if(!sb){$('#setsChoices')?.insertAdjacentHTML('beforeend',`<button data-choice="sets" data-value="${sets}">${sets}</button>`);sb=$(`#setsChoices [data-value="${sets}"]`)}sb?.click()}
function nearby(v,step,min=0){return [v-step,v,v+step].filter(x=>x>=min).map(x=>Math.round(x*10)/10)}
function renderSetEditor(eq=currentSelectedEq()){if(!eq||eq.type!=='strength')return hideSetEditor();const wrap=ensureSetEditor();$('#strengthFields')?.classList.add('v8-hidden-core');if(!draftSets.length)draftSets=defaultSetsFor(eq.id);selectedSet=Math.min(selectedSet,draftSets.length-1);const last=lastEvent(eq.id);wrap.classList.remove('hidden');wrap.innerHTML=`<div class="v8SetHead"><div><b>每组记录</b><span>${last?'上次 '+esc(setSummary(last)):'重量和次数可逐组调整'}</span></div><div class="v8SetCount"><button data-v8setcount="-1">−</button><b>${draftSets.length}组</b><button data-v8setcount="1">＋</button></div></div><div class="v8SetRows">${draftSets.map((s,i)=>`<button class="v8SetRow ${i===selectedSet?'active':''} ${s.doneAt?'done':''}" data-v8set="${i}"><i>${pad(i+1)}</i><span><b>${fmt(s.weight)}</b><small>kg</small></span><span><b>${s.reps}</b><small>次</small></span><em>${s.doneAt?'✓':'·'}</em></button>`).join('')}</div><div class="v8Adjust"><div><span>重量</span>${nearby(draftSets[selectedSet].weight,2.5).map(v=>`<button data-v8weight="${v}" class="${Number(v)===Number(draftSets[selectedSet].weight)?'active':''}">${fmt(v)}</button>`).join('')}</div><div><span>次数</span>${[6,8,10,12,15,draftSets[selectedSet].reps].filter((v,i,a)=>a.indexOf(v)===i).sort((a,b)=>a-b).map(v=>`<button data-v8reps="${v}" class="${Number(v)===Number(draftSets[selectedSet].reps)?'active':''}">${v}</button>`).join('')}</div></div><button class="v8DoneSet" id="v8DoneSet">${draftSets[selectedSet].doneAt?'取消完成':'完成这一组'}</button>`;syncCoreFromSets()}
function alterSetCount(delta){const eq=currentSelectedEq();if(!eq)return;const n=Math.max(1,Math.min(8,draftSets.length+delta));while(draftSets.length<n){const last=draftSets[draftSets.length-1]||{weight:20,reps:10};draftSets.push({weight:last.weight,reps:last.reps,doneAt:null})}while(draftSets.length>n)draftSets.pop();selectedSet=Math.min(selectedSet,n-1);renderSetEditor(eq)}
function setField(field,val){if(!draftSets[selectedSet])return;draftSets[selectedSet][field]=Number(val);renderSetEditor()}
function toggleDoneSet(){if(!draftSets[selectedSet])return;draftSets[selectedSet].doneAt=draftSets[selectedSet].doneAt?null:Date.now();if(draftSets[selectedSet].doneAt){const next=draftSets.findIndex((s,i)=>i>selectedSet&&!s.doneAt);if(next>=0)selectedSet=next}renderSetEditor()}
function installSetHandlers(){D.addEventListener('click',e=>{const b=e.target.closest('[data-v8set],[data-v8setcount],[data-v8weight],[data-v8reps],#v8DoneSet');if(!b)return;if(b.dataset.v8set!=null){selectedSet=Number(b.dataset.v8set);renderSetEditor();return}if(b.dataset.v8setcount){alterSetCount(Number(b.dataset.v8setcount));return}if(b.dataset.v8weight){setField('weight',b.dataset.v8weight);return}if(b.dataset.v8reps){setField('reps',b.dataset.v8reps);return}if(b.id==='v8DoneSet')toggleDoneSet()})}
function timeModel(session){if(!session)return{span:0,effective:0,gap:0,segments:0};const events=Array.isArray(session.events)?session.events:[];if(!events.length)return{span:0,effective:0,gap:0,segments:0};const meta=readMeta(),intervals=[];for(const e of events){if(e.kind==='cardio'){const dur=Math.max(1,Number(e.duration)||1)*60000;intervals.push([Math.max(0,(e.time||Date.now())-dur),e.time||Date.now()]);continue}const sets=meta.events?.[e.id]?.sets||eventSets(e),done=sets.map(s=>Number(s.doneAt)||0).filter(Boolean).sort((a,b)=>a-b);if(done.length){intervals.push([Math.max(0,done[0]-45000),done[done.length-1]])}else{const n=Math.max(1,sets.length),est=n*45000+Math.max(0,n-1)*90000;intervals.push([Math.max(0,(e.time||Date.now())-est),e.time||Date.now()])}}
intervals.sort((a,b)=>a[0]-b[0]);const rawGaps=[];for(let i=1;i<intervals.length;i++){const g=intervals[i][0]-intervals[i-1][1];if(g>30000&&g<20*60000)rawGaps.push(g)}const normal=rawGaps.length?median(rawGaps):2.5*60000,threshold=Math.max(6*60000,Math.min(14*60000,normal*2.5));const merged=[];for(const it of intervals){const last=merged[merged.length-1];if(last&&it[0]-last[1]<=threshold)last[1]=Math.max(last[1],it[1]);else merged.push([...it])}const first=intervals[0][0],last=intervals[intervals.length-1][1],span=Math.max(0,last-first),effective=merged.reduce((n,x)=>n+Math.max(0,x[1]-x[0]),0),gap=Math.max(0,span-effective);return{span,effective,gap,segments:merged.length,threshold}}
function median(a){if(!a.length)return 0;const x=[...a].sort((p,q)=>p-q),m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2}
function renderTimeIntelligence(){const c=readCore(),s=c.active||c.sessions?.[0];if(!s)return;const t=timeModel(s);let box=$('#v8TimeModel');if(!box){box=D.createElement('div');box.id='v8TimeModel';box.className='v8TimeModel';const anchor=$('#activeHome .metricPair.compact');anchor?.insertAdjacentElement('afterend',box)}if(c.active&&box)box.innerHTML=`<div><span>训练跨度</span><b>${mm(t.span)}分</b></div><div><span>有效训练</span><b>约${mm(t.effective)}分</b></div>${t.gap>=5*60000?`<div><span>空档</span><b>${mm(t.gap)}分</b></div>`:''}${t.segments>1?`<div><span>区段</span><b>${t.segments}</b></div>`:''}`;decorateHistoryTimes()}
function decorateHistoryTimes(){const c=readCore();$$('[data-session]').forEach(row=>{const s=(c.sessions||[]).find(x=>x.id===row.dataset.session);if(!s)return;const t=timeModel(s),small=$('small',row);if(small)small.textContent=`${(s.events||[]).length}项 · 有效约${mm(t.effective)}分 · 跨度${mm(t.span)}分`})}
function decorateTimeline(){const c=readCore(),events=c.active?.events||[];$$('#eventList [data-event]').forEach(row=>{const e=events.find(x=>x.id===row.dataset.event);if(!e||e.kind!=='strength')return;const small=$('small',row);if(small)small.textContent=setSummary(e)})}
function showFinishTime(){const c=readCore(),s=c.sessions?.[0];if(!s||!$('#finishSheet')?.classList.contains('show'))return;const t=timeModel(s);let e=$('#v8FinishTime');if(!e){e=D.createElement('div');e.id='v8FinishTime';e.className='v8FinishTime';$('.finishStats')?.insertAdjacentElement('beforebegin',e)}e.innerHTML=`<div><span>有效训练</span><b>约 ${mm(t.effective)} 分钟</b></div><div><span>训练跨度</span><b>${mm(t.span)} 分钟</b></div>${t.gap>=5*60000?`<div><span>空档</span><b>${mm(t.gap)} 分钟</b></div>`:''}`;$('#finishDuration').textContent=`${mm(t.span)}分钟`}
function installAutoStartCommit(){const save=$('#saveScan');if(!save)return;save.addEventListener('click',()=>{const eq=currentSelectedEq();if(!eq)return;if(eq.type==='strength'){if(!draftSets.length)prepareSetEditor(eq.id);syncCoreFromSets();saveDraft={sets:draftSets.map(s=>({...s})),source:$('#scanSheet')?.classList.contains('v8-quick-mode')?'quick':'camera'}}else saveDraft=null;const before=activeEventIds();ensureSessionForCommit();saving=true;setTimeout(()=>waitForNewEvent(before),0)},true)}
function installEquipmentWatcher(){const name=$('#equipmentName');if(!name)return;new MutationObserver(()=>{const eq=currentSelectedEq();if(eq?.type==='strength')prepareSetEditor(eq.id);else hideSetEditor()}).observe(name,{childList:true,characterData:true,subtree:true})}
function syncDock(){const today=$('#todayView')?.classList.contains('active'),sheet=$$('.sheetWrap.show').some(x=>x.id!=='finishSheet');const dock=$('#dock');if(!dock)return;dock.classList.toggle('show',!!today&&!sheet);dock.classList.toggle('v8-force',!!today&&!sheet)}
function simplifyIdle(){const idle=$('#idleHome');if(!idle)return;$('.sessionLead',idle)?.classList.add('v8-hide-start');const title=$('#helloTitle');if(title)title.textContent='';const last=$('#lastSession');if(last)last.textContent='';let hint=$('#v8IdleHint');if(!hint){hint=D.createElement('div');hint.id='v8IdleHint';hint.className='v8IdleHint';hint.innerHTML='<b>怎么方便怎么记</b><span>第一条记录会自动开始今天的训练</span>';idle.insertBefore(hint,$('.metricPair',idle))}}
function renameCapture(){const b=$('#scanBtn span');if(b)b.textContent='拍摄记录';const h=$('#scanSheet .sheetHead>b');if(h&&!$('#scanSheet')?.classList.contains('v8-quick-mode'))h.textContent='拍摄记录';$$('#captureModes [data-mode]').forEach(x=>x.textContent=x.dataset.mode==='photo'?'单张':`${x.dataset.mode}秒`);const s=$('#settingsSheet .versionLine');if(s)s.textContent='版本 8.0'}
function clearQuickMode(){const s=$('#scanSheet');if(!s)return;s.classList.remove('v8-quick-mode');$('#captureStage')?.classList.remove('hidden');renameCapture()}
function installLayerNavigation(){const ids=['profileBtn','myEqBtn','watermarkBtn','storageBtn','reportBtn'];D.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(ids.includes(b.id))$('#settingsSheet')?.classList.remove('show');if(b.id==='newCustomEq'||b.matches('[data-edit-eq]'))$('#myEqSheet')?.classList.remove('show');requestAnimationFrame(syncDock)},true)}
function installMutation(){new MutationObserver(()=>{syncDock();decorateTimeline();renderTimeIntelligence();showFinishTime()}).observe(D.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']})}
function inject(){injectQuick();simplifyIdle();renameCapture();installSetHandlers();installAutoStartCommit();installEquipmentWatcher();installLayerNavigation();installMutation();$('#scanBtn')?.addEventListener('click',()=>{clearQuickMode();setTimeout(renameCapture,0)},true);D.addEventListener('click',e=>{if(e.target.closest('[data-close="scanSheet"]'))setTimeout(clearQuickMode,0)},true);window.addEventListener('pageshow',()=>{syncDock();decorateTimeline();renderTimeIntelligence()});syncDock();decorateTimeline();renderTimeIntelligence()}
if(D.readyState==='loading')D.addEventListener('DOMContentLoaded',inject,{once:true});else inject();
})();