(()=>{'use strict';
const D=document,$=(s,r=D)=>r.querySelector(s),$$=(s,r=D)=>Array.from(r.querySelectorAll(s));
const CORE='axis_v60_state',META='axis_v8_meta';
const CAT=[['chest','胸推','strength'],['lat','高位下拉','strength'],['legpress','坐姿腿推','strength'],['row','坐姿 / 胸托划船','strength'],['dumbbell','哑铃','strength'],['treadmill','跑步机 / 跑步','cardio'],['rower','划船机','cardio'],['elliptical','椭圆机','cardio']];
let draft=[],sel=0,pending=null,quickOther=false;
function core(){try{return JSON.parse(localStorage.getItem(CORE)||'null')||{sessions:[],active:null,profile:{customEq:[]}}}catch{return{sessions:[],active:null,profile:{customEq:[]}}}}
function mread(){try{return JSON.parse(localStorage.getItem(META)||'null')||{events:{}}}catch{return{events:{}}}}
function msave(m){try{localStorage.setItem(META,JSON.stringify(m))}catch{}}
function allEvents(){const c=core();return (c.active?[c.active]:[]).concat(c.sessions||[]).flatMap(s=>s.events||[])}
function last(id){return allEvents().filter(e=>e.equipmentId===id).sort((a,b)=>(b.time||0)-(a.time||0))[0]||null}
function setsOf(e){const a=mread().events?.[e?.id]?.sets;if(Array.isArray(a)&&a.length)return a;return Array.from({length:Math.max(1,Number(e?.sets)||1)},()=>({weight:Number(e?.weight)||0,reps:Number(e?.reps)||0,doneAt:null}))}
function fmt(n){n=Number(n)||0;return n%1?n.toFixed(1):String(n)}function pad(n){return String(n).padStart(2,'0')}function mins(ms){return Math.max(0,Math.round(ms/60000))}
function summary(e){if(!e)return'';if(e.kind==='cardio')return`${e.duration||0}分钟 · 强度${e.intensity||0}`;const a=setsOf(e),w=[...new Set(a.map(s=>fmt(s.weight)))];return`${w.length===1?w[0]+'kg':'分组重量'} · ${a.map(s=>s.reps).join(' / ')}`}
function selected(){const n=$('#equipmentName')?.textContent?.trim();if(!n||n==='待确认')return null;const e=allEvents().find(x=>x.name===n);if(e)return{...e,id:e.equipmentId,type:e.kind};const c=core(),custom=c.profile?.customEq||[];const ce=custom.find(x=>x.name===n);if(ce)return ce;const x=CAT.find(q=>q[1]===n);return x?{id:x[0],name:x[1],type:x[2]}:{id:null,name:n,type:$('#cardioFields')?.classList.contains('hidden')?'strength':'cardio'}}
function syncDock(){const today=$('#todayView')?.classList.contains('active'),sheet=$$('.sheetWrap.show').some(x=>x.id!=='finishSheet');const d=$('#dock');if(!d)return;d.classList.toggle('show',!!today&&!sheet);d.classList.toggle('v8-force',!!today&&!sheet)}
function basic(){const lead=$('#idleHome .sessionLead');if(lead)lead.classList.add('v8-hide-start');$('#scanBtn span').textContent='拍摄记录';const h=$('#scanSheet .sheetHead>b');if(h&&!$('#scanSheet')?.classList.contains('v8-quick'))h.textContent='拍摄记录';$$('#captureModes [data-mode]').forEach(b=>b.textContent=b.dataset.mode==='photo'?'单张':`${b.dataset.mode}秒`);if($('.versionLine'))$('.versionLine').textContent='版本 8.0'}
function injectQuick(){if($('#quickRecordBtn'))return;const d=$('#dock');d.classList.add('v8-dual');d.insertAdjacentHTML('beforeend','<button id="quickRecordBtn" class="v8QuickBtn"><span>＋</span><b>快速记录</b></button>');D.body.insertAdjacentHTML('beforeend','<div class="sheetWrap" id="quickRecordSheet"><div class="sheet v8QuickSheet"><div class="grabber"></div><div class="sheetHead"><b>快速记录</b><button class="closeBtn" id="quickClose">×</button></div><div class="v8Block"><span>最近</span><div id="v8Recent"></div></div><button class="v8Other" id="v8Other">其他器械 / 运动 <i>›</i></button><button class="v8New" id="v8New">＋ 新建自定义</button></div></div>');$('#quickRecordBtn').onclick=openQuick;$('#quickClose').onclick=()=>{$('#quickRecordSheet').classList.remove('show');syncDock()};$('#v8Recent').onclick=e=>{const b=e.target.closest('[data-qid]');if(b)chooseQuick(b.dataset.qid)};$('#v8Other').onclick=()=>{quickOther=true;$('#quickRecordSheet').classList.remove('show');$('#equipmentRow')?.click()};$('#v8New').onclick=()=>{$('#quickRecordSheet').classList.remove('show');$('#addCustomEq')?.click()}}
function openQuick(){const map=new Map(),ev=allEvents();for(const e of ev)if(!map.has(e.equipmentId))map.set(e.equipmentId,e);let items=[...map.values()].slice(0,5).map(e=>({id:e.equipmentId,name:e.name,meta:summary(e)}));if(!items.length)items=CAT.slice(0,6).map(x=>({id:x[0],name:x[1],meta:x[2]==='cardio'?'有氧':'力量'}));$('#v8Recent').innerHTML=items.map(x=>`<button class="v8QuickItem" data-qid="${x.id}"><span><b>${x.name}</b><small>${x.meta}</small></span><i>›</i></button>`).join('');$('#quickRecordSheet').classList.add('show');syncDock()}
function chooseQuick(id){$('#quickRecordSheet').classList.remove('show');$('#equipmentRow')?.click();setTimeout(()=>{const b=$$('#eqSheet [data-eq]').find(x=>x.dataset.eq===id);if(b){b.click();setTimeout(showQuickEditor,0)}},0)}
function showQuickEditor(){const s=$('#scanSheet');s.classList.add('show','v8-quick');$('#captureStage').classList.add('hidden');$('#reviewStage').classList.remove('hidden');$('#film').innerHTML='';$('#scanSheet .sheetHead>b').textContent='快速记录';const e=selected();if(e?.type==='strength')prepare(e.id);syncDock()}
function prepare(id){const e=last(id);if(e?.kind==='strength')draft=setsOf(e).map(x=>({weight:Number(x.weight)||0,reps:Number(x.reps)||0,doneAt:null}));else{const w=Number($('#weight')?.value)||20,r=Number($('#repsChoices .active')?.dataset.value)||10,n=Number($('#setsChoices .active')?.dataset.value)||3;draft=Array.from({length:n},()=>({weight:w,reps:r,doneAt:null}))}sel=0;renderSets()}
function renderSets(){const e=selected();if(!e||e.type!=='strength'){hideSets();return}if(!draft.length)prepare(e.id);let box=$('#v8Sets');if(!box){box=D.createElement('div');box.id='v8Sets';box.className='v8Sets';$('#strengthFields')?.insertAdjacentElement('beforebegin',box)}$('#strengthFields').classList.add('v8-hide-core');box.classList.remove('hidden');sel=Math.min(sel,draft.length-1);const c=draft[sel],prev=last(e.id);const wopts=[c.weight-2.5,c.weight,c.weight+2.5].filter(x=>x>=0);box.innerHTML=`<div class="v8SetHead"><div><b>每组</b><span>${prev?'上次 '+summary(prev):'逐组记录'}</span></div><div class="v8SetCount"><button data-cnt="-1">−</button><b>${draft.length}组</b><button data-cnt="1">＋</button></div></div><div class="v8SetRows">${draft.map((s,i)=>`<button class="v8SetRow ${i===sel?'active':''} ${s.doneAt?'done':''}" data-si="${i}"><i>${pad(i+1)}</i><span><b>${fmt(s.weight)}</b><small>kg</small></span><span><b>${s.reps}</b><small>次</small></span><em>${s.doneAt?'✓':'·'}</em></button>`).join('')}</div><div class="v8Adjust"><div><span>重量</span>${wopts.map(v=>`<button data-w="${v}" class="${v===c.weight?'active':''}">${fmt(v)}</button>`).join('')}</div><div><span>次数</span>${[6,8,10,12,15,c.reps].filter((v,i,a)=>a.indexOf(v)===i).sort((a,b)=>a-b).map(v=>`<button data-r="${v}" class="${v===c.reps?'active':''}">${v}</button>`).join('')}</div></div><button id="doneSet8" class="v8DoneSet">${c.doneAt?'取消完成':'完成这一组'}</button>`;syncHidden()}
function hideSets(){$('#v8Sets')?.classList.add('hidden');$('#strengthFields')?.classList.remove('v8-hide-core')}
function syncHidden(){if(!draft.length)return;const weight=Math.max(...draft.map(s=>Number(s.weight)||0)),reps=draft[0].reps,n=draft.length;$('#weight').value=weight;let rb=$(`#repsChoices [data-value="${reps}"]`);if(!rb){$('#repsChoices').insertAdjacentHTML('beforeend',`<button data-choice="reps" data-value="${reps}">${reps}</button>`);rb=$(`#repsChoices [data-value="${reps}"]`)}rb?.click();let sb=$(`#setsChoices [data-value="${n}"]`);if(!sb){$('#setsChoices').insertAdjacentHTML('beforeend',`<button data-choice="sets" data-value="${n}">${n}</button>`);sb=$(`#setsChoices [data-value="${n}"]`)}sb?.click()}
function changeCount(d){const n=Math.max(1,Math.min(8,draft.length+d));while(draft.length<n){const x=draft.at(-1)||{weight:20,reps:10};draft.push({weight:x.weight,reps:x.reps,doneAt:null})}while(draft.length>n)draft.pop();sel=Math.min(sel,n-1);renderSets()}
function autoStart(){const e=selected();if(!e)return;pending=e.type==='strength'?draft.map(x=>({...x})):null;if(e.type==='strength')syncHidden();const c=core(),before=new Set((c.active?.events||[]).map(x=>x.id));if(!c.active){$('#startBtn')?.click();$('#toast')?.classList.remove('show')}pulse();requestAnimationFrame(()=>{$('#scanSheet')?.classList.remove('show');syncDock()});setTimeout(()=>attach(before),0)}
function attach(before,n=0){const e=(core().active?.events||[]).find(x=>!before.has(x.id));if(e){if(pending&&e.kind==='strength'){const m=mread();m.events=m.events||{};m.events[e.id]={sets:pending,savedAt:Date.now()};msave(m)}pending=null;decorate();return}if(n<70)setTimeout(()=>attach(before,n+1),80)}
function pulse(){let p=$('#v8Pulse');if(!p){p=D.createElement('div');p.id='v8Pulse';p.className='v8Pulse';D.body.appendChild(p)}p.textContent='已记下';p.classList.add('show');clearTimeout(p._t);p._t=setTimeout(()=>p.classList.remove('show'),900)}
function median(a){if(!a.length)return 0;const x=[...a].sort((p,q)=>p-q),i=Math.floor(x.length/2);return x.length%2?x[i]:(x[i-1]+x[i])/2}
function timeModel(s){if(!s?.events?.length)return{span:0,effective:0,gap:0,segments:0};const m=mread(),iv=[];for(const e of s.events){if(e.kind==='cardio'){const d=Math.max(1,Number(e.duration)||1)*60000;iv.push([(e.time||Date.now())-d,e.time||Date.now()]);continue}const a=m.events?.[e.id]?.sets||setsOf(e),done=a.map(x=>Number(x.doneAt)||0).filter(Boolean).sort((x,y)=>x-y);if(done.length)iv.push([done[0]-45000,done.at(-1)]);else{const n=Math.max(1,a.length),d=n*45000+Math.max(0,n-1)*90000;iv.push([(e.time||Date.now())-d,e.time||Date.now()])}}iv.sort((a,b)=>a[0]-b[0]);const gs=[];for(let i=1;i<iv.length;i++){const g=iv[i][0]-iv[i-1][1];if(g>30000&&g<1200000)gs.push(g)}const th=Math.max(360000,Math.min(840000,(median(gs)||150000)*2.5)),merged=[];for(const x of iv){const p=merged.at(-1);if(p&&x[0]-p[1]<=th)p[1]=Math.max(p[1],x[1]);else merged.push([...x])}const span=Math.max(0,iv.at(-1)[1]-iv[0][0]),effective=merged.reduce((n,x)=>n+Math.max(0,x[1]-x[0]),0);return{span,effective,gap:Math.max(0,span-effective),segments:merged.length}}
function decorate(){const c=core();if(c.active){const t=timeModel(c.active);let b=$('#v8Time');if(!b){b=D.createElement('div');b.id='v8Time';b.className='v8Time';$('#activeHome .metricPair.compact')?.insertAdjacentElement('afterend',b)}const h=`<div><span>跨度</span><b>${mins(t.span)}分</b></div><div><span>有效训练</span><b>约${mins(t.effective)}分</b></div>${t.gap>=300000?`<div><span>空档</span><b>${mins(t.gap)}分</b></div>`:''}${t.segments>1?`<div><span>区段</span><b>${t.segments}</b></div>`:''}`;if(b.innerHTML!==h)b.innerHTML=h}else $('#v8Time')?.remove();for(const r of $$('#eventList [data-event]')){const e=(c.active?.events||[]).find(x=>x.id===r.dataset.event);if(e?.kind==='strength'){const sm=$('small',r),v=summary(e);if(sm&&sm.textContent!==v)sm.textContent=v}}for(const r of $$('[data-session]')){const s=(c.sessions||[]).find(x=>x.id===r.dataset.session);if(!s)continue;const t=timeModel(s),sm=$('small',r),v=`${s.events?.length||0}项 · 有效约${mins(t.effective)}分 · 跨度${mins(t.span)}分`;if(sm&&sm.textContent!==v)sm.textContent=v}if($('#finishSheet')?.classList.contains('show')&&c.sessions?.[0]){const t=timeModel(c.sessions[0]);$('#finishDuration').textContent=`${mins(t.span)}分钟`;let f=$('#v8Finish');if(!f){f=D.createElement('div');f.id='v8Finish';f.className='v8Finish';$('.finishStats')?.insertAdjacentElement('beforebegin',f)}f.innerHTML=`<div><span>有效训练</span><b>约 ${mins(t.effective)} 分钟</b></div><div><span>训练跨度</span><b>${mins(t.span)} 分钟</b></div>${t.gap>=300000?`<div><span>空档</span><b>${mins(t.gap)} 分钟</b></div>`:''}`}}
function bind(){injectQuick();basic();syncDock();$('#saveScan')?.addEventListener('click',autoStart,true);const nm=$('#equipmentName');if(nm)new MutationObserver(()=>{const e=selected();if(e?.type==='strength')prepare(e.id);else hideSets()}).observe(nm,{childList:true,subtree:true});D.addEventListener('click',e=>{const b=e.target.closest('button,[data-edit-eq]');if(!b)return;if(['profileBtn','myEqBtn','watermarkBtn','storageBtn','reportBtn'].includes(b.id))$('#settingsSheet')?.classList.remove('show');if(b.dataset.si!=null){sel=Number(b.dataset.si);renderSets()}else if(b.dataset.cnt)changeCount(Number(b.dataset.cnt));else if(b.dataset.w){draft[sel].weight=Number(b.dataset.w);renderSets()}else if(b.dataset.r){draft[sel].reps=Number(b.dataset.r);renderSets()}else if(b.id==='doneSet8'){draft[sel].doneAt=draft[sel].doneAt?null:Date.now();if(draft[sel].doneAt){const n=draft.findIndex((x,i)=>i>sel&&!x.doneAt);if(n>=0)sel=n}renderSets()}else if(b.matches('#eqSheet [data-eq]')&&quickOther){quickOther=false;setTimeout(showQuickEditor,0)}if(b.id==='scanBtn')setTimeout(()=>{$('#scanSheet')?.classList.remove('v8-quick');$('#captureStage')?.classList.remove('hidden');basic()},0);requestAnimationFrame(()=>{syncDock();decorate()})},true);new MutationObserver(decorate).observe($('#eventList'),{childList:true,subtree:true});new MutationObserver(decorate).observe($('#historyList'),{childList:true,subtree:true});new MutationObserver(()=>{syncDock();decorate()}).observe(D.body,{subtree:true,attributes:true,attributeFilter:['class']});window.addEventListener('pageshow',()=>{basic();syncDock();decorate()});decorate()}
if(D.readyState==='loading')D.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();