(()=>{'use strict';
const D=document,$=(s,r=D)=>r.querySelector(s),$$=(s,r=D)=>Array.from(r.querySelectorAll(s));
const CORE='axis_v60_state',META='axis_v8_meta';
const BASE=[['cable','多功能龙门架','strength',['背部','胸肌','肩部']],['lat','高位下拉','strength',['背部','肱二头肌']],['row','坐姿 / 胸托划船','strength',['背部','肱二头肌']],['pec','飞鸟 / 后三角','strength',['胸肌','肩部']],['chest','胸推','strength',['胸肌','肱三头肌']],['shoulder','肩推','strength',['肩部','肱三头肌']],['dip','双杠 / 抬腿','strength',['胸肌','肱三头肌','核心']],['arms','手臂','strength',['肱二头肌','肱三头肌']],['legpress','坐姿腿推','strength',['股四头肌','臀部']],['hack','哈克 / 斜腿推','strength',['股四头肌','臀部']],['legext','腿屈伸','strength',['股四头肌']],['legcurl','腿弯举','strength',['腘绳肌']],['calf','小腿','strength',['小腿']],['dumbbell','哑铃','strength',['胸肌','背部','肩部']],['barbell','杠铃','strength',['背部','臀部','股四头肌']],['bodyweight','徒手','strength',['核心','胸肌','股四头肌']],['elliptical','椭圆机','cardio',['心肺','股四头肌','臀部']],['rower','划船机','cardio',['心肺','背部','股四头肌']],['treadmill','跑步机 / 跑步','cardio',['心肺','股四头肌','臀部']],['walk','步行','cardio',['心肺','股四头肌']]].map(x=>({id:x[0],name:x[1],type:x[2],muscles:x[3]}));
const CURATED=['chest','lat','legpress','row','dumbbell','treadmill'];let sets=[],setIndex=0,pending=null,quickOther=false,reopenQuick=false;
function core(){try{return JSON.parse(localStorage.getItem(CORE)||'null')||{sessions:[],active:null,profile:{customEq:[]}}}catch{return{sessions:[],active:null,profile:{customEq:[]}}}}
function meta(){try{return JSON.parse(localStorage.getItem(META)||'null')||{events:{}}}catch{return{events:{}}}}
function saveMeta(m){try{localStorage.setItem(META,JSON.stringify(m))}catch{}}
function eqs(){const c=core(),custom=(c.profile?.customEq||[]).map(e=>({...e,custom:true}));return BASE.concat(custom)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]))}
function fmt(n){n=Number(n)||0;return n%1?n.toFixed(1):String(n)}function pad(n){return String(n).padStart(2,'0')}function min(ms){return Math.max(0,Math.round(ms/60000))}
function events(){const c=core();return (c.active?[c.active]:[]).concat(c.sessions||[]).flatMap(s=>s.events||[])}function last(id){return events().filter(e=>e.equipmentId===id).sort((a,b)=>(b.time||0)-(a.time||0))[0]||null}
function eventSets(e){const x=meta().events?.[e?.id]?.sets;if(Array.isArray(x)&&x.length)return x;return Array.from({length:Math.max(1,Number(e?.sets)||1)},()=>({weight:Number(e?.weight)||0,reps:Number(e?.reps)||0,doneAt:null}))}
function summary(e){if(!e)return'';if(e.kind==='cardio')return`${e.duration||0}分钟 · 强度${e.intensity||0}`;const s=eventSets(e),w=[...new Set(s.map(x=>fmt(x.weight)))];return`${w.length===1?w[0]+'kg':'分组重量'} · ${s.map(x=>Number(x.reps)||0).join(' / ')}`}
function selectedEq(){const n=$('#equipmentName')?.textContent?.trim();return eqs().find(e=>e.name===n)||null}
function syncDock(){const today=$('#todayView')?.classList.contains('active'),sheet=$$('.sheetWrap.show').some(x=>x.id!=='finishSheet');const d=$('#dock');if(!d)return;d.classList.toggle('show',!!today&&!sheet);d.classList.toggle('v8-force',!!today&&!sheet)}
function simplify(){const lead=$('#idleHome .sessionLead');if(lead)lead.classList.add('v8-hide-start');const s=$('.versionLine');if(s)s.textContent='版本 8.0';const scan=$('#scanBtn span');if(scan)scan.textContent='拍摄记录';const head=$('#scanSheet .sheetHead>b');if(head&&!$('#scanSheet')?.classList.contains('v8-quick'))head.textContent='拍摄记录';$$('#captureModes [data-mode]').forEach(b=>b.textContent=b.dataset.mode==='photo'?'单张':`${b.dataset.mode}秒`)}
function injectQuick(){if($('#quickRecordBtn'))return;const d=$('#dock');if(!d)return;d.classList.add('v8-dual');d.insertAdjacentHTML('beforeend','<button class="v8QuickBtn" id="quickRecordBtn"><span>＋</span><b>快速记录</b></button>');D.body.insertAdjacentHTML('beforeend',`<div class="sheetWrap" id="quickRecordSheet"><div class="sheet v8QuickSheet"><div class="grabber"></div><div class="sheetHead"><b>快速记录</b><button class="closeBtn" id="quickClose">×</button></div><div class="v8Block"><span>最近</span><div id="v8Recent"></div></div><div class="v8Block" id="v8MineWrap"><span>我的器械</span><div id="v8Mine"></div></div><button class="v8Other" id="v8Other">其他器械 / 运动 <i>›</i></button><button class="v8New" id="v8New">＋ 新建自定义</button></div></div>`);$('#quickRecordBtn').onclick=openQuick;$('#quickClose').onclick=()=>{$('#quickRecordSheet').classList.remove('show');syncDock()};$('#v8Recent').onclick=$('#v8Mine').onclick=e=>{const b=e.target.closest('[data-eq8]');if(b)chooseQuick(b.dataset.eq8)};$('#v8Other').onclick=()=>{quickOther=true;$('#quickRecordSheet').classList.remove('show');$('#equipmentRow')?.click()};$('#v8New').onclick=()=>{reopenQuick=true;$('#quickRecordSheet').classList.remove('show');$('#addCustomEq')?.click()}}
function renderQuick(){const all=eqs(),by=new Map(all.map(e=>[e.id,e])),u=new Map();for(const e of events()){const x=u.get(e.equipmentId)||{n:0,t:0,e:null};x.n++;if((e.time||0)>=x.t){x.t=e.time||0;x.e=e}u.set(e.equipmentId,x)}let recent=[...u.entries()].sort((a,b)=>b[1].t-a[1].t).map(([id,x])=>({eq:by.get(id),x})).filter(x=>x.eq).slice(0,5);if(!recent.length)recent=CURATED.map(id=>({eq:by.get(id),x:{}})).filter(x=>x.eq);let mine=[...u.entries()].sort((a,b)=>b[1].n-a[1].n||b[1].t-a[1].t).map(([id,x])=>({eq:by.get(id),x})).filter(x=>x.eq&&!recent.some(r=>r.eq.id===x.eq.id)).slice(0,4);for(const q of all.filter(e=>e.custom))if(!recent.some(x=>x.eq.id===q.id)&&!mine.some(x=>x.eq.id===q.id))mine.push({eq:q,x:{}});mine=mine.slice(0,5);const row=o=>`<button class="v8QuickItem" data-eq8="${esc(o.eq.id)}"><span><b>${esc(o.eq.name)}</b><small>${o.x.e?esc(summary(o.x.e)):esc((o.eq.muscles||[]).slice(0,2).join(' · '))}</small></span>${o.x.e?'<em>上次</em>':'<i>›</i>'}</button>`;$('#v8Recent').innerHTML=recent.map(row).join('');$('#v8MineWrap').classList.toggle('hidden',!mine.length);$('#v8Mine').innerHTML=mine.map(row).join('')}
function openQuick(){renderQuick();$('#quickRecordSheet').classList.add('show');syncDock()}
function chooseQuick(id){$('#quickRecordSheet').classList.remove('show');$('#equipmentRow')?.click();setTimeout(()=>{const b=$$(`#eqSheet [data-eq]`).find(x=>x.dataset.eq===id);if(b){b.click();setTimeout(()=>showEditor(id),0)}},0)}
function showEditor(id){const s=$('#scanSheet');s.classList.add('show','v8-quick');$('#captureStage').classList.add('hidden');$('#reviewStage').classList.remove('hidden');$('#film').innerHTML='';const h=$('#scanSheet .sheetHead>b');if(h)h.textContent='快速记录';prepareSets(id);syncDock()}
function defaultSets(id){const e=last(id);if(e?.kind==='strength')return eventSets(e).map(x=>({weight:Number(x.weight)||0,reps:Number(x.reps)||0,doneAt:null}));const w=Number($('#weight')?.value)||20,r=Number($('#repsChoices .active')?.dataset.value)||10,n=Number($('#setsChoices .active')?.dataset.value)||3;return Array.from({length:n},()=>({weight:w,reps:r,doneAt:null}))}
function prepareSets(id){const e=eqs().find(x=>x.id===id)||selectedEq();if(!e||e.type!=='strength')return hideSets();sets=defaultSets(e.id);setIndex=0;renderSets(e)}
function hideSets(){$('#v8Sets')?.classList.add('hidden');$('#strengthFields')?.classList.remove('v8-hide-core')}
function setBox(){let b=$('#v8Sets');if(!b){b=D.createElement('div');b.id='v8Sets';b.className='v8Sets';$('#strengthFields')?.insertAdjacentElement('beforebegin',b)}return b}
function syncCore(){if(!sets.length)return;const weights=sets.map(s=>Number(s.weight)||0),first=sets[0],w=$('#weight');if(w)w.value=Math.max(...weights);let rb=$(`#repsChoices [data-value="${first.reps}"]`);if(!rb){$('#repsChoices')?.insertAdjacentHTML('beforeend',`<button data-choice="reps" data-value="${first.reps}">${first.reps}</button>`);rb=$(`#repsChoices [data-value="${first.reps}"]`)}rb?.click();let sb=$(`#setsChoices [data-value="${sets.length}"]`);if(!sb){$('#setsChoices')?.insertAdjacentHTML('beforeend',`<button data-choice="sets" data-value="${sets.length}">${sets.length}</button>`);sb=$(`#setsChoices [data-value="${sets.length}"]`}sb?.click()}
function around(v,step){return[v-step,v,v+step].filter(x=>x>=0).map(x=>Math.round(x*10)/10)}
function renderSets(eq=selectedEq()){if(!eq||eq.type!=='strength')return hideSets();if(!sets.length)sets=defaultSets(eq.id);setIndex=Math.min(setIndex,sets.length-1);const b=setBox(),prev=last(eq.id),cur=sets[setIndex];$('#strengthFields').classList.add('v8-hide-core');b.classList.remove('hidden');b.innerHTML=`<div class="v8SetHead"><div><b>每组</b><span>${prev?'上次 '+esc(summary(prev)):'逐组记录重量和次数'}</span></div><div class="v8SetCount"><button data-count8="-1">−</button><b>${sets.length}组</b><button data-count8="1">＋</button></div></div><div class="v8SetRows">${sets.map((s,i)=>`<button class="v8SetRow ${i===setIndex?'active':''} ${s.doneAt?'done':''}" data-set8="${i}"><i>${pad(i+1)}</i><span><b>${fmt(s.weight)}</b><small>kg</small></span><span><b>${s.reps}</b><small>次</small></span><em>${s.doneAt?'✓':'·'}</em></button>`).join('')}</div><div class="v8Adjust"><div><span>重量</span>${around(cur.weight,2.5).map(v=>`<button data-weight8="${v}" class="${Number(v)===Number(cur.weight)?'active':''}">${fmt(v)}</button>`).join('')}</div><div><span>次数</span>${[6,8,10,12,15,cur.reps].filter((v,i,a)=>a.indexOf(v)===i).sort((a,b)=>a-b).map(v=>`<button data-reps8="${v}" class="${Number(v)===Number(cur.reps)?'active':''}">${v}</button>`).join('')}</div></div><button class="v8DoneSet" id="doneSet8">${cur.doneAt?'取消完成':'完成这一组'}</button>`;syncCore()}
function changeCount(d){const n=Math.max(1,Math.min(8,sets.length+d));while(sets.length<n){const x=sets.at(-1)||{weight:20,reps:10};sets.push({weight:x.weight,reps:x.reps,doneAt:null})}while(sets.length>n)sets.pop();setIndex=Math.min(setIndex,n-1);renderSets()}
function timeModel(s){if(!s?.events?.length)return{span:0,effective:0,gap:0,segments:0};const m=meta(),iv=[];for(const e of s.events){if(e.kind==='cardio'){const d=Math.max(1,Number(e.duration)||1)*60000;iv.push([(e.time||Date.now())-d,e.time||Date.now()]);continue}const a=m.events?.[e.id]?.sets||eventSets(e),done=a.map(x=>Number(x.doneAt)||0).filter(Boolean).sort((x,y)=>x-y);if(done.length)iv.push([done[0]-45000,done.at(-1)]);else{const n=Math.max(1,a.length),d=n*45000+Math.max(0,n-1)*90000;iv.push([(e.time||Date.now())-d,e.time||Date.now()])}}iv.sort((a,b)=>a[0]-b[0]);const gaps=[];for(let i=1;i<iv.length;i++){const g=iv[i][0]-iv[i-1][1];if(g>30000&&g<20*60000)gaps.push(g)}const med=median(gaps)||150000,threshold=Math.max(6*60000,Math.min(14*60000,med*2.5)),merged=[];for(const x of iv){const p=merged.at(-1);if(p&&x[0]-p[1]<=threshold)p[1]=Math.max(p[1],x[1]);else merged.push([...x])}const span=Math.max(0,iv.at(-1)[1]-iv[0][0]),effective=merged.reduce((n,x)=>n+Math.max(0,x[1]-x[0]),0);return{span,effective,gap:Math.max(0,span-effective),segments:merged.length}}
function median(a){if(!a.length)return 0;const x=[...a].sort((p,q)=>p-q),i=Math.floor(x.length/2);return x.length%2?x[i]:(x[i-1]+x[i])/2}
function decorate(){const c=core(),active=c.active,m=active?timeModel(active):null;let box=$('#v8Time');if(active){if(!box){box=D.createElement('div');box.id='v8Time';box.className='v8Time';$('#activeHome .metricPair.compact')?.insertAdjacentElement('afterend',box)}const html=`<div><span>跨度</span><b>${min(m.span)}分</b></div><div><span>有效训练</span><b>约${min(m.effective)}分</b></div>${m.gap>=300000?`<div><span>空档</span><b>${min(m.gap)}分</b></div>`:''}${m.segments>1?`<div><span>区段</span><b>${m.segments}</b></div>`:''}`;if(box.innerHTML!==html)box.innerHTML=html}else box?.remove();const a=active?.events||[];$$('#eventList [data-event]').forEach(r=>{const e=a.find(x=>x.id===r.dataset.event);if(!e||e.kind!=='strength')return;const sm=$('small',r),v=summary(e);if(sm&&sm.textContent!==v)sm.textContent=v});for(const r of $$('[data-session]')){const s=(c.sessions||[]).find(x=>x.id===r.dataset.session);if(!s)continue;const t=timeModel(s),sm=$('small',r),v=`${s.events?.length||0}项 · 有效约${min(t.effective)}分 · 跨度${min(t.span)}分`;if(sm&&sm.textContent!==v)sm.textContent=v}if($('#finishSheet')?.classList.contains('show')&&c.sessions?.[0]){const t=timeModel(c.sessions[0]);let f=$('#v8Finish');if(!f){f=D.createElement('div');f.id='v8Finish';f.className='v8Finish';$('.finishStats')?.insertAdjacentElement('beforebegin',f)}f.innerHTML=`<div><span>有效训练</span><b>约 ${min(t.effective)} 分钟</b></div><div><span>训练跨度</span><b>${min(t.span)} 分钟</b></div>${t.gap>=300000?`<div><span>空档</span><b>${min(t.gap)} 分钟</b></div>`:''}`;$('#finishDuration').textContent=`${min(t.span)}分钟`}}
function attachPending(before,n=0){const c=core(),e=(c.active?.events||[]).find(x=>!before.has(x.id));if(e){if(pending&&e.kind==='strength'){const m=meta();m.events=m.events||{};m.events[e.id]={sets:pending.map(x=>({...x})),savedAt:Date.now()};saveMeta(m)}pending=null;decorate();return}if(n<60)setTimeout(()=>attachPending(before,n+1),80)}
function autoStartAndSave(){const e=selectedEq();if(!e)return;pending=e.type==='strength'?sets.map(x=>({...x})):null;if(e.type==='strength')syncCore();const c=core(),before=new Set((c.active?.events||[]).map(x=>x.id));if(!c.active){$('#startBtn')?.click();$('#toast')?.classList.remove('show')}pulse();requestAnimationFrame(()=>{$('#scanSheet')?.classList.remove('show');stopPreview();syncDock()});setTimeout(()=>attachPending(before),0)}
function pulse(){let p=$('#v8Pulse');if(!p){p=D.createElement('div');p.id='v8Pulse';p.className='v8Pulse';D.body.appendChild(p)}p.textContent='已记下';p.classList.add('show');clearTimeout(p._t);p._t=setTimeout(()=>p.classList.remove('show'),900)}function stopPreview(){const s=$('#cameraVideo')?.srcObject;if(s?.getTracks)s.getTracks().forEach(t=>{try{t.stop()}catch{}})}
function showDetail(id){setTimeout(()=>{const e=events().find(x=>x.id===id);if(!e||e.kind!=='strength'||!$('#detail'))return;const a=eventSets(e);let b=$('#v8Detail');if(!b){b=D.createElement('div');b.id='v8Detail';b.className='v8Detail';$('#detail').prepend(b)}b.innerHTML='<span>每组</span>'+a.map((s,i)=>`<div><i>${pad(i+1)}</i><b>${fmt(s.weight)} kg</b><b>${s.reps} 次</b><small>${s.doneAt?new Date(s.doneAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false}):'—'}</small></div>`).join('')},80)}
function wm(){const chip=$('#wmChip'),p=chip?.getAttribute('data-pos')||'bl';$$('#watermarkPreview [data-pos]').forEach(b=>b.dataset.selected=String(b.dataset.pos===p))}
function layerFix(b){if(['profileBtn','myEqBtn','watermarkBtn','storageBtn','reportBtn'].includes(b.id))$('#settingsSheet')?.classList.remove('show');if(b.id==='newCustomEq'||b.matches('[data-edit-eq]'))$('#myEqSheet']?.classList.remove('show')}
function bind(){injectQuick();simplify();syncDock();wm();$('#saveScan')?.addEventListener('click',autoStartAndSave,true);const name=$('#equipmentName');if(name)new MutationObserver(()=>{const e=selectedEq();if(e?.type==='strength')prepareSets(e.id);else hideSets()}).observe(name,{childList:true,subtree:true});D.addEventListener('click',e=>{const b=e.target.closest('button,[data-edit-eq]');if(!b)return;layerFix(b);if(b.dataset.set8!=null){setIndex=Number(b.dataset.set8);renderSets()}else if(b.dataset.count8)changeCount(Number(b.dataset.count8));else if(b.dataset.weight8){sets[setIndex].weight=Number(b.dataset.weight8);renderSets()}else if(b.dataset.reps8){sets[setIndex].reps=Number(b.dataset.reps8);renderSets()}else if(b.id==='doneSet8'){sets[setIndex].doneAt=sets[setIndex].doneAt?null:Date.now();if(sets[setIndex].doneAt){const n=sets.findIndex((x,i)=>i>setIndex&&!x.doneAt);if(n>=0)setIndex=n}renderSets()}else if(b.matches('#eqSheet [data-eq]')&&quickOther){quickOther=false;setTimeout(()=>showEditor(b.dataset.eq),0)}else if(b.id==='saveCustomEq'&&reopenQuick){reopenQuick=false;setTimeout(openQuick,80)}else if(b.matches('[data-event]'))showDetail(b.dataset.event);if(b.closest('#watermarkPreview')&&b.dataset.pos)setTimeout(wm,0);if(b.id==='scanBtn'){setTimeout(()=>{$('#scanSheet')?.classList.remove('v8-quick');$('#captureStage')?.classList.remove('hidden');simplify()},0)}requestAnimationFrame(()=>{syncDock();decorate()})},true);for(const n of $$('.nav button'))n.addEventListener('click',()=>requestAnimationFrame(syncDock));new MutationObserver(()=>decorate()).observe($('#eventList'),{childList:true,subtree:true});new MutationObserver(()=>decorate()).observe($('#historyList'),{childList:true,subtree:true});new MutationObserver(()=>{syncDock();decorate()}).observe(D.body,{subtree:true,attributes:true,attributeFilter:['class']});window.addEventListener('pageshow',()=>{simplify();syncDock();decorate();wm()});decorate()}
if(D.readyState==='loading')D.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();