(()=>{'use strict';
const D=document,$=(s,r=D)=>r.querySelector(s),$$=(s,r=D)=>Array.from(r.querySelectorAll(s));
const CORE='axis_v60_state',META='axis_v8_meta',DB='axis_v42_media';
const CAT=[['cable','多功能龙门架','strength'],['lat','高位下拉','strength'],['row','坐姿 / 胸托划船','strength'],['pec','飞鸟 / 后三角','strength'],['chest','胸推','strength'],['shoulder','肩推','strength'],['dip','双杠 / 抬腿','strength'],['arms','手臂','strength'],['legpress','坐姿腿推','strength'],['hack','哈克 / 斜腿推','strength'],['legext','腿屈伸','strength'],['legcurl','腿弯举','strength'],['calf','小腿','strength'],['dumbbell','哑铃','strength'],['barbell','杠铃','strength'],['bodyweight','徒手','strength'],['elliptical','椭圆机','cardio'],['rower','划船机','cardio'],['treadmill','跑步机 / 跑步','cardio'],['walk','步行','cardio']];
let draft=[],sel=0,pending=null,quickOther=false,statusTouched=false,deferOnce=false,editingId=null,undoTimer=null;
function core(){try{return JSON.parse(localStorage.getItem(CORE)||'null')||{version:60,sessions:[],active:null,profile:{customEq:[]}}}catch{return{version:60,sessions:[],active:null,profile:{customEq:[]}}}}
function writeCore(c){try{localStorage.setItem(CORE,JSON.stringify(c));return true}catch{return false}}
function mread(){try{const m=JSON.parse(localStorage.getItem(META)||'null')||{};return{events:m.events||{},prefs:m.prefs||{}}}catch{return{events:{},prefs:{}}}}
function msave(m){try{localStorage.setItem(META,JSON.stringify(m));return true}catch{return false}}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmt(n){if(n==null||n==='')return'—';n=Number(n);if(!Number.isFinite(n))return'—';return n%1?n.toFixed(1):String(n)}
function pad(n){return String(n).padStart(2,'0')}
function mins(ms){return Math.max(0,Math.round((Number(ms)||0)/60000))}
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(e._v81t);e._v81t=setTimeout(()=>e.classList.remove('show'),1500)}
function sessions(c=core()){return (c.active?[c.active]:[]).concat(c.sessions||[])}
function allEvents(){return sessions().flatMap(s=>Array.isArray(s.events)?s.events:[])}
function last(id,excludeId=null){return allEvents().filter(e=>e.equipmentId===id&&e.id!==excludeId).sort((a,b)=>(b.time||0)-(a.time||0))[0]||null}
function normalizeSavedSet(s,legacyDone=true){return{weight:s?.weight==null?null:Number(s.weight),reps:s?.reps==null?null:Number(s.reps),state:s?.state||(s?.doneAt?'done':legacyDone?'done':'assumed'),doneAt:Number(s?.doneAt)||null,inferred:!!s?.inferred}}
function setsOf(e){const rec=mread().events?.[e?.id],a=rec?.sets;if(Array.isArray(a)&&a.length)return a.map(s=>normalizeSavedSet(s,true));const n=Math.max(1,Number(e?.sets)||1),w=Number.isFinite(Number(e?.weight))?Number(e.weight):null,r=Number.isFinite(Number(e?.reps))?Number(e.reps):null;return Array.from({length:n},()=>({weight:w,reps:r,state:'done',doneAt:null,inferred:true}))}
function performedSets(e){return setsOf(e).filter(s=>s.state!=='unfinished')}
function summary(e){if(!e)return'';if(e.kind==='cardio')return`${e.duration||0}分钟 · 强度${e.intensity||0}`;const all=setsOf(e),done=all.filter(s=>s.state!=='unfinished'),weights=[...new Set(done.map(s=>fmt(s.weight)))],reps=done.map(s=>fmt(s.reps)),base=`${weights.length===1?weights[0]+'kg':weights.length?'分组重量':'重量—'} · ${reps.length?reps.join(' / '):'次数—'}`;const incomplete=done.length<all.length?` · ${done.length}/${all.length}组`:'';const review=mread().events?.[e.id]?.needsReview?' · 待补':'';return base+incomplete+review}
function selected(){const n=$('#equipmentName')?.textContent?.trim();if(!n||n==='待确认')return null;const hist=allEvents().find(x=>x.name===n);if(hist)return{id:hist.equipmentId,name:hist.name,type:hist.kind};const c=core(),custom=c.profile?.customEq||[],ce=custom.find(x=>x.name===n);if(ce)return{id:ce.id,name:ce.name,type:ce.type};const x=CAT.find(q=>q[1]===n);if(x)return{id:x[0],name:x[1],type:x[2]};return{id:null,name:n,type:$('#cardioFields')?.classList.contains('hidden')?'strength':'cardio'}}
function syncDock(){const today=$('#todayView')?.classList.contains('active'),sheet=$$('.sheetWrap.show').some(x=>x.id!=='finishSheet');const d=$('#dock');if(!d)return;d.classList.toggle('show',!!today&&!sheet);d.classList.toggle('v8-force',!!today&&!sheet)}
function basic(){const lead=$('#idleHome .sessionLead');if(lead)lead.classList.add('v8-hide-start');const scan=$('#scanBtn span');if(scan)scan.textContent='拍摄记录';const h=$('#scanSheet .sheetHead>b');if(h&&!$('#scanSheet')?.classList.contains('v8-quick'))h.textContent='拍摄记录';$$('#captureModes [data-mode]').forEach(b=>b.textContent=b.dataset.mode==='photo'?'单张':`${b.dataset.mode}秒`);if($('.versionLine'))$('.versionLine').textContent='版本 8.1'}
function injectQuick(){if($('#quickRecordBtn'))return;const d=$('#dock');if(!d)return;d.classList.add('v8-dual');d.insertAdjacentHTML('beforeend','<button id="quickRecordBtn" class="v8QuickBtn"><span>＋</span><b>快速记录</b></button>');D.body.insertAdjacentHTML('beforeend','<div class="sheetWrap" id="quickRecordSheet"><div class="sheet v8QuickSheet"><div class="grabber"></div><div class="sheetHead"><b>快速记录</b><button class="closeBtn" id="quickClose">×</button></div><div class="v8Block"><span>最近</span><div id="v8Recent"></div></div><button class="v8Other" id="v8Other">其他器械 / 运动 <i>›</i></button><button class="v8New" id="v8New">＋ 新建自定义</button></div></div>');$('#quickRecordBtn').onclick=openQuick;$('#quickClose').onclick=()=>{$('#quickRecordSheet').classList.remove('show');syncDock()};$('#v8Recent').onclick=e=>{const b=e.target.closest('[data-qid]');if(b)chooseQuick(b.dataset.qid)};$('#v8Other').onclick=()=>{quickOther=true;$('#quickRecordSheet').classList.remove('show');$('#equipmentRow')?.click()};$('#v8New').onclick=()=>{$('#quickRecordSheet').classList.remove('show');$('#addCustomEq')?.click()}}
function recentDistinct(limit=5){const out=[],seen=new Set();for(const e of allEvents().sort((a,b)=>(b.time||0)-(a.time||0))){if(!e.equipmentId||seen.has(e.equipmentId))continue;seen.add(e.equipmentId);out.push(e);if(out.length>=limit)break}return out}
function openQuick(){let items=recentDistinct(5).map(e=>({id:e.equipmentId,name:e.name,meta:summary(e),today:!!core().active?.events?.some(x=>x.id===e.id)}));if(!items.length)items=CAT.slice(0,6).map(x=>({id:x[0],name:x[1],meta:x[2]==='cardio'?'有氧':'力量'}));$('#v8Recent').innerHTML=items.map(x=>`<button class="v8QuickItem" data-qid="${x.id}"><span><b>${esc(x.name)}</b><small>${x.today?'继续 · ':''}${esc(x.meta)}</small></span><i>›</i></button>`).join('');$('#quickRecordSheet').classList.add('show');syncDock()}
function chooseQuick(id){$('#quickRecordSheet')?.classList.remove('show');$('#equipmentRow')?.click();setTimeout(()=>{const b=$$('#eqSheet [data-eq]').find(x=>x.dataset.eq===id);if(b){b.click();setTimeout(()=>showQuickEditor(id),0)}},0)}
function showQuickEditor(id){const s=$('#scanSheet');if(!s)return;s.classList.add('show','v8-quick');$('#captureStage')?.classList.add('hidden');$('#reviewStage')?.classList.remove('hidden');if($('#film'))$('#film').innerHTML='';const h=$('#scanSheet .sheetHead>b');if(h)h.textContent=editingId?'补一下':'快速记录';const e=selected();if(e?.type==='strength')prepare(id||e.id);syncDock()}
function prepare(id){const prev=last(id,editingId);if(editingId){const target=allEvents().find(e=>e.id===editingId),saved=mread().events?.[editingId]?.sets;if(target&&Array.isArray(saved)&&saved.length)draft=saved.map(s=>({...normalizeSavedSet(s,true)}));else if(target)draft=setsOf(target).map(s=>({...s}))}else if(prev?.kind==='strength')draft=setsOf(prev).map(s=>({weight:s.weight,reps:s.reps,state:'assumed',doneAt:null,inferred:true}));else{const w=Number($('#weight')?.value)||20,r=Number($('#repsChoices .active')?.dataset.value)||10,n=1;draft=Array.from({length:n},()=>({weight:w,reps:r,state:'assumed',doneAt:null,inferred:true}))}if(!draft.length)draft=[{weight:20,reps:10,state:'assumed',doneAt:null,inferred:true}];sel=0;statusTouched=false;renderSets()}
function deltaText(s,i,prev){if(s.state==='unfinished')return'未完成';const p=prev[i];if(!p)return s.state==='done'?'完成':'新';if(s.weight==null||s.reps==null)return'待补';const dw=Number(s.weight)-Number(p.weight||0),dr=Number(s.reps)-Number(p.reps||0);if(Math.abs(dw)>.01)return`${dw>0?'+':''}${fmt(dw)}kg`;if(dr)return`${dr>0?'+':''}${dr}次`;return s.state==='done'?'完成':'同上次'}
function renderSets(){const e=selected();if(!e||e.type!=='strength'){hideSets();return}if(!draft.length)prepare(e.id);let box=$('#v8Sets');if(!box){box=D.createElement('div');box.id='v8Sets';box.className='v8Sets';$('#strengthFields')?.insertAdjacentElement('beforebegin',box)}$('#strengthFields')?.classList.add('v8-hide-core');box.classList.remove('hidden');sel=Math.min(sel,draft.length-1);const c=draft[sel],prevEvent=last(e.id,editingId),prev=prevEvent?setsOf(prevEvent):[],w=Number(c.weight)||0,wopts=[null,w-2.5,w,w+2.5].filter(x=>x==null||x>=0).filter((x,i,a)=>a.findIndex(y=>y===x)===i),ropts=[null,6,8,10,12,15,c.reps].filter((x,i,a)=>a.findIndex(y=>y===x)===i).sort((a,b)=>(a==null?-1:b==null?1:a-b));box.innerHTML=`<div class="v8SetHead"><div><b>每组</b><span>${prevEvent?'沿用上次 · 有变化再改':'记得多少就记多少'}</span></div><div class="v8SetCount"><button data-cnt="-1">−</button><b>${draft.length}组</b><button data-cnt="1">＋</button></div></div>${prevEvent?'<button class="v81Reset" id="resetPrevious8">恢复上次</button>':''}<div class="v8SetRows">${draft.map((s,i)=>`<button class="v8SetRow ${i===sel?'active':''} ${s.state==='done'?'done':''} ${s.state==='unfinished'?'unfinished':''}" data-si="${i}"><i>${pad(i+1)}</i><span><b>${fmt(s.weight)}</b><small>kg</small></span><span><b>${fmt(s.reps)}</b><small>次</small></span><em>${esc(deltaText(s,i,prev))}</em></button>`).join('')}</div><div class="v8Adjust"><div><span>重量</span>${wopts.map(v=>`<button data-w="${v==null?'unknown':v}" class="${v==null?c.weight==null:Number(v)===Number(c.weight)?'active':''}">${v==null?'—':fmt(v)}</button>`).join('')}</div><div><span>次数</span>${ropts.map(v=>`<button data-r="${v==null?'unknown':v}" class="${v==null?c.reps==null:Number(v)===Number(c.reps)?'active':''}">${v==null?'—':v}</button>`).join('')}</div></div><div class="v81SetActions"><button id="doneSet8" class="v8DoneSet">${c.state==='done'?'已完成':'完成这一组'}</button><button id="skipSet8" class="v81SkipSet">${c.state==='unfinished'?'恢复这组':'这组没做'}</button></div><button id="saveLater8" class="v81Later">先记下，稍后补</button>`;syncHidden(draft)}
function hideSets(){$('#v8Sets')?.classList.add('hidden');$('#strengthFields')?.classList.remove('v8-hide-core')}
function syncHidden(arr=draft){if(!arr.length)return;const usable=arr.filter(s=>s.state!=='unfinished'),knownW=usable.map(s=>s.weight).filter(v=>v!=null&&Number.isFinite(Number(v))),knownR=usable.map(s=>s.reps).filter(v=>v!=null&&Number.isFinite(Number(v)));if($('#weight'))$('#weight').value=knownW.length?Math.max(...knownW.map(Number)):0;const reps=knownR.length?Number(knownR[0]):1,n=Math.max(1,usable.length);let rb=$(`#repsChoices [data-value="${reps}"]`);if(!rb){$('#repsChoices')?.insertAdjacentHTML('beforeend',`<button data-choice="reps" data-value="${reps}">${reps}</button>`);rb=$(`#repsChoices [data-value="${reps}"]`)}rb?.click();let sb=$(`#setsChoices [data-value="${n}"]`);if(!sb){$('#setsChoices')?.insertAdjacentHTML('beforeend',`<button data-choice="sets" data-value="${n}">${n}</button>`);sb=$(`#setsChoices [data-value="${n}"]`)}sb?.click()}
function changeCount(d){const n=Math.max(1,Math.min(10,draft.length+d));while(draft.length<n){const x=draft.at(-1)||{weight:20,reps:10,state:'assumed',doneAt:null};draft.push({weight:x.weight,reps:x.reps,state:'assumed',doneAt:null,inferred:true})}while(draft.length>n)draft.pop();sel=Math.min(sel,n-1);renderSets()}
function resetPrevious(){const e=selected(),p=e?last(e.id,editingId):null;if(!p)return;draft=setsOf(p).map(s=>({weight:s.weight,reps:s.reps,state:'assumed',doneAt:null,inferred:true}));sel=0;statusTouched=false;renderSets()}
function finalizedDraft(needsReview=false){const now=Date.now();return draft.map((s,i)=>{let state=s.state;if(needsReview){if(state!=='unfinished')state='done'}else if(!statusTouched&&state==='assumed')state='done';else if(statusTouched&&state==='assumed')state='unfinished';return{weight:s.weight==null?null:Number(s.weight),reps:s.reps==null?null:Number(s.reps),state,doneAt:state==='done'?(s.doneAt||null):null,inferred:(state==='done'&&!s.doneAt)||!!s.inferred,order:i}}).map(s=>({...s,doneAt:s.doneAt||((needsReview&&s.state==='done')?now:null)}))}
function onSaveClick(ev){const e=selected();if(!e)return;if(editingId){ev.preventDefault();ev.stopImmediatePropagation();finishEditing();return}if(e.type==='strength'){const final=finalizedDraft(deferOnce),performed=final.filter(s=>s.state!=='unfinished');if(!performed.length){ev.preventDefault();ev.stopImmediatePropagation();toast('至少保留一组已完成');deferOnce=false;return}pending={sets:final,needsReview:deferOnce||performed.some(s=>s.weight==null||s.reps==null),inheritedFrom:last(e.id)?.id||null};syncHidden(final)}else pending={sets:null,needsReview:false,inheritedFrom:last(e.id)?.id||null};const c=core(),before=new Set((c.active?.events||[]).map(x=>x.id));if(!c.active){$('#startBtn')?.click();$('#toast')?.classList.remove('show')}pulseSaving();setTimeout(()=>attach(before),0)}
function attach(before,n=0){const c=core(),e=(c.active?.events||[]).find(x=>!before.has(x.id));if(e){const m=mread();m.events=m.events||{};m.events[e.id]={...(m.events[e.id]||{}),sets:pending?.sets||m.events[e.id]?.sets||null,needsReview:!!pending?.needsReview,inheritedFrom:pending?.inheritedFrom||null,savedAt:Date.now()};msave(m);pending=null;deferOnce=false;showUndo(e);decorate();renderContinue();renderPending();return}if(n<200)setTimeout(()=>attach(before,n+1),100);else{pending=null;deferOnce=false}}
function pulseSaving(){let p=$('#v8Pulse');if(!p){p=D.createElement('div');p.id='v8Pulse';p.className='v8Pulse';D.body.appendChild(p)}p.textContent='正在记下';p.classList.add('show');clearTimeout(p._t);p._t=setTimeout(()=>p.classList.remove('show'),1200)}
function showUndo(e){let bar=$('#v81Undo');if(!bar){bar=D.createElement('div');bar.id='v81Undo';bar.className='v81Undo';bar.innerHTML='<span>已记下</span><button>撤销</button>';D.body.appendChild(bar);bar.querySelector('button').onclick=()=>undoEvent(bar.dataset.event)}bar.dataset.event=e.id;bar.classList.add('show');clearTimeout(undoTimer);undoTimer=setTimeout(()=>bar.classList.remove('show'),5000)}
async function deleteMediaKey(key){if(!key||!indexedDB)return;try{const db=await new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)});await new Promise((res,rej)=>{const tx=db.transaction('media','readwrite');tx.objectStore('media').delete(key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close()}catch{}}
async function undoEvent(id){if(!id)return;const c=core();let target=null;if(c.active?.events){const i=c.active.events.findIndex(e=>e.id===id);if(i>=0){target=c.active.events[i];c.active.events.splice(i,1);if(!c.active.events.length)c.active=null}}if(!target){for(const s of c.sessions||[]){const i=(s.events||[]).findIndex(e=>e.id===id);if(i>=0){target=s.events[i];s.events.splice(i,1);break}}}if(!target)return;writeCore(c);const m=mread();delete m.events[id];msave(m);for(const r of target.frameRefs||[])await deleteMediaKey(r);if(target.clipRef)await deleteMediaKey(target.clipRef);location.reload()}
function finishEditing(){const c=core(),event=sessions(c).flatMap(s=>s.events||[]).find(e=>e.id===editingId);if(!event){editingId=null;return}const final=finalizedDraft(false),done=final.filter(s=>s.state!=='unfinished');if(!done.length)return toast('至少保留一组已完成');event.sets=done.length;const knownW=done.map(s=>s.weight).filter(v=>v!=null),knownR=done.map(s=>s.reps).filter(v=>v!=null);event.weight=knownW.length?Math.max(...knownW):0;event.reps=knownR.length?knownR[0]:1;writeCore(c);const m=mread();m.events[editingId]={...(m.events[editingId]||{}),sets:final,needsReview:done.some(s=>s.weight==null||s.reps==null),savedAt:Date.now()};msave(m);editingId=null;toast('已补好');setTimeout(()=>location.reload(),120)}
function injectPending(){if($('#v81PendingSheet'))return;D.body.insertAdjacentHTML('beforeend','<div class="sheetWrap" id="v81PendingSheet"><div class="sheet v81PendingSheet"><div class="grabber"></div><div class="sheetHead"><b>待补记录</b><button class="closeBtn" id="v81PendingClose">×</button></div><div id="v81PendingList"></div></div></div>');$('#v81PendingClose').onclick=()=>{$('#v81PendingSheet').classList.remove('show');syncDock()};$('#v81PendingList').onclick=e=>{const b=e.target.closest('[data-pending-id]');if(b)editPending(b.dataset.pendingId)}}
function pendingEvents(){const m=mread();return allEvents().filter(e=>m.events?.[e.id]?.needsReview)}
function renderPending(){injectPending();const list=pendingEvents();let btn=$('#v81PendingBtn');const host=core().active?$('#activeHome'):$('#idleHome');if(!host)return;if(!btn){btn=D.createElement('button');btn.id='v81PendingBtn';btn.className='v81PendingBtn';btn.onclick=()=>{renderPendingList();$('#v81PendingSheet').classList.add('show');syncDock()};host.prepend(btn)}else if(btn.parentNode!==host)host.prepend(btn);btn.classList.toggle('hidden',!list.length);btn.innerHTML=list.length?`<span>待补</span><b>${list.length} 条记录</b><i>›</i>`:''}
function renderPendingList(){const list=pendingEvents();$('#v81PendingList').innerHTML=list.length?list.map(e=>`<button class="v81PendingRow" data-pending-id="${e.id}"><span><b>${esc(e.name)}</b><small>${esc(summary(e))}</small></span><i>补一下</i></button>`).join(''):'<div class="empty">暂无待补记录</div>'}
function editPending(id){const e=allEvents().find(x=>x.id===id);if(!e)return;editingId=id;$('#v81PendingSheet').classList.remove('show');$('#equipmentRow')?.click();setTimeout(()=>{const b=$$('#eqSheet [data-eq]').find(x=>x.dataset.eq===e.equipmentId);if(b){b.click();setTimeout(()=>showQuickEditor(e.equipmentId),0)}else{editingId=null;toast('请先确认器械')}},0)}
function renderContinue(){const host=$('#idleHome');if(!host)return;let box=$('#v81Continue');const items=recentDistinct(3);if(!box){box=D.createElement('div');box.id='v81Continue';box.className='v81Continue';host.querySelector('.metricPair')?.insertAdjacentElement('beforebegin',box)}box.classList.toggle('hidden',!items.length);box.innerHTML=items.length?`<div class="v81ContinueHead"><b>接着上次</b><span>只改变化</span></div>${items.map(e=>`<button data-continue-id="${e.equipmentId}"><span><b>${esc(e.name)}</b><small>${esc(summary(e))}</small></span><i>›</i></button>`).join('')}`:'';box.onclick=e=>{const b=e.target.closest('[data-continue-id]');if(b)chooseQuick(b.dataset.continueId)};host.querySelector('.metricPair')?.classList.add('v81Secondary')}
function median(a){if(!a.length)return 0;const x=[...a].sort((p,q)=>p-q),i=Math.floor(x.length/2);return x.length%2?x[i]:(x[i-1]+x[i])/2}
function timeModel(s){if(!s?.events?.length)return{span:0,effective:0,gap:0,segments:0,lastEnd:0};const m=mread(),iv=[];for(const e of s.events){if(e.kind==='cardio'){const d=Math.max(1,Number(e.duration)||1)*60000,et=e.time||Date.now();iv.push([et-d,et]);continue}const a=(m.events?.[e.id]?.sets||setsOf(e)).map(x=>normalizeSavedSet(x,true)).filter(x=>x.state!=='unfinished'),done=a.map(x=>Number(x.doneAt)||0).filter(Boolean).sort((x,y)=>x-y);if(done.length)iv.push([done[0]-45000,done.at(-1)]);else{const n=Math.max(1,a.length),d=n*45000+Math.max(0,n-1)*90000,et=e.time||Date.now();iv.push([et-d,et])}}if(!iv.length)return{span:0,effective:0,gap:0,segments:0,lastEnd:0};iv.sort((a,b)=>a[0]-b[0]);const gs=[];for(let i=1;i<iv.length;i++){const g=iv[i][0]-iv[i-1][1];if(g>30000&&g<1200000)gs.push(g)}const th=Math.max(360000,Math.min(840000,(median(gs)||150000)*2.5)),merged=[];for(const x of iv){const p=merged.at(-1);if(p&&x[0]-p[1]<=th)p[1]=Math.max(p[1],x[1]);else merged.push([...x])}const span=Math.max(0,iv.at(-1)[1]-iv[0][0]),effective=merged.reduce((n,x)=>n+Math.max(0,x[1]-x[0]),0);return{span,effective,gap:Math.max(0,span-effective),segments:merged.length,lastEnd:iv.at(-1)[1]}}
function completedCount(ss){return (ss||[]).flatMap(s=>s.events||[]).reduce((n,e)=>n+(e.kind==='strength'?performedSets(e).length:1),0)}
function decorate(){const c=core();if(c.active){const t=timeModel(c.active);let b=$('#v8Time');if(!b){b=D.createElement('div');b.id='v8Time';b.className='v8Time';$('#activeHome .metricPair.compact')?.insertAdjacentElement('afterend',b)}const h=`<div><span>跨度</span><b>${mins(t.span)}分</b></div><div><span>有效训练</span><b>约${mins(t.effective)}分</b></div>${t.gap>=300000?`<div><span>空档</span><b>${mins(t.gap)}分</b></div>`:''}${t.segments>1?`<div><span>区段</span><b>${t.segments}</b></div>`:''}`;if(b.innerHTML!==h)b.innerHTML=h;if($('#liveSets'))$('#liveSets').textContent=completedCount([c.active])}else $('#v8Time')?.remove();for(const r of $$('#eventList [data-event]')){const e=(c.active?.events||[]).find(x=>x.id===r.dataset.event);if(e?.kind==='strength'){const sm=$('small',r),v=summary(e);if(sm&&sm.textContent!==v)sm.textContent=v}}for(const r of $$('[data-session]')){const s=(c.sessions||[]).find(x=>x.id===r.dataset.session);if(!s)continue;const t=timeModel(s),sm=$('small',r),v=`${s.events?.length||0}项 · 有效约${mins(t.effective)}分 · 跨度${mins(t.span)}分`;if(sm&&sm.textContent!==v)sm.textContent=v}if($('#finishSheet')?.classList.contains('show')&&c.sessions?.[0]){const s=c.sessions[0],t=timeModel(s);$('#finishDuration').textContent=`${mins(t.span)}分钟`;if($('#finishSets'))$('#finishSets').textContent=completedCount([s]);let f=$('#v8Finish');if(!f){f=D.createElement('div');f.id='v8Finish';f.className='v8Finish';$('.finishStats')?.insertAdjacentElement('beforebegin',f)}f.innerHTML=`<div><span>有效训练</span><b>约 ${mins(t.effective)} 分钟</b></div><div><span>训练跨度</span><b>${mins(t.span)} 分钟</b></div>${t.gap>=300000?`<div><span>空档</span><b>${mins(t.gap)} 分钟</b></div>`:''}`}}
function staleCheck(){const c=core(),a=c.active;if(!a?.events?.length)return removeStale();const m=mread();if((m.prefs?.staleIgnoreUntil||0)>Date.now())return removeStale();const t=timeModel(a),idle=Date.now()-(t.lastEnd||a.events.at(-1)?.time||Date.now());if(idle<120*60000)return removeStale();let box=$('#v81Stale');if(!box){box=D.createElement('div');box.id='v81Stale';box.className='v81Stale';box.innerHTML='<span><b>上次训练可能已结束</b><small>最后有效记录已经过去很久</small></span><div><button id="v81CloseStale">按最后记录结束</button><button id="v81KeepStale">继续</button></div>';$('#activeHome')?.prepend(box);$('#v81CloseStale').onclick=closeStale;$('#v81KeepStale').onclick=()=>{const mm=mread();mm.prefs.staleIgnoreUntil=Date.now()+2*3600000;msave(mm);removeStale()}}box.classList.remove('hidden')}
function removeStale(){$('#v81Stale')?.classList.add('hidden')}
function closeStale(){const c=core(),a=c.active;if(!a)return;const t=timeModel(a);a.end=t.lastEnd||a.events.at(-1)?.time||Date.now();c.sessions=c.sessions||[];c.sessions.unshift(a);c.active=null;writeCore(c);location.reload()}
function bind(){injectQuick();injectPending();basic();renderContinue();renderPending();syncDock();decorate();staleCheck();$('#saveScan')?.addEventListener('click',onSaveClick,true);const nm=$('#equipmentName');if(nm)new MutationObserver(()=>{const e=selected();if(e?.type==='strength')prepare(e.id);else hideSets()}).observe(nm,{childList:true,subtree:true});D.addEventListener('click',e=>{const b=e.target.closest('button,[data-edit-eq]');if(!b)return;if(['profileBtn','myEqBtn','watermarkBtn','storageBtn','reportBtn'].includes(b.id))$('#settingsSheet')?.classList.remove('show');if(b.dataset.si!=null){sel=Number(b.dataset.si);renderSets()}else if(b.dataset.cnt)changeCount(Number(b.dataset.cnt));else if(b.dataset.w){draft[sel].weight=b.dataset.w==='unknown'?null:Number(b.dataset.w);renderSets()}else if(b.dataset.r){draft[sel].reps=b.dataset.r==='unknown'?null:Number(b.dataset.r);renderSets()}else if(b.id==='doneSet8'){statusTouched=true;draft[sel].state='done';draft[sel].doneAt=draft[sel].doneAt||Date.now();const n=draft.findIndex((x,i)=>i>sel&&x.state!=='done');if(n>=0)sel=n;renderSets()}else if(b.id==='skipSet8'){statusTouched=true;draft[sel].state=draft[sel].state==='unfinished'?'assumed':'unfinished';draft[sel].doneAt=null;renderSets()}else if(b.id==='resetPrevious8')resetPrevious();else if(b.id==='saveLater8'){deferOnce=true;$('#saveScan')?.click()}else if(b.matches('#eqSheet [data-eq]')&&quickOther){quickOther=false;setTimeout(()=>showQuickEditor(b.dataset.eq),0)}if(b.id==='scanBtn')setTimeout(()=>{$('#scanSheet')?.classList.remove('v8-quick');$('#captureStage')?.classList.remove('hidden');editingId=null;basic()},0);requestAnimationFrame(()=>{syncDock();decorate();renderPending()})},true);new MutationObserver(()=>{decorate();renderContinue();renderPending()}).observe($('#eventList'),{childList:true,subtree:true});new MutationObserver(()=>{decorate();renderContinue();renderPending()}).observe($('#historyList'),{childList:true,subtree:true});new MutationObserver(()=>{syncDock();decorate()}).observe(D.body,{subtree:true,attributes:true,attributeFilter:['class']});window.addEventListener('pageshow',()=>{basic();syncDock();decorate();renderContinue();renderPending();staleCheck()});D.addEventListener('visibilitychange',()=>{if(!D.hidden)staleCheck()})}
if(D.readyState==='loading')D.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();