(()=>{'use strict';
const D=document,CORE='axis_v60_state',META='axis_v8_meta',$=s=>D.querySelector(s);let h=null,raf=0;
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}},now=()=>Date.now(),pad=n=>String(n).padStart(2,'0'),clock=ms=>{ms=Math.max(0,Number(ms)||0);const q=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000);return q?`${q}:${pad(m)}:${pad(s)}`:`${pad(m)}:${pad(s)}`},signed=ms=>(ms>0?'+':ms<0?'−':'±')+clock(Math.abs(ms));
function close(a,t){const x=a?.intervals?.at(-1);if(x&&!x.end)x.end=t}function elapsed(a,t){return(a?.intervals||[]).reduce((n,x)=>n+Math.max(0,(x.end||((a.status==='active')?t:x.start))-x.start),0)}
function finish(id){const c=read(CORE,{active:null,sessions:[]}),m=read(META,{events:{},prefs:{}});m.events=m.events||{};const e=c.active?.events?.find(x=>x.id===id),a=m.events?.[id]?.activity;if(!e||!a)return;const t=now();if(a.status==='active')close(a,t);a.status='finished';a.finishedAt=t;a.actualMs=elapsed(a,t);a.comparisonMs=a.actualMs-(a.estimateMs||a.actualMs);a.restStartedAt=null;const sets=m.events?.[id]?.sets,used=(a.setDoneAt||[]).some(Boolean),done=Math.max(0,Number(a.completedSets)||0);if(Array.isArray(sets)&&used){sets.forEach((s,i)=>{if(i<done){s.state='done';s.doneAt=a.setDoneAt[i]||s.doneAt||null}else{s.state='unfinished';s.doneAt=null}});e.sets=Math.max(1,done)}write(META,m);write(CORE,c);const flash=$('#v86Flash'),est=a.estimateMs||a.actualMs;if(flash){flash.innerHTML=`<span>已完成</span><b>${String(e.name||'项目')}</b><div><em><span>实际</span><b>${clock(a.actualMs)}</b></em><em><span>预计</span><b>${clock(est)}</b></em><em><span>差异</span><b>${signed(a.actualMs-est)}</b></em></div>`;flash.classList.add('show');clearTimeout(flash._t);flash._t=setTimeout(()=>flash.classList.remove('show'),1900)}try{navigator.vibrate?.(22)}catch{}window.dispatchEvent(new Event('pageshow'))}
function clear(delay=0){if(raf)cancelAnimationFrame(raf);raf=0;if(h?.b)h.b.style.setProperty('--p','0deg');h=null;setTimeout(()=>{$('#v86Hold')?.classList.remove('show');$('#v86HoldRing')?.style.setProperty('--p','0deg');if($('#v86HoldAxis'))$('#v86HoldAxis').style.width='0'},delay)}
function begin(b,e){clear();h={b,id:b.dataset.v86Finish,start:performance.now(),x:e.clientX,y:e.clientY};$('#v86Hold')?.classList.add('show');const step=t=>{if(!h)return;const p=Math.min(1,(t-h.start)/1380);h.b.style.setProperty('--p',`${p*360}deg`);$('#v86HoldRing')?.style.setProperty('--p',`${p*360}deg`);if($('#v86HoldAxis'))$('#v86HoldAxis').style.width=`${Math.max(0,(p-.16)/.84)*74}%`;if(p<1)raf=requestAnimationFrame(step);else{const id=h.id;clear(120);finish(id)}};raf=requestAnimationFrame(step)}
window.addEventListener('pointerdown',e=>{const b=e.target.closest?.('[data-v86-finish]');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();b.setPointerCapture?.(e.pointerId);begin(b,e)},true);
window.addEventListener('pointermove',e=>{if(!h)return;if(Math.hypot(e.clientX-h.x,e.clientY-h.y)>44)clear()},true);
for(const type of ['pointerup','pointercancel'])window.addEventListener(type,()=>{if(h)clear()},true);
})();