(()=>{'use strict';
const D=document,$=(s,r=D)=>r.querySelector(s),CORE='axis_v60_state';let range='last',card=0;
const read=()=>{try{const c=JSON.parse(localStorage.getItem(CORE)||'null')||{};c.sessions=c.sessions||[];c.profile=c.profile||{};return c}catch{return{sessions:[],profile:{}}}},esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m])),pad=n=>String(n).padStart(2,'0');
function style(){if($('#v8710ReportStyle'))return;const s=D.createElement('style');s.id='v8710ReportStyle';s.textContent=`
#reportPreview,#v877ReportDeck,#v877ReportDots,#v877ReportHint{display:none!important}
#reportSheet .sheet{overflow-x:hidden!important}
.v8710ReportDeck{display:flex;gap:12px;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none;margin:14px 0 8px;padding:0;overscroll-behavior-x:contain}
.v8710ReportDeck::-webkit-scrollbar{display:none}
.v8710Plate{flex:0 0 100%;width:100%;aspect-ratio:4/5;border-radius:24px;background:#eeede8;color:#0b0d10;scroll-snap-align:start;overflow:hidden;position:relative;padding:30px;display:flex;flex-direction:column;box-sizing:border-box;font-family:-apple-system,BlinkMacSystemFont,'PingFang SC',sans-serif}
.v8710Plate .t{font-size:15px;line-height:1.35;color:#747980}.v8710Plate .d{font-size:22px;line-height:1.16;font-weight:680;letter-spacing:-.025em;color:#0b0d10}
.v8710PlateHead{display:flex;justify-content:space-between;align-items:flex-start;gap:18px;min-height:64px}.v8710PlateMeta{display:grid;gap:7px}.v8710PlateMeta .brand{color:#0b0d10;font-weight:650}
.v8710Glyph{width:58px;height:58px;display:grid;grid-template-columns:repeat(4,1fr);grid-template-rows:repeat(4,1fr);gap:3px;transform:rotate(var(--rot,0deg));flex:0 0 auto}.v8710Glyph i{background:#0b0d10;border-radius:2px;opacity:.13}.v8710Glyph i.on{background:#737cff;opacity:1}
.v8710Rule{height:3px;width:52px;background:#737cff;border-radius:9px;margin:24px 0 26px}.v8710Names{max-width:92%;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}
.v8710Bars{height:220px;display:flex;align-items:flex-end;gap:8px;margin-top:30px;overflow:hidden}.v8710Bars i{flex:1;min-width:4px;max-width:54px;background:#0b0d10;border-radius:6px 6px 1px 1px}.v8710Bars i.hot{background:#737cff}
.v8710Grid{display:grid;grid-template-columns:repeat(5,1fr);gap:7px;margin-top:30px;max-width:100%}.v8710Grid i{aspect-ratio:1;border-radius:10px;background:rgba(11,13,16,.075)}.v8710Grid i.on{background:#0b0d10}.v8710Grid i.hot{background:#737cff}
.v8710Focus{margin-top:28px;display:flex;gap:8px;flex-wrap:wrap}.v8710Focus span{height:38px;padding:0 13px;border-radius:12px;background:rgba(11,13,16,.07);display:flex;align-items:center;font-size:15px;color:#0b0d10;max-width:100%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.v8710Trace{margin-top:44px;display:grid;grid-template-columns:repeat(9,minmax(0,1fr));align-items:center;gap:7px}.v8710Trace i{height:10px;border-radius:99px;background:rgba(11,13,16,.09)}.v8710Trace i.on{background:#0b0d10}.v8710Trace i.hot{background:#737cff}
.v8710RhythmStats{margin-top:34px;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.v8710RhythmStats div{padding-top:14px;border-top:1px solid rgba(11,13,16,.12);min-width:0}.v8710RhythmStats b,.v8710RhythmStats span{display:block}.v8710RhythmStats span{margin-top:7px}
.v8710Foot{margin-top:auto;padding-top:18px;border-top:1px solid rgba(11,13,16,.11);display:flex;align-items:flex-end;justify-content:space-between;gap:18px}.v8710Foot>*{min-width:0}.v8710Foot .right{text-align:right}
.v8710Share{width:100%;height:60px;margin-top:12px;border-radius:18px;background:var(--text);color:#0b0d10;font-size:var(--axis-ui,15px);font-weight:720}
@media(max-width:390px){.v8710Plate{padding:26px}.v8710Bars{height:200px}.v8710Grid{gap:6px}.v8710RhythmStats{gap:8px}}
`;(D.head||D.documentElement).appendChild(s)}
function sessions(){const c=read(),ss=c.sessions||[];if(range==='last')return ss.slice(0,1);const cut=Date.now()-Number(range||7)*864e5;return ss.filter(s=>Number(s.start)>=cut)}
function data(){const ss=sessions(),events=ss.flatMap(s=>s.events||[]),mins=ss.reduce((n,s)=>n+Math.max(0,Math.round(((s.end||Date.now())-s.start)/60000)),0),sets=events.filter(e=>e.kind==='strength').reduce((n,e)=>n+(Number(e.sets)||0),0),f={};events.forEach(e=>(e.muscles||[]).forEach(x=>f[x]=(f[x]||0)+1));return{ss,events,mins,sets,focus:Object.entries(f).sort((a,b)=>b[1]-a[1]).slice(0,5),names:[...new Set(events.map(e=>e.name).filter(Boolean))]}}
function hash(s){let h=2166136261;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function sig(r){const seed=hash(r.events.map(e=>e.name).join('|')+'|'+(r.ss[0]?.start||0)+'|'+(read().profile?.name||'')),bits=[];for(let i=0;i<16;i++)bits.push(Boolean((seed>>>(i%31))&1));return{seed,bits,rot:(seed%7-3)*3}}
function glyph(s){return`<span class="v8710Glyph" style="--rot:${s.rot}deg">${s.bits.map((x,i)=>`<i class="${x||i===s.seed%16?'on':''}"></i>`).join('')}</span>`}
function dateText(r){const d=r.ss.length?new Date(r.ss[0].start):new Date();return`${d.getFullYear()}.${pad(d.getMonth()+1)}.${pad(d.getDate())}`}
function render(){const d=$('#v8710ReportDeck');if(!d)return;const r=data(),s=sig(r),p=read().profile||{},items=r.events.slice(-10),max=Math.max(1,...items.map(e=>e.kind==='strength'?Number(e.sets)||1:Number(e.duration)||1)),focus=r.focus.length?r.focus:[['训练',1]],n=Math.max(1,r.events.length);d.innerHTML=`
<article class="v8710Plate"><div class="v8710PlateHead"><div class="v8710PlateMeta"><div class="t brand">AXIS${p.name?' · '+esc(p.name):''}</div><div class="t">${dateText(r)}</div></div>${glyph(s)}</div><div class="v8710Rule"></div><div class="d v8710Names">${r.names.slice(0,4).map(esc).join(' / ')||'本次训练'}</div><div class="v8710Bars">${items.map((e,i)=>`<i class="${i===items.length-1?'hot':''}" style="height:${Math.max(14,Math.round(((e.kind==='strength'?Number(e.sets)||1:Number(e.duration)||1)/max)*100))}%"></i>`).join('')||'<i class="hot" style="height:28%"></i>'}</div><div class="v8710Foot"><div><div class="d">${r.mins} 分</div><div class="t">训练时间</div></div><div class="right"><div class="d">${r.names.length} 项 · ${r.sets} 组</div><div class="t">记录</div></div></div></article>
<article class="v8710Plate"><div class="v8710PlateHead"><div class="d">训练重心</div>${glyph({bits:s.bits.slice().reverse(),rot:-s.rot,seed:s.seed>>>1})}</div><div class="v8710Rule"></div><div class="v8710Grid">${Array.from({length:20},(_,i)=>{const v=((s.seed>>>(i%29))&1)||i<focus.length*2;return`<i class="${v?(i===s.seed%20?'hot':'on'):''}"></i>`}).join('')}</div><div class="v8710Focus">${focus.slice(0,4).map(x=>`<span>${esc(x[0])}</span>`).join('')}</div><div class="v8710Foot"><div class="d">${focus[0]?.[0]?esc(focus[0][0]):'—'}</div><div class="t right">${focus.length} 个主要区域</div></div></article>
<article class="v8710Plate"><div class="v8710PlateHead"><div class="d">训练节奏</div>${glyph({bits:s.bits.map((x,i)=>i%3?x:!x),rot:s.rot*-.6,seed:s.seed>>>2})}</div><div class="v8710Rule"></div><div class="v8710Trace">${Array.from({length:9},(_,i)=>`<i class="${i<Math.min(9,n)?(i===Math.min(8,n-1)?'hot':'on'):''}"></i>`).join('')}</div><div class="v8710RhythmStats"><div><b class="d">${r.events.length}</b><span class="t">项目</span></div><div><b class="d">${r.sets}</b><span class="t">组</span></div><div><b class="d">${r.mins}</b><span class="t">分钟</span></div></div><div class="v8710Foot"><div class="t">${dateText(r)}</div><div class="t right">AXIS</div></div></article>`;requestAnimationFrame(()=>d.scrollLeft=card*d.clientWidth)}
function ensure(){const host=$('#reportPreview');if(!host)return;let d=$('#v8710ReportDeck');if(!d){host.insertAdjacentHTML('afterend','<div class="v8710ReportDeck" id="v8710ReportDeck"></div>');d=$('#v8710ReportDeck');d.addEventListener('scroll',()=>{clearTimeout(d._t);d._t=setTimeout(()=>card=Math.max(0,Math.min(2,Math.round(d.scrollLeft/d.clientWidth))),80)},{passive:true})}const sh=$('#shareReport');if(sh){sh.id='v8710ShareReport';sh.classList.add('v8710Share');sh.textContent='分享报告'}render()}
function draw(c,r,index){const W=1080,H=1350,ink='#0b0d10',muted='#747980',accent='#737cff';c.fillStyle='#eeede8';c.fillRect(0,0,W,H);const txt=(s,x,y,big=false,color=ink,align='left')=>{c.fillStyle=color;c.font=`${big?'680 52':'520 36'}px -apple-system,BlinkMacSystemFont,Arial`;c.textAlign=align;c.textBaseline='top';c.fillText(String(s),x,y)};const s=sig(r),items=r.events.slice(-10),max=Math.max(1,...items.map(e=>e.kind==='strength'?Number(e.sets)||1:Number(e.duration)||1)),focus=r.focus.length?r.focus:[['训练',1]],name=read().profile?.name||'';txt(`AXIS${name?' · '+name:''}`,80,80);txt(dateText(r),80,136,false,muted);c.fillStyle=accent;c.fillRect(80,212,72,6);const glyphDraw=(bits,rot=0)=>{c.save();c.translate(890,76);c.rotate(rot*Math.PI/180);for(let i=0;i<16;i++){c.fillStyle=bits[i]?accent:'rgba(11,13,16,.12)';c.fillRect((i%4)*28,Math.floor(i/4)*28,20,20)}c.restore()};
if(index===0){glyphDraw(s.bits,s.rot);txt(r.names.slice(0,4).join(' / ')||'本次训练',80,278,true);const base=830,bw=Math.max(20,Math.floor(820/Math.max(1,items.length))-12);items.forEach((e,i)=>{const v=e.kind==='strength'?Number(e.sets)||1:Number(e.duration)||1,h=Math.max(60,Math.round(v/max*350));c.fillStyle=i===items.length-1?accent:ink;c.fillRect(80+i*(bw+12),base-h,bw,h)});txt(`${r.mins} 分`,80,1160,true);txt('训练时间',80,1225,false,muted);txt(`${r.names.length} 项 · ${r.sets} 组`,1000,1160,true,ink,'right');txt('记录',1000,1225,false,muted,'right')}
else if(index===1){glyphDraw(s.bits.slice().reverse(),-s.rot);txt('训练重心',80,278,true);for(let i=0;i<20;i++){const on=((s.seed>>>(i%29))&1)||i<focus.length*2;c.fillStyle=on?(i===s.seed%20?accent:ink):'rgba(11,13,16,.08)';const x=80+(i%5)*176,y=420+Math.floor(i/5)*142;c.fillRect(x,y,120,120)}txt(focus.slice(0,3).map(x=>x[0]).join(' · '),80,1040,true);txt(`${focus.length} 个主要区域`,80,1120,false,muted)}
else{glyphDraw(s.bits.map((x,i)=>i%3?x:!x),s.rot*-.6);txt('训练节奏',80,278,true);for(let i=0;i<9;i++){c.fillStyle=i<Math.min(9,Math.max(1,r.events.length))?(i===Math.min(8,Math.max(0,r.events.length-1))?accent:ink):'rgba(11,13,16,.10)';c.fillRect(80+i*100,520,78,16)}txt(`${r.events.length} 项`,80,690,true);txt(`${r.sets} 组`,390,690,true);txt(`${r.mins} 分钟`,700,690,true);txt('项目',80,756,false,muted);txt('组',390,756,false,muted);txt('时间',700,756,false,muted);txt(dateText(r),80,1190,false,muted);txt('AXIS',1000,1190,false,muted,'right')}}
async function share(){const r=data();if(!r.ss.length)return;const cv=D.createElement('canvas');cv.width=1080;cv.height=1350;draw(cv.getContext('2d'),r,card);const blob=await new Promise(ok=>cv.toBlob(ok,'image/jpeg',.96));if(!blob)return;const f=new File([blob],`AXIS-${dateText(r)}.jpg`,{type:'image/jpeg'});try{if(navigator.canShare?.({files:[f]})&&navigator.share)return navigator.share({files:[f]})}catch{}const a=D.createElement('a');a.href=URL.createObjectURL(blob);a.download=f.name;D.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}
function bind(){style();D.addEventListener('click',e=>{if(e.target.closest('#reportBtn,#sessionReportBtn,#makeSessionReport'))setTimeout(ensure,120);const x=e.target.closest('#reportRange [data-range]');if(x){range=x.dataset.range;card=0;setTimeout(render,40);return}if(e.target.closest('#v8710ShareReport')){e.preventDefault();share();return}},true);const el=$('#reportSheet');if(el){const MO=window.__AXIS_NATIVE_MUTATION_OBSERVER__||MutationObserver;new MO(()=>{if(el.classList.contains('show'))setTimeout(ensure,60)}).observe(el,{attributes:true,attributeFilter:['class']})}window.addEventListener('pageshow',()=>{if($('#reportSheet')?.classList.contains('show'))ensure()})}
if(D.readyState==='loading')D.addEventListener('DOMContentLoaded',bind,{once:true});else bind();window.__AXIS_8710_REPORT_READY__=true;
})();