(()=>{'use strict';
const D=document,$=(s,r=D)=>r.querySelector(s),$$=(s,r=D)=>Array.from(r.querySelectorAll(s));
const CORE='axis_v60_state',META='axis_v8_meta';
let motionInstalled=false,gravity=null,peak=null,cooldownUntil=0,motionUndo=null,motionUndoTimer=0,timelineTimer=0;
const now=()=>Date.now(),pad=n=>String(n).padStart(2,'0');
function readCore(){try{return JSON.parse(localStorage.getItem(CORE)||'null')||{active:null,sessions:[]}}catch{return{active:null,sessions:[]}}}
function readMeta(){try{const m=JSON.parse(localStorage.getItem(META)||'null')||{};m.events=m.events||{};m.prefs=m.prefs||{};return m}catch{return{events:{},prefs:{}}}}
function writeMeta(m){try{localStorage.setItem(META,JSON.stringify(m));return true}catch{return false}}
function clock(ms){ms=Math.max(0,Number(ms)||0);const h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000);return h?`${h}:${pad(m)}:${pad(s)}`:`${pad(m)}:${pad(s)}`}
function signed(ms){const q=Number(ms)||0;return(q>0?'+':q<0?'−':'±')+clock(Math.abs(q))}
function planned(e,m){return Math.max(1,m.events?.[e.id]?.sets?.length||Number(e.sets)||1)}
function activeStrength(){const c=readCore(),m=readMeta();if(!c.active)return null;const xs=(c.active.events||[]).map(e=>({e,a:m.events?.[e.id]?.activity})).filter(x=>x.a?.status==='active'&&x.e.kind==='strength').sort((x,y)=>(y.a.lastResumedAt||y.a.startedAt||0)-(x.a.lastResumedAt||x.a.startedAt||0));return xs[0]||null}
function injectStyle(){if($('#v871Style'))return;const s=D.createElement('style');s.id='v871Style';s.textContent=`#eventList .v82EventStatus,#eventList .v86Metric,#eventList .v87Metric{display:none!important}.v871State{display:inline-flex!important;align-items:center;height:21px;margin-top:6px;padding:0 8px;border-radius:8px;background:rgba(115,124,255,.11);color:#aeb3ff;font-size:10px!important;font-weight:660;line-height:21px;white-space:nowrap;vertical-align:top}.v871State[data-state="paused"]{background:rgba(255,255,255,.045);color:#8d95a3}.v871State[data-state="finished"]{background:rgba(255,255,255,.055);color:#a5acb8}.v871State[data-state="plan"]{background:rgba(115,124,255,.14);color:#b9bdff}.v871Metric{display:block!important;min-height:16px;margin-top:5px;color:#8e96a4;font-size:10.5px!important;line-height:16px;font-variant-numeric:tabular-nums;white-space:nowrap}.v87Test.v871Test{width:auto!important;min-width:58px;height:30px!important;margin:0!important;padding:0 11px!important;border-radius:9px!important;background:rgba(255,255,255,.045)!important;font-size:10.5px!important;flex:none}.v87Audio .v87Top{min-height:30px}.v87Audio .v87AudioBlock{padding:15px 0}.v87Audio .v87Seg{height:42px}.v871MotionState{font-size:10.5px!important;color:#7f8794!important;font-weight:560!important}`;(D.head||D.documentElement).appendChild(s)}
function migrateMotion(){const m=readMeta(),p=m.prefs||{};if(p.v871Motion==null)p.v871Motion=p.v87Motion==='set'?'set':'off';p.v87Motion='off';m.prefs=p;writeMeta(m)}
function refineSettings(){const audio=$('#v87Audio');if(!audio)return;const motion=$('#v87Motion')||$('#v871Motion');if(motion){motion.id='v871Motion';const top=motion.previousElementSibling;if(top?.classList.contains('v87Top')){const b=$('b',top);if(b){b.classList.add('v871MotionState');const p=readMeta().prefs||{};b.textContent=p.v871Motion==='set'?'已启用':''}}$$('button',motion).forEach(b=>b.classList.toggle('active',b.dataset.v===(readMeta().prefs?.v871Motion==='set'?'set':'off')))}const tone=$('#v87Tone');const test=$('#v87Test');if(tone&&test){const top=tone.closest('.v87AudioBlock')?.querySelector('.v87Top');if(top&&!top.contains(test)){const empty=$('b',top);if(empty&&!empty.textContent.trim())empty.remove();test.classList.add('v871Test');top.appendChild(test)}}}
function renderTimeline(){const c=readCore(),m=readMeta();for(const row of $$('#eventList [data-event]')){const e=c.active?.events?.find(x=>x.id===row.dataset.event),a=e?m.events?.[e.id]?.activity:null;if(!e||!a)continue;const box=row.querySelector('span:nth-child(2)');if(!box)continue;const total=planned(e,m),plan=e.kind==='strength'&&Number(a.completedSets||0)>=total;const state=a.status==='finished'?'finished':plan?'plan':a.status==='paused'?'paused':'active';const label=state==='finished'?'已完成':state==='plan'?'计划完成':state==='paused'?'已暂停':'进行中';let tag=$('.v871State',box);if(!tag){tag=D.createElement('small');tag.className='v871State';box.appendChild(tag)}if(tag.textContent!==label)tag.textContent=label;if(tag.dataset.state!==state)tag.dataset.state=state;let metric=$('.v871Metric',box);if(a.status==='finished'&&a.actualMs){if(!metric){metric=D.createElement('small');metric.className='v871Metric';box.appendChild(metric)}const est=a.estimateMs||a.actualMs,tracked=(a.setDoneAt||[]).some(Boolean),set=tracked?` · ${a.completedSets||0}/${total}组`:'';const text=`实际 ${clock(a.actualMs)} · 预计 ${clock(est)} · ${signed(a.actualMs-est)}${set}`;if(metric.textContent!==text)metric.textContent=text}else metric?.remove()}}
function setMotionPref(v){const m=readMeta();m.prefs.v871Motion=v;m.prefs.v87Motion='off';writeMeta(m);refineSettings()}
async function enableMotion(){let ok=typeof DeviceMotionEvent!=='undefined';try{if(ok&&typeof DeviceMotionEvent.requestPermission==='function')ok=(await DeviceMotionEvent.requestPermission())==='granted'}catch{ok=false}if(!ok){setMotionPref('off');const top=$('#v871Motion')?.previousElementSibling,b=top?.querySelector('b');if(b)b.textContent='未授权';return false}setMotionPref('set');gravity=null;peak=null;installMotion();return true}
function linearVector(e){const a=e.acceleration;if(a&&[a.x,a.y,a.z].every(Number.isFinite))return[a.x,a.y,a.z];const g=e.accelerationIncludingGravity;if(!g||![g.x,g.y,g.z].every(Number.isFinite))return null;const v=[g.x,g.y,g.z];if(!gravity){gravity=v.slice();return null}const alpha=.82;for(let i=0;i<3;i++)gravity[i]=gravity[i]*alpha+v[i]*(1-alpha);return[v[0]-gravity[0],v[1]-gravity[1],v[2]-gravity[2]]}
function motionContextOK(){if(readMeta().prefs?.v871Motion!=='set'||D.visibilityState!=='visible'||now()<cooldownUntil)return false;if($$('.sheetWrap.show').some(x=>x.id!=='finishSheet')||$('#scanSheet')?.classList.contains('show'))return false;const pair=activeStrength();if(!pair)return false;const m=readMeta();return Number(pair.a.completedSets||0)<planned(pair.e,m)}
function showMotionUndo(snapshot){motionUndo=snapshot;const u=$('#v87Undo'),t=$('#v87UndoText'),b=$('#v87UndoBtn');if(u&&t&&b){t.textContent='已完成一组';u.classList.add('show');if(!b.__v871){b.__v871=true;b.addEventListener('click',undoMotion,true)}}clearTimeout(motionUndoTimer);motionUndoTimer=setTimeout(()=>{motionUndo=null;u?.classList.remove('show')},4200)}
function completeByMotion(){const c=readCore(),m=readMeta(),pair=activeStrength();if(!pair)return false;const {e,a}=pair,total=planned(e,m),done=Math.max(0,Number(a.completedSets)||0);if(done>=total)return false;const sets=m.events?.[e.id]?.sets,snap={id:e.id,completedSets:done,setDoneAt:[...(a.setDoneAt||[])],planCompletedAt:a.planCompletedAt||null,restStartedAt:a.restStartedAt||null,index:done,setState:Array.isArray(sets)&&sets[done]?sets[done].state:null,setDone:Array.isArray(sets)&&sets[done]?sets[done].doneAt:null};a.completedSets=done+1;a.setDoneAt=a.setDoneAt||[];a.setDoneAt[done]=now();a.restStartedAt=now();a.restNotified=false;if(a.completedSets>=total)a.planCompletedAt=now();if(Array.isArray(sets)&&sets[done]){sets[done].state='done';sets[done].doneAt=a.setDoneAt[done]}writeMeta(m);showMotionUndo(snap);try{navigator.vibrate?.([12,45,12])}catch{};renderTimeline();return true}
function undoMotion(e){if(!motionUndo)return;e?.preventDefault?.();e?.stopPropagation?.();const m=readMeta(),a=m.events?.[motionUndo.id]?.activity;if(!a){motionUndo=null;return}a.completedSets=motionUndo.completedSets;a.setDoneAt=motionUndo.setDoneAt;a.planCompletedAt=motionUndo.planCompletedAt;a.restStartedAt=motionUndo.restStartedAt;const sets=m.events?.[motionUndo.id]?.sets;if(Array.isArray(sets)&&sets[motionUndo.index]){sets[motionUndo.index].state=motionUndo.setState||'assumed';sets[motionUndo.index].doneAt=motionUndo.setDone||null}writeMeta(m);motionUndo=null;clearTimeout(motionUndoTimer);$('#v87Undo')?.classList.remove('show');renderTimeline()}
function motionHandler(e){if(!motionContextOK())return;const vec=linearVector(e);if(!vec)return;const mag=Math.hypot(vec[0],vec[1],vec[2]),t=now();if(mag<5.2)return;const p={t,mag,vec};if(peak){const dt=t-peak.t,n1=Math.max(.001,peak.mag),n2=Math.max(.001,mag),dot=(vec[0]*peak.vec[0]+vec[1]*peak.vec[1]+vec[2]*peak.vec[2])/(n1*n2);if(dt>=120&&dt<=700&&dot<-.24&&(mag+peak.mag)>=12){peak=null;cooldownUntil=t+5000;if(completeByMotion())return}else if(dt>700)peak=null}peak=p;setTimeout(()=>{if(peak===p)peak=null},760)}
function installMotion(){if(motionInstalled)return;motionInstalled=true;window.addEventListener('devicemotion',motionHandler,{passive:true})}
function installEvents(){D.addEventListener('click',async e=>{const b=e.target.closest('#v871Motion button');if(!b)return;e.preventDefault();if(b.dataset.v==='off'){setMotionPref('off');peak=null;return}await enableMotion()},true);D.addEventListener('click',e=>{if(e.target.closest('#settingsBtn'))setTimeout(refineSettings,130)},true);window.addEventListener('pageshow',()=>setTimeout(()=>{refineSettings();renderTimeline()},80));D.addEventListener('visibilitychange',()=>{if(!D.hidden){refineSettings();renderTimeline()}})}
function boot(){injectStyle();migrateMotion();refineSettings();installEvents();if(readMeta().prefs?.v871Motion==='set')installMotion();renderTimeline();clearInterval(timelineTimer);timelineTimer=setInterval(()=>{if(D.visibilityState==='visible')renderTimeline()},900);const v=$('.versionLine');if(v)v.textContent='版本 8.7.1'}
try{boot()}catch(e){console.warn('[AXIS] 8.7.1 fix skipped',e)}
})();