(()=>{'use strict';
const D=document,$=(s,r=D)=>r.querySelector(s),$$=(s,r=D)=>[...r.querySelectorAll(s)],C='axis_v60_state',M='axis_v8_meta';let id=null,d=null,openAll=false;const seen=new Set();
const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'null')||{}}catch{return{}}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const core=()=>read(C),meta=()=>{const m=read(M);m.events=m.events||{};return m},events=c=>(c.active?[c.active]:[]).concat(c.sessions||[]).flatMap(s=>s.events||[]),ev=(x,c=core())=>events(c).find(e=>e.id===x);
function css(){if($('#v879Style'))return;const s=D.createElement('style');s.id='v879Style';s.textContent=`
:root{--aT:14px;--aE:20px}#v81Undo,#v87Undo,#v87Flash{display:none!important}.sheetWrap .sheet :is(button,label,span,small,p,em),#eventList :is(small,.v82EventStatus,.v87Metric),.v87State,.v87Meta,.v87Rest{font-size:var(--aT)!important;line-height:1.35!important}.sheetHead>b,.v87Name,#v8Sets .v8SetHead>div>b,#eventList [data-event] span:nth-child(2)>b{font-size:var(--aE)!important;line-height:1.15!important}
#cardioFields .choiceControl:has(#intensityChoices){display:grid!important;grid-template-columns:104px 1fr!important;align-items:center!important;gap:12px!important}#cardioFields .choiceControl:has(#intensityChoices)>span{white-space:nowrap!important}.v877IntensityMain,.v875Stepper,.v879Step{height:56px!important;display:grid!important;grid-template-columns:56px 1fr 56px!important;padding:3px!important;align-items:stretch!important}.v877IntensityMain>button,.v875Stepper>button,.v879Step>button{height:50px!important;display:grid!important;place-items:center!important;padding:0!important;margin:0!important;font-size:var(--aE)!important}.v877IntensityValue,.v875Value,.v879Val{height:50px!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:6px!important}.v877IntensityValue b,.v875Value b,.v879Val b{font-size:var(--aE)!important;line-height:1!important}.v877IntensityValue small,.v875Value small,.v879Val small{font-size:var(--aT)!important;line-height:1!important;margin:0!important}
#v8Sets .v8SetCount{display:grid!important;grid-template-columns:48px 78px 48px!important;align-items:center!important}#v8Sets .v8SetCount>*{height:48px!important;display:grid!important;place-items:center!important;padding:0!important;margin:0!important;font-size:var(--aE)!important;line-height:1!important}
#eventList [data-event].v879Done{background:linear-gradient(90deg,rgba(115,124,255,.12),transparent 60%)}#eventList [data-event].v879Done:before{content:'';position:absolute;left:0;top:12px;bottom:12px;width:2px;background:#737cff;border-radius:3px}.v879EditBtn{height:32px;padding:0 11px;border-radius:10px;background:rgba(255,255,255,.045);color:#aeb3ff!important}.v879Block{padding:16px 0;border-bottom:1px solid var(--line)}.v879Top{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px}.v879Top b{font-size:var(--aE)!important}.v879Save{width:100%;height:58px;margin-top:18px;border-radius:18px;background:var(--text);color:#111318;font-weight:720}.v879Note{text-align:center;color:var(--dim);margin-top:10px}
body.v879Lock{overflow:hidden!important}.sheetWrap.show.v879Under{pointer-events:none!important}.sheetWrap.show.v879Under>.sheet{overflow:hidden!important;touch-action:none!important}.sheetWrap.show.v879Front>.sheet{touch-action:pan-y!important;overscroll-behavior:contain!important}.v879More{width:100%;height:42px;display:flex;align-items:center;justify-content:space-between;border-top:1px solid var(--line2);border-bottom:1px solid var(--line2);color:var(--muted)}#eventList.v879Compact>[data-event].v879Hide{display:none!important}
.v877Plate{padding:30px!important}.v877Plate .k,.v877Plate .m,.v877FocusGrid span{font-size:var(--aT)!important;line-height:1.45!important}.v877Plate .l,.v877FocusGrid b{font-size:var(--aE)!important;line-height:1.18!important}.v877Trace{grid-template-columns:1fr!important}.v877TraceNum,.v877ReportHint,.v877TraceBody .k{display:none!important}.v877TraceBody{padding:15px 0!important}.v877AxisLine{height:2px!important;width:42px!important}
@media(max-width:390px){#cardioFields .choiceControl:has(#intensityChoices){grid-template-columns:92px 1fr!important}.v877Plate{padding:26px!important}}
`;(D.head||D.documentElement).appendChild(s)}
function ver(){window.__AXIS_RELEASE__='8.7.9';window.__AXIS_VERSION__='8.7.9';const v=$('.versionLine');if(v){v.textContent='版本 8.7.9';v.dataset.axisVersion='8.7.9';v.style.visibility='visible'}}
function layer(){const xs=$$('.sheetWrap.show');D.body.classList.toggle('v879Lock',!!xs.length);xs.forEach((x,i)=>{x.classList.toggle('v879Under',i<xs.length-1);x.classList.toggle('v879Front',i===xs.length-1)})}
function finishCue(){const m=meta(),t=Date.now();for(const r of $$('#eventList [data-event]')){const a=m.events?.[r.dataset.event]?.activity;if(a?.finishedAt&&t-a.finishedAt<2600&&!seen.has(r.dataset.event)){seen.add(r.dataset.event);r.classList.add('v879Done');setTimeout(()=>r.classList.remove('v879Done'),1700)}}}
function timeline(){const l=$('#eventList');if(!l)return;$('#v879More')?.remove();const rs=$$(':scope>[data-event]',l);rs.forEach(r=>r.classList.remove('v879Hide'));if(rs.length<=4){l.classList.remove('v879Compact');return}if(!openAll){const m=meta(),keep=[];for(const r of rs){const s=m.events?.[r.dataset.event]?.activity?.status;if(s==='active'||s==='paused')keep.push(r)}for(let i=rs.length-1;i>=0&&keep.length<3;i--)if(!keep.includes(rs[i]))keep.push(rs[i]);const k=new Set(keep.slice(0,3));rs.forEach(r=>{if(!k.has(r))r.classList.add('v879Hide')});l.classList.add('v879Compact')}else l.classList.remove('v879Compact');const b=D.createElement('button');b.id='v879More';b.className='v879More';b.innerHTML=`<span>${openAll?'完整时间线':'时间线已收拢'}</span><b>${openAll?'收起':`全部 ${rs.length}`}</b>`;b.onclick=()=>{openAll=!openAll;timeline()};l.before(b)}
function sheet(){if($('#v879Edit'))return;D.body.insertAdjacentHTML('beforeend','<div class="sheetWrap" id="v879Edit"><div class="sheet"><div class="grabber"></div><div class="sheetHead"><b>调整一次</b><button class="closeBtn" id="v879X">×</button></div><div id="v879Body"></div></div></div>');$('#v879X').onclick=()=>{$('#v879Edit').classList.remove('show');layer()}}
function aid(){return $('#v87Finish')?.dataset.id||''}
function entry(){const x=aid(),h=$('#v87Now .v87Actions');if(!x||!h)return;const r=meta().events?.[x];if(!r?.activity||r.activity.status==='finished'||r.v879EditAt){$('#v879EditBtn')?.remove();return}if(!$('#v879EditBtn')){const b=D.createElement('button');b.id='v879EditBtn';b.className='v879EditBtn';b.textContent='调整一次';b.onclick=()=>open(x);h.appendChild(b)}}
function open(x){const c=core(),m=meta(),e=ev(x,c),r=m.events?.[x];if(!e||!r||r.v879EditAt)return;id=x;if(e.kind==='strength'){const ss=Array.isArray(r.sets)?r.sets:[],done=Number(r.activity?.completedSets)||0,b=ss[done]||ss.at(-1)||{weight:e.weight||20,reps:e.reps||10};d={kind:'s',done,sets:Math.max(done+1,ss.length||e.sets||1),w:Number(b.weight)||20,r:Number(b.reps)||10}}else d={kind:'c',min:Number(e.duration)||15,int:Number(e.intensity)||1};render();$('#v879Edit').classList.add('show');layer()}
const row=(n,k,v,u)=>`<div class="v879Block"><div class="v879Top"><span>${n}</span><b>${v}${u}</b></div><div class="v879Step"><button data-k="${k}" data-d="-1">−</button><div class="v879Val"><b>${v}</b><small>${u}</small></div><button data-k="${k}" data-d="1">＋</button></div></div>`;
function render(){const b=$('#v879Body');if(!b||!d)return;b.innerHTML=d.kind==='s'?`${row('总组数','sets',d.sets,'组')}${row('未完成组重量','w',d.w,'kg')}${row('未完成组次数','r',d.r,'次')}<button class="v879Save" id="v879Save">应用调整</button><div class="v879Note">已完成的组不改变 · 仅可调整一次</div>`:`${row('时间','min',d.min,'分钟')}${row('阻力 / 档位','int',d.int,'档')}<button class="v879Save" id="v879Save">应用调整</button><div class="v879Note">进行中的项目仅可调整一次</div>`;$('#v879Save').onclick=apply}
function change(k,n){if(!d)return;if(k==='sets')d.sets=Math.max(d.done+1,Math.min(10,d.sets+n));if(k==='w'){const st=d.w<10?.5:d.w<30?1:d.w<120?2.5:5;d.w=Math.max(0,Math.round((d.w+n*st)*100)/100)}if(k==='r')d.r=Math.max(1,d.r+n);if(k==='min')d.min=Math.max(1,d.min+n);if(k==='int')d.int=Math.max(1,Math.min(99,d.int+n));render()}
function apply(){const c=core(),m=meta(),e=ev(id,c),r=m.events?.[id];if(!e||!r||r.v879EditAt)return;if(d.kind==='s'){let ss=Array.isArray(r.sets)?r.sets.map(x=>({...x})):[];while(ss.length<d.sets)ss.push({weight:d.w,reps:d.r,state:'assumed',doneAt:null,inferred:true});ss=ss.slice(0,d.sets);for(let i=d.done;i<ss.length;i++){ss[i].weight=d.w;ss[i].reps=d.r}r.sets=ss;e.sets=ss.length;e.weight=Math.max(...ss.map(x=>+x.weight||0));e.reps=+ss[0]?.reps||d.r}else{e.duration=d.min;e.intensity=d.int;r.activity.estimateMs=d.min*60000}r.v879EditAt=Date.now();save(C,c);save(M,m);$('#v879Edit').classList.remove('show');$('#v879EditBtn')?.remove();layer()}
function observe(){const MO=window.__AXIS_NATIVE_MUTATION_OBSERVER__||MutationObserver;if(!MO)return;const evl=$('#eventList');if(evl)new MO(()=>{finishCue();timeline();entry()}).observe(evl,{childList:true,subtree:true,characterData:true});new MO(()=>{layer();entry()}).observe(D.body,{childList:true});for(const s of $$('.sheetWrap'))new MO(layer).observe(s,{attributes:true,attributeFilter:['class']})}
function bind(){css();ver();sheet();entry();finishCue();timeline();layer();observe();D.addEventListener('click',e=>{const b=e.target.closest('[data-k]');if(b){change(b.dataset.k,+b.dataset.d);return}requestAnimationFrame(()=>{entry();finishCue();timeline();layer();ver()})},true);window.addEventListener('pageshow',()=>{ver();entry();timeline();layer()})}
if(D.readyState==='loading')D.addEventListener('DOMContentLoaded',bind,{once:true});else bind();window.__AXIS_879_READY__=true;
})();
