(()=>{'use strict';
const D=document,$=(s,r=D)=>r.querySelector(s),$$=(s,r=D)=>Array.from(r.querySelectorAll(s));
const C='axis_v60_state',M='axis_v8_meta',VERSION='8.7.9';
let editId=null,editDraft=null,openAll=false,patchQueued=false,lastStepAt=0;
const seen=new Set(),clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),fmt=n=>{n=Number(n)||0;return n%1?String(Math.round(n*100)/100):String(n)};
const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'null')||{}}catch{return{}}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const core=()=>read(C),meta=()=>{const m=read(M);m.events=m.events||{};return m},events=c=>(c.active?[c.active]:[]).concat(c.sessions||[]).flatMap(s=>s.events||[]),eventById=(id,c=core())=>events(c).find(e=>e.id===id);
function css(){if($('#v879Style'))return;const s=D.createElement('style');s.id='v879Style';s.textContent=`
:root{--axis-ui:15px;--axis-display:22px;--axis-pad:clamp(20px,5.3vw,28px);--axis-control-h:56px}
#v81Undo,#v87Undo,#v87Flash{display:none!important}[data-v875-step]{pointer-events:none!important}.v8Adjust:has([data-v875-step]){visibility:hidden!important}
.sheet{padding-left:var(--axis-pad)!important;padding-right:var(--axis-pad)!important}.sheetHead{height:54px!important;margin-bottom:20px!important;grid-template-columns:minmax(0,1fr) 44px!important}.sheetHead>b{font-size:var(--axis-display)!important;line-height:1.1!important;letter-spacing:-.02em!important}.sheetHead .closeBtn{font-size:var(--axis-display)!important}
.sheet :is(.resultRow span,.resultRow b,.musclePanel i,.musclePanel>span,.recognitionLine span,.numberLabel>span,.numberLabel>small,.choiceControl>span,.quickValues button,.choiceStrip button,.sectionLabel,.lineInput span,.settingLink span,.settingLink b,.settingPlain span,.settingPlain b,.textAction,.dangerAction,.reportAction,.versionLine,.v879FieldLabel,.v879Current,.v879Note){font-size:var(--axis-ui)!important;line-height:1.35!important}.sheet :is(.numberMain input,.v8SetRow>span b,.v879Value b,.v879NumInput,.v877IntensityValue b){font-size:var(--axis-display)!important;line-height:1!important;font-variant-numeric:tabular-nums!important;letter-spacing:-.018em!important}.sheet :is(.numberMain em,.v8SetRow>span small,.v879Value small,.v877IntensityValue small){font-size:var(--axis-ui)!important;line-height:1!important;margin:0!important;color:var(--muted)!important}
.resultRow{height:72px!important}.musclePanel{padding:16px 0!important}.numberControl{padding:18px 0 20px!important}.numberLabel{min-height:24px!important}.numberMain{height:72px!important;grid-template-columns:60px minmax(0,1fr) 60px!important}.numberMain>button{width:52px!important;height:52px!important;display:grid!important;place-items:center!important;padding:0!important;margin:0!important;font-size:var(--axis-display)!important}.numberMain label{height:56px!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:7px!important}.numberMain input{width:auto!important;min-width:64px!important;max-width:120px!important;text-align:center!important;padding:0!important}.quickValues,.choiceStrip{gap:8px!important}.quickValues button,.choiceStrip button{height:42px!important;min-width:54px!important;padding:0 12px!important}.choiceControl{min-height:76px!important;grid-template-columns:104px minmax(0,1fr)!important;gap:12px!important}
#cardioFields .choiceControl:has(#intensityChoices){display:block!important;min-height:0!important;padding:18px 0 20px!important;border-bottom:1px solid var(--line2)!important}#cardioFields .choiceControl:has(#intensityChoices)>span{display:block!important;margin-bottom:12px!important;white-space:normal!important}#intensityChoices.v877Intensity{display:block!important;width:100%!important;overflow:visible!important}.v877IntensityMain{width:100%!important;height:var(--axis-control-h)!important;display:grid!important;grid-template-columns:56px minmax(0,1fr) 56px!important;align-items:center!important;padding:3px!important;border-radius:16px!important;background:var(--s2)!important;overflow:hidden!important}.v877IntensityMain>button{height:50px!important;display:grid!important;place-items:center!important;padding:0!important;margin:0!important;font-size:var(--axis-display)!important}.v877IntensityValue{height:50px!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:7px!important}.v877IntensityQuick{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:8px!important;overflow:visible!important;margin-top:10px!important}.v877IntensityQuick button{min-width:0!important;width:100%!important;height:40px!important;padding:0!important;border-radius:12px!important;font-size:var(--axis-ui)!important}.v877IntensityNote{display:none!important}
#v8Sets{margin-top:14px!important;border-top:1px solid var(--line2)!important}#v8Sets .v8SetHead{min-height:76px!important;display:grid!important;grid-template-columns:minmax(0,1fr) 164px!important;align-items:center!important;gap:16px!important}#v8Sets .v8SetHead>div:first-child b{font-size:var(--axis-display)!important;line-height:1.1!important}#v8Sets .v8SetHead>div:first-child span{font-size:var(--axis-ui)!important;line-height:1.35!important;margin-top:6px!important}#v8Sets .v8SetCount{width:164px!important;display:grid!important;grid-template-columns:48px 68px 48px!important;align-items:center!important;justify-content:end!important;gap:0!important}#v8Sets .v8SetCount>*{width:100%!important;height:48px!important;display:grid!important;place-items:center!important;padding:0!important;margin:0!important;line-height:1!important}#v8Sets .v8SetCount button{font-size:var(--axis-display)!important;color:var(--muted)!important}#v8Sets .v8SetCount>b{font-size:var(--axis-display)!important;white-space:nowrap!important;text-align:center!important;font-variant-numeric:tabular-nums!important}
.v875PlanEntry{height:58px!important;display:grid!important;grid-template-columns:minmax(0,1fr) auto 18px!important;align-items:center!important;gap:10px!important;border-top:1px solid var(--line2)!important;border-bottom:1px solid var(--line2)!important;text-align:left!important}.v875PlanEntry b,.v875PlanEntry strong,.v875PlanEntry i{font-size:var(--axis-ui)!important;line-height:1!important}.v875PlanEntry small{display:none!important}.v875PlanEntry i{font-style:normal!important;color:var(--dim)!important;text-align:right!important}
#v8Sets .v8SetRows{border-top:0!important}#v8Sets .v8SetRow{min-height:78px!important;display:grid!important;grid-template-columns:34px minmax(88px,1fr) minmax(88px,1fr) 58px!important;column-gap:10px!important;align-items:center!important;padding:0!important;border-bottom:1px solid var(--line2)!important}#v8Sets .v8SetRow>i{font-size:var(--axis-ui)!important;line-height:1!important;padding:0!important;color:var(--dim)!important;font-style:normal!important;text-align:left!important}#v8Sets .v8SetRow>span{height:54px!important;display:flex!important;align-items:center!important;justify-content:flex-start!important;gap:6px!important;min-width:0!important}#v8Sets .v8SetRow>span b{font-weight:650!important}#v8Sets .v8SetRow>span small{font-weight:500!important;white-space:nowrap!important}#v8Sets .v8SetRow>em{width:58px!important;min-width:58px!important;max-width:58px!important;height:36px!important;padding:0!important;border-radius:11px!important;display:grid!important;place-items:center!important;justify-self:end!important;font-size:var(--axis-ui)!important;font-style:normal!important;line-height:1!important}
.v8Adjust{padding:18px 0 4px!important;visibility:visible!important}.v879Adjust{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;width:100%}.v879Field{min-width:0}.v879FieldLabel{height:30px;display:flex;align-items:center;justify-content:space-between;gap:8px;color:var(--muted)}.v879Control{height:var(--axis-control-h);display:grid;grid-template-columns:52px minmax(0,1fr) 52px;align-items:center;border-radius:16px;background:var(--s2);overflow:hidden}.v879Control>button{height:52px;display:grid;place-items:center;padding:0;margin:0;font-size:var(--axis-display);color:var(--muted)}.v879Value{display:flex!important;align-items:center!important;justify-content:center!important;gap:6px!important;color:var(--text)!important}.v879Value b{font-weight:650!important}.v879Pattern{width:100%;min-height:38px;margin-top:8px;padding:0 10px;border-radius:11px;background:rgba(115,124,255,.09);color:var(--accent2);font-size:var(--axis-ui);text-align:center}
.v879NumSheet{padding-bottom:calc(24px + env(safe-area-inset-bottom))!important}.v879Current{display:block;color:var(--muted);margin:2px 0 12px}.v879NumInput{width:100%;height:66px;border:0;border-radius:17px;background:var(--s2);color:var(--text);padding:0 16px;text-align:center;outline:0}.v879NumApply{width:100%;height:58px;margin-top:12px;border-radius:18px;background:var(--text);color:#0b0d10;font-size:var(--axis-ui);font-weight:720}
body.v879Lock{overflow:hidden!important}.sheetWrap.show.v879Under{pointer-events:none!important}.sheetWrap.show.v879Under>.sheet{overflow:hidden!important;touch-action:none!important}.sheetWrap.show.v879Front>.sheet{touch-action:pan-y!important;overscroll-behavior:contain!important}.v879More{width:100%;height:44px;display:flex;align-items:center;justify-content:space-between;border-top:1px solid var(--line2);border-bottom:1px solid var(--line2);color:var(--muted);font-size:var(--axis-ui)}#eventList.v879Compact>[data-event].v879Hide{display:none!important}#eventList [data-event].v879Done{background:linear-gradient(90deg,rgba(115,124,255,.10),transparent 64%)}#eventList [data-event].v879Done:before{content:'';position:absolute;left:0;top:14px;bottom:14px;width:2px;background:#737cff;border-radius:3px}.v879EditBtn{height:34px;padding:0 12px;border-radius:10px;background:rgba(255,255,255,.045);color:#aeb3ff!important;font-size:var(--axis-ui)!important}
.v879Block{padding:18px 0;border-bottom:1px solid var(--line)}.v879Top{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px}.v879Top b{font-size:var(--axis-display)!important}.v879Save{width:100%;height:58px;margin-top:18px;border-radius:18px;background:var(--text);color:#111318;font-size:var(--axis-ui);font-weight:720}.v879Note{text-align:center;color:var(--dim);margin-top:10px}
.v877Plate{padding:30px!important}.v877Plate :is(.k,.m,.v877FocusGrid span,.v877TraceBody .k){font-size:var(--axis-ui)!important;line-height:1.45!important}.v877Plate :is(.l,.v877FocusGrid b){font-size:var(--axis-display)!important;line-height:1.15!important}.v877TraceNum,.v877ReportHint{display:none!important}.v877Trace{grid-template-columns:1fr!important}.v877TraceBody{padding:16px 0!important}.v877PlateFoot{gap:14px!important}
@media(max-width:390px){:root{--axis-pad:20px}.sheet{padding-left:20px!important;padding-right:20px!important}#v8Sets .v8SetHead{grid-template-columns:minmax(0,1fr) 150px!important;gap:10px!important}#v8Sets .v8SetCount{width:150px!important;grid-template-columns:44px 62px 44px!important}#v8Sets .v8SetRow{grid-template-columns:28px minmax(74px,1fr) minmax(74px,1fr) 50px!important;column-gap:6px!important}#v8Sets .v8SetRow>em{width:50px!important;min-width:50px!important;max-width:50px!important}.v879Adjust{grid-template-columns:1fr!important;gap:10px}}
`;(D.head||D.documentElement).appendChild(s)}
function rows(){return $$('#v8Sets .v8SetRow')}
function activeSet(){const rs=rows(),row=rs.find(x=>x.classList.contains('active'))||rs[0];if(!row)return null;const vals=$$('span>b',row).map(x=>Number(x.textContent));return{row,i:rs.indexOf(row),w:Number(vals[0])||0,r:Number(vals[1])||0}}
function setValues(){return rows().map(row=>{const a=$$('span>b',row).map(x=>Number(x.textContent));return{w:Number(a[0])||0,r:Number(a[1])||0}})}
function weightStep(w){if(w<10)return.5;if(w<30)return 1;if(w<120)return 2.5;if(w<220)return 5;return 10}
function observed(kind){const a=activeSet(),vs=setValues();if(!a||a.i<1||a.i>=vs.length-1)return null;const k=kind==='weight'?'w':'r',delta=vs[a.i][k]-vs[a.i-1][k];if(!Number.isFinite(delta)||Math.abs(delta)<(kind==='weight'?.24:.5))return null;return{delta}}
function hiddenTrigger(kind,val){const h=$('#v8Sets');if(!h)return;const b=D.createElement('button');b.type='button';b.hidden=true;if(kind==='weight')b.dataset.w=String(clamp(Math.round(Number(val)*100)/100,0,1000));else b.dataset.r=String(clamp(Math.round(Number(val)),1,300));h.appendChild(b);b.click();b.remove()}
function patchAdjust(){const h=$('#v8Sets'),adj=$('.v8Adjust',h),a=activeSet();if(!h||!adj||!a)return;const ws=weightStep(a.w),wp=observed('weight'),rp=observed('reps'),sig=[a.i,a.w,a.r,rows().length,ws,wp?.delta||0,rp?.delta||0].join('|');if(adj.dataset.v879safe===sig&&adj.querySelector('.v879Adjust'))return;adj.dataset.v879safe=sig;adj.innerHTML=`<div class="v879Adjust"><section class="v879Field"><div class="v879FieldLabel"><span>重量</span><span>${fmt(ws)} kg / 次</span></div><div class="v879Control"><button type="button" data-v879-step="weight" data-dir="-1">−</button><button type="button" class="v879Value" data-v879-edit="weight"><b>${fmt(a.w)}</b><small>kg</small></button><button type="button" data-v879-step="weight" data-dir="1">＋</button></div>${wp?`<button type="button" class="v879Pattern" data-v879-pattern="weight">后续每组 ${wp.delta>0?'+':''}${fmt(wp.delta)} kg</button>`:''}</section><section class="v879Field"><div class="v879FieldLabel"><span>次数</span><span>1 次 / 次</span></div><div class="v879Control"><button type="button" data-v879-step="reps" data-dir="-1">−</button><button type="button" class="v879Value" data-v879-edit="reps"><b>${a.r}</b><small>次</small></button><button type="button" data-v879-step="reps" data-dir="1">＋</button></div>${rp?`<button type="button" class="v879Pattern" data-v879-pattern="reps">后续每组 ${rp.delta>0?'+':''}${Math.round(rp.delta)} 次</button>`:''}</section></div>`}
function cleanLegacy(){for(const b of $$('[data-v875-step]')){b.removeAttribute('data-v875-step');b.removeAttribute('data-dir')}patchAdjust()}
function queuePatch(){if(patchQueued)return;patchQueued=true;requestAnimationFrame(()=>{patchQueued=false;cleanLegacy()})}
function ensureNum(){if($('#v879NumSheet'))return;D.body.insertAdjacentHTML('beforeend','<div class="sheetWrap" id="v879NumSheet"><div class="sheet v879NumSheet"><div class="grabber"></div><div class="sheetHead"><b id="v879NumTitle">调整</b><button class="closeBtn" id="v879NumClose">×</button></div><span class="v879Current" id="v879NumCurrent"></span><input class="v879NumInput" id="v879NumInput" inputmode="decimal"><button class="v879NumApply" id="v879NumApply">应用</button></div></div>');$('#v879NumClose').onclick=()=>{$('#v879NumSheet').classList.remove('show');layer()};$('#v879NumApply').onclick=applyNum}
function openNum(kind){ensureNum();const a=activeSet();if(!a)return;const v=kind==='weight'?a.w:a.r,s=$('#v879NumSheet');s.dataset.kind=kind;$('#v879NumTitle').textContent=kind==='weight'?'重量':'次数';$('#v879NumCurrent').textContent=kind==='weight'?`当前 ${fmt(v)} kg · 直接输入`:`当前 ${v} 次 · 直接输入`;$('#v879NumInput').value=String(v);s.classList.add('show');layer();setTimeout(()=>{$('#v879NumInput')?.focus();$('#v879NumInput')?.select?.()},60)}
function applyNum(){const s=$('#v879NumSheet'),kind=s?.dataset.kind,v=Number($('#v879NumInput')?.value);if(!Number.isFinite(v))return;hiddenTrigger(kind,kind==='weight'?clamp(v,0,1000):clamp(v,1,300));s.classList.remove('show');layer();queuePatch()}
function step(kind,dir){const t=performance.now();if(t-lastStepAt<110)return;lastStepAt=t;const a=activeSet();if(!a)return;if(kind==='weight')hiddenTrigger('weight',a.w+dir*weightStep(a.w));else hiddenTrigger('reps',a.r+dir);queuePatch()}
function applyPattern(kind){const a=activeSet(),p=observed(kind),rs=rows();if(!a||!p)return;let v=kind==='weight'?a.w:a.r;const original=a.i;(async()=>{for(let i=a.i+1;i<rs.length;i++){v+=p.delta;rows()[i]?.click();await new Promise(r=>setTimeout(r,16));hiddenTrigger(kind,v);await new Promise(r=>setTimeout(r,16))}rows()[original]?.click();queuePatch()})()}
function layer(){const xs=$$('.sheetWrap.show');D.body.classList.toggle('v879Lock',!!xs.length);xs.forEach((x,i)=>{x.classList.toggle('v879Under',i<xs.length-1);x.classList.toggle('v879Front',i===xs.length-1)})}
function finishCue(){const m=meta(),t=Date.now();for(const r of $$('#eventList [data-event]')){const a=m.events?.[r.dataset.event]?.activity;if(a?.finishedAt&&t-a.finishedAt<2600&&!seen.has(r.dataset.event)){seen.add(r.dataset.event);r.classList.add('v879Done');setTimeout(()=>r.classList.remove('v879Done'),1500)}}}
function timeline(){const l=$('#eventList');if(!l)return;$('#v879More')?.remove();const rs=$$(':scope>[data-event]',l);rs.forEach(r=>r.classList.remove('v879Hide'));if(rs.length<=4){l.classList.remove('v879Compact');return}if(!openAll){const m=meta(),keep=[];for(const r of rs){const s=m.events?.[r.dataset.event]?.activity?.status;if(s==='active'||s==='paused')keep.push(r)}for(let i=rs.length-1;i>=0&&keep.length<3;i--)if(!keep.includes(rs[i]))keep.push(rs[i]);const k=new Set(keep.slice(0,3));rs.forEach(r=>{if(!k.has(r))r.classList.add('v879Hide')});l.classList.add('v879Compact')}else l.classList.remove('v879Compact');const b=D.createElement('button');b.id='v879More';b.className='v879More';b.innerHTML=`<span>${openAll?'完整时间线':'时间线已收拢'}</span><b>${openAll?'收起':`全部 ${rs.length}`}</b>`;b.onclick=()=>{openAll=!openAll;timeline()};l.before(b)}
function ensureEdit(){if($('#v879Edit'))return;D.body.insertAdjacentHTML('beforeend','<div class="sheetWrap" id="v879Edit"><div class="sheet"><div class="grabber"></div><div class="sheetHead"><b>调整一次</b><button class="closeBtn" id="v879X">×</button></div><div id="v879Body"></div></div></div>');$('#v879X').onclick=()=>{$('#v879Edit').classList.remove('show');layer()}}
function activeId(){return $('#v87Finish')?.dataset.id||''}
function editEntry(){const id=activeId(),host=$('#v87Now .v87Actions');if(!id||!host)return;const r=meta().events?.[id];if(!r?.activity||r.activity.status==='finished'||r.v879EditAt){$('#v879EditBtn')?.remove();return}if(!$('#v879EditBtn')){const b=D.createElement('button');b.id='v879EditBtn';b.className='v879EditBtn';b.textContent='调整一次';b.onclick=()=>openEdit(id);host.appendChild(b)}}
function openEdit(id){ensureEdit();const c=core(),m=meta(),e=eventById(id,c),r=m.events?.[id];if(!e||!r||r.v879EditAt)return;editId=id;if(e.kind==='strength'){const ss=Array.isArray(r.sets)?r.sets:[],done=Number(r.activity?.completedSets)||0,b=ss[done]||ss.at(-1)||{weight:e.weight||20,reps:e.reps||10};editDraft={kind:'s',done,sets:Math.max(done+1,ss.length||e.sets||1),w:Number(b.weight)||20,r:clamp(Number(b.reps)||10,1,300)}}else editDraft={kind:'c',min:Number(e.duration)||15,int:Number(e.intensity)||1};renderEdit();$('#v879Edit').classList.add('show');layer()}
const editRow=(n,k,v,u)=>`<div class="v879Block"><div class="v879Top"><span>${n}</span><b>${v} ${u}</b></div><div class="v879Control"><button data-v879-edit-step="${k}" data-dir="-1">−</button><div class="v879Value"><b>${v}</b><small>${u}</small></div><button data-v879-edit-step="${k}" data-dir="1">＋</button></div></div>`;
function renderEdit(){const b=$('#v879Body');if(!b||!editDraft)return;b.innerHTML=editDraft.kind==='s'?`${editRow('总组数','sets',editDraft.sets,'组')}${editRow('未完成组重量','w',fmt(editDraft.w),'kg')}${editRow('未完成组次数','r',editDraft.r,'次')}<button class="v879Save" id="v879Save">应用调整</button><div class="v879Note">已完成的组不改变 · 仅可调整一次</div>`:`${editRow('时间','min',editDraft.min,'分钟')}${editRow('阻力 / 档位','int',editDraft.int,'档')}<button class="v879Save" id="v879Save">应用调整</button><div class="v879Note">进行中的项目仅可调整一次</div>`;$('#v879Save').onclick=applyEdit}
function changeEdit(k,n){if(!editDraft)return;if(k==='sets')editDraft.sets=clamp(editDraft.sets+n,editDraft.done+1,10);if(k==='w'){const st=weightStep(editDraft.w);editDraft.w=Math.max(0,Math.round((editDraft.w+n*st)*100)/100)}if(k==='r')editDraft.r=clamp(editDraft.r+n,1,300);if(k==='min')editDraft.min=Math.max(1,editDraft.min+n);if(k==='int')editDraft.int=clamp(editDraft.int+n,1,99);renderEdit()}
function applyEdit(){const c=core(),m=meta(),e=eventById(editId,c),r=m.events?.[editId];if(!e||!r||r.v879EditAt)return;if(editDraft.kind==='s'){let ss=Array.isArray(r.sets)?r.sets.map(x=>({...x})):[];while(ss.length<editDraft.sets)ss.push({weight:editDraft.w,reps:editDraft.r,state:'assumed',doneAt:null,inferred:true});ss=ss.slice(0,editDraft.sets);for(let i=editDraft.done;i<ss.length;i++){ss[i].weight=editDraft.w;ss[i].reps=editDraft.r}r.sets=ss;e.sets=ss.length;e.weight=Math.max(...ss.map(x=>+x.weight||0));e.reps=+ss[0]?.reps||editDraft.r}else{e.duration=editDraft.min;e.intensity=editDraft.int;r.activity.estimateMs=editDraft.min*60000}r.v879EditAt=Date.now();save(C,c);save(M,m);$('#v879Edit').classList.remove('show');$('#v879EditBtn')?.remove();layer()}
function version(){window.__AXIS_RELEASE__=VERSION;window.__AXIS_VERSION__=VERSION;const v=$('.versionLine');if(v){v.textContent=`版本 ${VERSION}`;v.dataset.axisVersion=VERSION;v.style.visibility='visible'}}
function bind(){css();ensureNum();ensureEdit();cleanLegacy();version();layer();finishCue();timeline();editEntry();const sets=$('#v8Sets');if(sets){const MO=window.__AXIS_NATIVE_MUTATION_OBSERVER__||MutationObserver;new MO(queuePatch).observe(sets,{childList:true,subtree:true,characterData:true})}const evl=$('#eventList');if(evl){const MO=window.__AXIS_NATIVE_MUTATION_OBSERVER__||MutationObserver;new MO(()=>{finishCue();timeline();editEntry()}).observe(evl,{childList:true,subtree:true,characterData:true})}for(const s of $$('.sheetWrap')){const MO=window.__AXIS_NATIVE_MUTATION_OBSERVER__||MutationObserver;new MO(layer).observe(s,{attributes:true,attributeFilter:['class']})}D.addEventListener('click',e=>{const stepBtn=e.target.closest('[data-v879-step]');if(stepBtn){e.preventDefault();e.stopPropagation();step(stepBtn.dataset.v879Step,Number(stepBtn.dataset.dir)||1);return}const editBtn=e.target.closest('[data-v879-edit]');if(editBtn){e.preventDefault();e.stopPropagation();openNum(editBtn.dataset.v879Edit);return}const pat=e.target.closest('[data-v879-pattern]');if(pat){e.preventDefault();e.stopPropagation();applyPattern(pat.dataset.v879Pattern);return}const es=e.target.closest('[data-v879-edit-step]');if(es){e.preventDefault();e.stopPropagation();changeEdit(es.dataset.v879EditStep,Number(es.dataset.dir)||1);return}requestAnimationFrame(()=>{cleanLegacy();version();layer();editEntry()})},true);window.addEventListener('pageshow',()=>{cleanLegacy();version();layer();timeline()})}
if(D.readyState==='loading')D.addEventListener('DOMContentLoaded',bind,{once:true});else bind();window.__AXIS_879_READY__=true;
})();
