(()=>{'use strict';
const D=document,$=(s,r=D)=>r.querySelector(s),$$=(s,r=D)=>Array.from(r.querySelectorAll(s));
const CORE='axis_v60_state',META='axis_v8_meta';let editId=null,edit=null,expanded=false,seq=0;const ranks=new WeakMap(),seen=new Set();
const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'null')||{}}catch{return{}}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return 1}catch{return 0}};
const core=()=>{const c=read(CORE);c.sessions=c.sessions||[];return c},meta=()=>{const m=read(META);m.events=m.events||{};return m};
const events=c=>(c.active?[c.active]:[]).concat(c.sessions||[]).flatMap(s=>s.events||[]),byId=(id,c=core())=>events(c).find(e=>e.id===id),fmt=n=>{n=Number(n)||0;return n%1?String(Math.round(n*100)/100):String(n)};
function style(){if($('#v879Style'))return;const s=D.createElement('style');s.id='v879Style';s.textContent=`
:root{--ax-t:14px;--ax-e:20px;--ax-h:56px}#v81Undo,#v87Undo,#v87Flash{display:none!important}
.sheetWrap .sheet :is(button,label,span,small,p,em),#eventList :is(small,.v82EventStatus,.v87Metric),.v87State,.v87Meta,.v87Rest,.v87Primary,.v87Add{font-size:var(--ax-t)!important;line-height:1.35!important}.sheetWrap .sheet .sheetHead>b,.v87Name,#v8Sets .v8SetHead>div>b,#eventList [data-event] span:nth-child(2)>b{font-size:var(--ax-e)!important;line-height:1.15!important}
#cardioFields .choiceControl:has(#intensityChoices){display:grid!important;grid-template-columns:104px minmax(0,1fr)!important;align-items:center!important;gap:12px!important}#cardioFields .choiceControl:has(#intensityChoices)>span{white-space:nowrap!important}
.v877IntensityMain,.v875Stepper,.v879Step{height:var(--ax-h)!important;display:grid!important;grid-template-columns:56px 1fr 56px!important;align-items:stretch!important;padding:3px!important;border-radius:16px!important;background:#13161c!important}.v877IntensityMain>button,.v875Stepper>button,.v879Step>button{height:50px!important;display:grid!important;place-items:center!important;margin:0!important;padding:0!important;font-size:var(--ax-e)!important;line-height:1!important}.v877IntensityValue,.v875Value,.v879Val{height:50px!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:6px!important}.v877IntensityValue b,.v875Value b,.v879Val b{font-size:var(--ax-e)!important;line-height:1!important;font-variant-numeric:tabular-nums}.v877IntensityValue small,.v875Value small,.v879Val small{font-size:var(--ax-t)!important;line-height:1!important;margin:0!important}
#v8Sets .v8SetCount{display:grid!important;grid-template-columns:48px 78px 48px!important;align-items:center!important;gap:0!important}#v8Sets .v8SetCount button,#v8Sets .v8SetCount b{height:48px!important;display:grid!important;place-items:center!important;padding:0!important;margin:0!important;line-height:1!important}#v8Sets .v8SetCount button,#v8Sets .v8SetCount b{font-size:var(--ax-e)!important}
#eventList [data-event].v879Done{background:linear-gradient(90deg,rgba(115,124,255,.12),transparent 58%);transform:translateX(2px)}#eventList [data-event].v879Done:before{content:'';position:absolute;left:0;top:12px;bottom:12px;width:2px;border-radius:4px;background:#737cff}
.v879EditBtn{height:32px;padding:0 11px;border-radius:10px;background:rgba(255,255,255,.045);color:#aeb3ff!important}.v879Block{padding:16px 0;border-bottom:1px solid var(--line)}.v879Head{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px}.v879Head b{font-size:var(--ax-e)!important}.v879Save{width:100%;height:58px;margin-top:18px;border-radius:18px;background:var(--text);color:#101216;font-weight:720}.v879Note{text-align:center;color:var(--dim);margin-top:10px}.v879Count{display:grid;grid-template-columns:56px 1fr 56px;height:var(--ax-h);padding:3px;border-radius:16px;background:#13161c}.v879Count>*{height:50px;display:grid;place-items:center;margin:0;padding:0;font-size:var(--ax-e)!important}
body.v879Sheets{overflow:hidden!important;overscroll-behavior:none!important}.sheetWrap.show.v879Under{pointer-events:none!important}.sheetWrap.show.v879Under>.sheet{overflow:hidden!important;touch-action:none!important}.sheetWrap.show.v879Top>.sheet{overscroll-behavior:contain!important;touch-action:pan-y!important;-webkit-overflow-scrolling:touch}
#eventList.v879Compact>[data-event].v879Hide{display:none!important}.v879All{width:100%;height:42px;display:flex;align-items:center;justify-content:space-between;border-top:1px solid var(--line2);border-bottom:1px solid var(--line2);color:var(--muted)}.v879All b{font-size:var(--ax-t)!important;color:var(--text)}
.v877Plate{padding:30px!important}.v877Plate .k,.v877Plate .m,.v877FocusGrid span{font-size:var(--ax-t)!important;line-height:1.45!important;letter-spacing:.02em!important}.v877Plate .l,.v877FocusGrid b{font-size:var(--ax-e)!important;line-height:1.18!important}.v877Trace{grid-template-columns:1fr!important}.v877TraceNum,.v877ReportHint,.v877TraceBody .k{display:none!important}.v877TraceBody{padding:15px 0!important}.v877AxisLine{height:2px!important;width:42px!important;margin:24px 0!important}
@media(max-width:390px){#cardioFields .choiceControl:has(#intensityChoices){grid-template-columns:92px minmax(0,1fr)!important}.v877Plate{padding:26px!important}}
`;(D.head||D.documentElement).appendChild(s)}
function release(){window.__AXIS_RELEASE__='8.7.9';window.__AXIS_VERSION__='8.7.9';const v=$('.versionLine');if(v){v.textContent='版本 8.7.9';v.dataset.axisVersion='8.7.9';v.style.visibility='visible'}}
function editSheet(){if($('#v879Edit'))return;D.body.insertAdjacentHTML('beforeend','<div class="sheetWrap" id="v879Edit"><div class="sheet"><div class="grabber"></div><div class="sheetHead"><b>调整一次</b><button class="closeBtn" id="v879Close">×</button></div><div id="v879Body"></div></div></div>');$('#v879Close').onclick=()=>{$('#v879Edit').classList.remove('show');layers()}}
function activeId(){return $('#v87Finish')?.dataset.id||null}
function editButton(){const id=activeId(),host=$('#v87Now .v87Actions');if(!id||!host)return;const r=meta().events?.[id];if(!r?.activity||r.activity.status==='finished'||r.v879EditAt){$('#v879EditBtn')?.remove();return}let b=$('#v879EditBtn');if(!b){b=D.createElement('button');b.id='v879EditBtn';b.className='v879EditBtn';b.textContent='调整一次';host.appendChild(b);b.onclick=()=>openEdit(activeId())}}
function openEdit(id){const c=core(),m=meta(),e=byId(id,c),r=m.events?.[id];if(!e||!r?.activity||r.v879EditAt)return;editId=id;if(e.kind==='strength'){const ss=Array.isArray(r.sets)&&r.sets.length?r.sets:[];const done=Math.min(ss.length,Number(r.activity.completedSets)||0),base=ss[done]||ss.at(-1)||{weight:e.weight||20,reps:e.reps||10};edit={kind:'strength',sets:Math.max(done+1,ss.length||e.sets||1),done,weight:Number(base.weight)||20,reps:Math.max(1,Number(base.reps)||10)}}else edit={kind:'cardio',duration:Math.max(1,Number(e.duration)||Math.round((r.activity.estimateMs||900000)/60000)),intensity:Math.max(1,Number(e.intensity)||1)};renderEdit();$('#v879Edit').classList.add('show');layers()}
function row(label,key,val,unit){return`<div class="v879Block"><div class="v879Head"><span>${label}</span><b>${fmt(val)}${unit}</b></div><div class="v879Step"><button data-v879="${key}" data-d="-1">−</button><div class="v879Val"><b>${fmt(val)}</b><small>${unit}</small></div><button data-v879="${key}" data-d="1">＋</button></div></div>`}
function renderEdit(){const b=$('#v879Body');if(!b||!edit)return;if(edit.kind==='strength')b.innerHTML=`<div class="v879Block"><div class="v879Head"><span>总组数</span><b>${edit.sets}组</b></div><div class="v879Count"><button data-v879="sets" data-d="-1">−</button><b>${edit.sets}组</b><button data-v879="sets" data-d="1">＋</button></div></div>${row('未完成组重量','weight',edit.weight,'kg')}${row('未完成组次数','reps',edit.reps,'次')}<button class="v879Save" id="v879Save">应用调整</button><div class="v879Note">已完成的组不会被改动 · 仅可调整一次</div>`;else b.innerHTML=`${row('时间','duration',edit.duration,'分钟')}${row('阻力 / 档位','intensity',edit.intensity,'档')}<button class="v879Save" id="v879Save">应用调整</button><div class="v879Note">进行中的项目仅可调整一次</div>`;$('#v879Save').onclick=saveEdit}
function change(k,d){if(!edit)return;if(k==='sets')edit.sets=Math.max(edit.done+1,Math.min(10,edit.sets+d));else if(k==='weight'){const st=edit.weight<10?.5:edit.weight<30?1:edit.weight<120?2.5:5;edit.weight=Math.max(0,Math.round((edit.weight+d*st)*100)/100)}else if(k==='reps')edit.reps=Math.max(1,Math.min(999,edit.reps+d));else if(k==='duration')edit.duration=Math.max(1,Math.min(999,edit.duration+d));else if(k==='intensity')edit.intensity=Math.max(1,Math.min(99,edit.intensity+d));renderEdit()}
function saveEdit(){const c=core(),m=meta(),e=byId(editId,c),r=m.events?.[editId];if(!e||!r||r.v879EditAt)return;if(edit.kind==='strength'){let ss=Array.isArray(r.sets)?r.sets.map(x=>({...x})):[];while(ss.length<edit.sets)ss.push({weight:edit.weight,reps:edit.reps,state:'assumed',doneAt:null,inferred:true});ss=ss.slice(0,edit.sets);for(let i=edit.done;i<ss.length;i++){ss[i].weight=edit.weight;ss[i].reps=edit.reps}r.sets=ss;e.sets=ss.length;e.weight=Math.max(...ss.map(x=>Number(x.weight)||0));e.reps=Number(ss[0]?.reps)||edit.reps;if(r.activity.completedSets<ss.length)r.activity.planCompletedAt=null}else{e.duration=edit.duration;e.intensity=edit.intensity;r.activity.estimateMs=edit.duration*60000}r.v879EditAt=Date.now();write(CORE,c);write(META,m);$('#v879Edit').classList.remove('show');$('#v879EditBtn')?.remove();layers()}
function doneCue(){const m=meta(),t=Date.now();for(const r of $$('#eventList [data-event]')){const id=r.dataset.event,a=m.events?.[id]?.activity;if(a?.finishedAt&&t-a.finishedAt<3000&&!seen.has(id)){seen.add(id);r.classList.add('v879Done');setTimeout(()=>r.classList.remove('v879Done'),1800)}}}
function timeline(){const list=$('#eventList');if(!list)return;$('#v879All')?.remove();const rs=$$(':scope>[data-event]',list);rs.forEach(r=>r.classList.remove('v879Hide'));if(rs.length<=4){list.classList.remove('v879Compact');return}const m=meta(),keep=[];for(const r of rs){const st=m.events?.[r.dataset.event]?.activity?.status;if(st==='active'||st==='paused')keep.push(r)}for(let i=rs.length-1;i>=0&&keep.length<3;i--)if(!keep.includes(rs[i]))keep.push(rs[i]);if(!expanded){const s=new Set(keep.slice(0,3));rs.forEach(r=>{if(!s.has(r))r.classList.add('v879Hide')});list.classList.add('v879Compact')}else list.classList.remove('v879Compact');const b=D.createElement('button');b.id='v879All';b.className='v879All';b.innerHTML=`<span>${expanded?'完整时间线':'时间线已收拢'}</span><b>${expanded?'收起':`全部 ${rs.length}`}</b>`;b.onclick=()=>{expanded=!expanded;timeline()};list.before(b)}
function layers(){const xs=$$('.sheetWrap.show');if(!xs.length){D.body.classList.remove('v879Sheets');return}for(const x of xs)if(!ranks.has(x))ranks.set(x,++seq);const top=[...xs].sort((a,b)=>ranks.get(a)-ranks.get(b)).at(-1);for(const x of xs){x.classList.toggle('v879Top',x===top);x.classList.toggle('v879Under',x!==top)}D.body.classList.add('v879Sheets')}
function observe(){const MO=window.__AXIS_NATIVE_MUTATION_OBSERVER__||window.MutationObserver;if(!MO)return;new MO(()=>{layers();editButton();doneCue();timeline()}).observe(D.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']})}
function bind(){style();release();editSheet();editButton();doneCue();timeline();observe();D.addEventListener('click',e=>{const b=e.target.closest('[data-v879]');if(b){change(b.dataset.v879,Number(b.dataset.d)||0);return}requestAnimationFrame(()=>{editButton();doneCue();timeline();layers();release()})},true);window.addEventListener('pageshow',()=>{release();editButton();timeline();layers()})}
if(D.readyState==='loading')D.addEventListener('DOMContentLoaded',bind,{once:true});else bind();window.__AXIS_879_READY__=true;
})();
