(()=>{'use strict';
const D=document,$=(s,r=D)=>r.querySelector(s),$$=(s,r=D)=>Array.from(r.querySelectorAll(s));
const VERSION='8.8.0';
let patchQueued=false,lastStepAt=0;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const fmt=n=>{n=Number(n)||0;return n%1?String(Math.round(n*100)/100):String(n)};
function style(){if($('#v880Style'))return;const s=D.createElement('style');s.id='v880Style';s.textContent=`
:root{--axis-ui:15px;--axis-display:22px;--axis-control-h:56px;--axis-gap:12px;--axis-pad:clamp(20px,5.3vw,28px)}
.sheet{padding-left:var(--axis-pad)!important;padding-right:var(--axis-pad)!important}.sheetHead{height:54px!important;margin-bottom:20px!important;grid-template-columns:minmax(0,1fr) 44px!important}.sheetHead>b{font-size:var(--axis-display)!important;line-height:1.1!important;letter-spacing:-.02em!important}.sheetHead .closeBtn{font-size:var(--axis-display)!important}
.sheet :is(.resultRow span,.resultRow b,.musclePanel i,.musclePanel>span,.recognitionLine span,.numberLabel>span,.numberLabel>small,.choiceControl>span,.quickValues button,.choiceStrip button,.sectionLabel,.lineInput span,.settingLink span,.settingLink b,.settingPlain span,.settingPlain b,.textAction,.dangerAction,.reportAction,.versionLine){font-size:var(--axis-ui)!important;line-height:1.35!important}
.sheet :is(.numberMain input,.v8SetRow>span b,.v880Value b,.v880NumInput,.v877IntensityValue b){font-size:var(--axis-display)!important;line-height:1!important;font-variant-numeric:tabular-nums!important;letter-spacing:-.018em!important}
.sheet :is(.numberMain em,.v8SetRow>span small,.v880Value small,.v877IntensityValue small){font-size:var(--axis-ui)!important;line-height:1!important;margin:0!important;color:var(--muted)!important}
.resultRow{height:72px!important}.musclePanel{padding:16px 0!important}.recordFields{margin-top:2px!important}.numberControl{padding:18px 0 20px!important}.numberLabel{min-height:24px!important}.numberMain{height:72px!important;grid-template-columns:60px minmax(0,1fr) 60px!important}.numberMain>button{width:52px!important;height:52px!important;font-size:var(--axis-display)!important;display:grid!important;place-items:center!important;padding:0!important;margin:0!important}.numberMain label{height:56px!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:7px!important}.numberMain input{width:auto!important;min-width:64px!important;max-width:120px!important;text-align:center!important;padding:0!important}.quickValues,.choiceStrip{gap:8px!important}.quickValues button,.choiceStrip button{height:42px!important;min-width:54px!important;padding:0 12px!important}.choiceControl{min-height:76px!important;grid-template-columns:104px minmax(0,1fr)!important;gap:12px!important}
#cardioFields .choiceControl:has(#intensityChoices){display:block!important;min-height:0!important;padding:18px 0 20px!important;border-bottom:1px solid var(--line2)!important}#cardioFields .choiceControl:has(#intensityChoices)>span{display:block!important;margin-bottom:12px!important;white-space:normal!important}#intensityChoices.v877Intensity{display:block!important;width:100%!important;overflow:visible!important}.v877IntensityMain{width:100%!important;height:var(--axis-control-h)!important;display:grid!important;grid-template-columns:56px minmax(0,1fr) 56px!important;align-items:center!important;padding:3px!important;border-radius:16px!important;background:var(--s2)!important;overflow:hidden!important}.v877IntensityMain>button{height:50px!important;display:grid!important;place-items:center!important;padding:0!important;margin:0!important;font-size:var(--axis-display)!important}.v877IntensityValue{height:50px!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:7px!important}.v877IntensityQuick{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:8px!important;overflow:visible!important;margin-top:10px!important}.v877IntensityQuick button{min-width:0!important;width:100%!important;height:40px!important;padding:0!important;border-radius:12px!important;font-size:var(--axis-ui)!important}.v877IntensityNote{display:none!important}
#v8Sets{margin-top:14px!important;border-top:1px solid var(--line2)!important}#v8Sets .v8SetHead{min-height:76px!important;display:grid!important;grid-template-columns:minmax(0,1fr) 164px!important;align-items:center!important;gap:16px!important}#v8Sets .v8SetHead>div:first-child b{font-size:var(--axis-display)!important;line-height:1.1!important}#v8Sets .v8SetHead>div:first-child span{font-size:var(--axis-ui)!important;line-height:1.35!important;margin-top:6px!important}#v8Sets .v8SetCount{width:164px!important;display:grid!important;grid-template-columns:48px 68px 48px!important;align-items:center!important;justify-content:end!important;gap:0!important}#v8Sets .v8SetCount>*{width:100%!important;height:48px!important;display:grid!important;place-items:center!important;padding:0!important;margin:0!important;line-height:1!important}#v8Sets .v8SetCount button{font-size:var(--axis-display)!important;color:var(--muted)!important}#v8Sets .v8SetCount>b{font-size:var(--axis-display)!important;white-space:nowrap!important;text-align:center!important;font-variant-numeric:tabular-nums!important}
.v875PlanEntry{height:58px!important;display:grid!important;grid-template-columns:minmax(0,1fr) auto 18px!important;align-items:center!important;gap:10px!important;border-top:1px solid var(--line2)!important;border-bottom:1px solid var(--line2)!important;text-align:left!important}.v875PlanEntry b,.v875PlanEntry strong,.v875PlanEntry i{font-size:var(--axis-ui)!important;line-height:1!important}.v875PlanEntry small{display:none!important}.v875PlanEntry i{font-style:normal!important;color:var(--dim)!important;text-align:right!important}
#v8Sets .v8SetRows{border-top:0!important}#v8Sets .v8SetRow{min-height:78px!important;display:grid!important;grid-template-columns:34px minmax(88px,1fr) minmax(88px,1fr) 58px!important;column-gap:10px!important;align-items:center!important;padding:0!important;border-bottom:1px solid var(--line2)!important}#v8Sets .v8SetRow>i{font-size:var(--axis-ui)!important;line-height:1!important;padding:0!important;color:var(--dim)!important;font-style:normal!important;text-align:left!important}#v8Sets .v8SetRow>span{height:54px!important;display:flex!important;align-items:center!important;justify-content:flex-start!important;gap:6px!important;min-width:0!important}#v8Sets .v8SetRow>span b{font-weight:650!important}#v8Sets .v8SetRow>span small{font-weight:500!important;white-space:nowrap!important}#v8Sets .v8SetRow>em{width:58px!important;min-width:58px!important;max-width:58px!important;height:36px!important;padding:0!important;border-radius:11px!important;display:grid!important;place-items:center!important;justify-self:end!important;font-size:var(--axis-ui)!important;font-style:normal!important;line-height:1!important}
.v8Adjust{padding:18px 0 4px!important}.v880Adjust{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;width:100%}.v880Field{min-width:0}.v880FieldLabel{height:30px;display:flex;align-items:center;justify-content:space-between;gap:8px;color:var(--muted);font-size:var(--axis-ui)}.v880Control{height:var(--axis-control-h);display:grid;grid-template-columns:52px minmax(0,1fr) 52px;align-items:center;border-radius:16px;background:var(--s2);overflow:hidden}.v880Control>button{height:52px;display:grid;place-items:center;padding:0;margin:0;font-size:var(--axis-display);color:var(--muted)}.v880Value{display:flex!important;align-items:center!important;justify-content:center!important;gap:6px!important;color:var(--text)!important}.v880Value b{font-weight:650!important}.v880Pattern{width:100%;min-height:38px;margin-top:8px;padding:0 10px;border-radius:11px;background:rgba(115,124,255,.09);color:var(--accent2);font-size:var(--axis-ui);text-align:center}
.v880NumSheet{padding-bottom:calc(24px + env(safe-area-inset-bottom))!important}.v880NumCurrent{display:block;color:var(--muted);font-size:var(--axis-ui);margin:2px 0 12px}.v880NumInput{width:100%;height:66px;border:0;border-radius:17px;background:var(--s2);color:var(--text);padding:0 16px;text-align:center;outline:0}.v880NumApply{width:100%;height:58px;margin-top:12px;border-radius:18px;background:var(--text);color:#0b0d10;font-size:var(--axis-ui);font-weight:720}
.v877Plate{padding:30px!important}.v877Plate :is(.k,.m,.v877FocusGrid span,.v877TraceBody .k){font-size:var(--axis-ui)!important;line-height:1.45!important}.v877Plate :is(.l,.v877FocusGrid b){font-size:var(--axis-display)!important;line-height:1.15!important}.v877TraceNum,.v877ReportHint{display:none!important}.v877Trace{grid-template-columns:1fr!important}.v877TraceBody{padding:16px 0!important}.v877PlateFoot{gap:14px!important}
@media(max-width:390px){:root{--axis-pad:20px}.sheet{padding-left:20px!important;padding-right:20px!important}#v8Sets .v8SetHead{grid-template-columns:minmax(0,1fr) 150px!important;gap:10px!important}#v8Sets .v8SetCount{width:150px!important;grid-template-columns:44px 62px 44px!important}#v8Sets .v8SetRow{grid-template-columns:28px minmax(74px,1fr) minmax(74px,1fr) 50px!important;column-gap:6px!important}#v8Sets .v8SetRow>em{width:50px!important;min-width:50px!important;max-width:50px!important}.v880Adjust{grid-template-columns:1fr!important;gap:10px}.v877IntensityQuick{grid-template-columns:repeat(4,minmax(0,1fr))!important}}
@media(min-width:700px){.sheet{padding-left:28px!important;padding-right:28px!important}}
`;(D.head||D.documentElement).appendChild(s)}
function rows(){return $$('#v8Sets .v8SetRow')}
function active(){const rs=rows(),row=rs.find(x=>x.classList.contains('active'))||rs[0];if(!row)return null;const vals=$$('span>b',row).map(x=>Number(x.textContent));return{row,i:rs.indexOf(row),w:Number(vals[0])||0,r:Number(vals[1])||0}}
function values(){return rows().map(row=>{const a=$$('span>b',row).map(x=>Number(x.textContent));return{w:Number(a[0])||0,r:Number(a[1])||0}})}
function weightStep(w){if(w<10)return.5;if(w<30)return 1;if(w<120)return 2.5;if(w<220)return 5;return 10}
function pattern(kind){const a=active(),vs=values();if(!a||a.i<1||a.i>=vs.length-1)return null;const k=kind==='weight'?'w':'r',delta=vs[a.i][k]-vs[a.i-1][k];if(!Number.isFinite(delta)||Math.abs(delta)<(kind==='weight'?.24:.5))return null;return{delta}}
function trigger(kind,val){const h=$('#v8Sets');if(!h)return;const b=D.createElement('button');b.type='button';b.hidden=true;if(kind==='weight')b.dataset.w=String(clamp(Math.round(Number(val)*100)/100,0,1000));else b.dataset.r=String(clamp(Math.round(Number(val)),1,300));h.appendChild(b);b.click();b.remove()}
function patchAdjust(){const h=$('#v8Sets'),adj=$('.v8Adjust',h),a=active();if(!h||!adj||!a)return;const ws=weightStep(a.w),wp=pattern('weight'),rp=pattern('reps');const sig=[a.i,a.w,a.r,rows().length,ws,wp?.delta||0,rp?.delta||0].join('|');if(adj.dataset.v880===sig&&adj.querySelector('.v880Adjust'))return;adj.dataset.v880=sig;adj.innerHTML=`<div class="v880Adjust"><section class="v880Field"><div class="v880FieldLabel"><span>重量</span><span>${fmt(ws)} kg / 次</span></div><div class="v880Control"><button type="button" data-v880-step="weight" data-dir="-1" aria-label="减少重量">−</button><button type="button" class="v880Value" data-v880-edit="weight"><b>${fmt(a.w)}</b><small>kg</small></button><button type="button" data-v880-step="weight" data-dir="1" aria-label="增加重量">＋</button></div>${wp?`<button type="button" class="v880Pattern" data-v880-pattern="weight">后续每组 ${wp.delta>0?'+':''}${fmt(wp.delta)} kg</button>`:''}</section><section class="v880Field"><div class="v880FieldLabel"><span>次数</span><span>1 次 / 次</span></div><div class="v880Control"><button type="button" data-v880-step="reps" data-dir="-1" aria-label="减少次数">−</button><button type="button" class="v880Value" data-v880-edit="reps"><b>${a.r}</b><small>次</small></button><button type="button" data-v880-step="reps" data-dir="1" aria-label="增加次数">＋</button></div>${rp?`<button type="button" class="v880Pattern" data-v880-pattern="reps">后续每组 ${rp.delta>0?'+':''}${Math.round(rp.delta)} 次</button>`:''}</section></div>`}
function ensureNum(){if($('#v880NumSheet'))return;D.body.insertAdjacentHTML('beforeend','<div class="sheetWrap" id="v880NumSheet"><div class="sheet v880NumSheet"><div class="grabber"></div><div class="sheetHead"><b id="v880NumTitle">调整</b><button class="closeBtn" id="v880NumClose">×</button></div><span class="v880NumCurrent" id="v880NumCurrent"></span><input class="v880NumInput" id="v880NumInput" inputmode="decimal"><button class="v880NumApply" id="v880NumApply">应用</button></div></div>');$('#v880NumClose').onclick=()=>$('#v880NumSheet').classList.remove('show');$('#v880NumApply').onclick=applyNum}
function openNum(kind){ensureNum();const a=active();if(!a)return;const v=kind==='weight'?a.w:a.r,s=$('#v880NumSheet');s.dataset.kind=kind;$('#v880NumTitle').textContent=kind==='weight'?'重量':'次数';$('#v880NumCurrent').textContent=kind==='weight'?`当前 ${fmt(v)} kg · 直接输入`:`当前 ${v} 次 · 直接输入`;$('#v880NumInput').value=String(v);s.classList.add('show');setTimeout(()=>{$('#v880NumInput')?.focus();$('#v880NumInput')?.select?.()},60)}
function applyNum(){const s=$('#v880NumSheet'),kind=s?.dataset.kind,v=Number($('#v880NumInput')?.value);if(!Number.isFinite(v))return;trigger(kind,kind==='weight'?clamp(v,0,1000):clamp(v,1,300));s.classList.remove('show');queue()}
function step(kind,dir){const t=performance.now();if(t-lastStepAt<110)return;lastStepAt=t;const a=active();if(!a)return;if(kind==='weight')trigger('weight',a.w+dir*weightStep(a.w));else trigger('reps',a.r+dir);queue()}
function applyPattern(kind){const a=active(),p=pattern(kind),rs=rows();if(!a||!p)return;let v=kind==='weight'?a.w:a.r;const original=a.i;(async()=>{for(let i=a.i+1;i<rs.length;i++){v+=p.delta;rows()[i]?.click();await new Promise(r=>setTimeout(r,16));trigger(kind,v);await new Promise(r=>setTimeout(r,16))}rows()[original]?.click();queue()})()}
function cleanLegacy(){for(const b of $$('[data-v875-step]')){b.removeAttribute('data-v875-step');b.removeAttribute('data-dir')}patchAdjust()}
function queue(){if(patchQueued)return;patchQueued=true;requestAnimationFrame(()=>{patchQueued=false;cleanLegacy()})}
function version(){window.__AXIS_RELEASE__=VERSION;window.__AXIS_VERSION__=VERSION;const v=$('.versionLine');if(v){v.textContent=`版本 ${VERSION}`;v.dataset.axisVersion=VERSION;v.style.visibility='visible'}}
function bind(){style();ensureNum();cleanLegacy();version();const sets=$('#v8Sets');if(sets){const MO=window.__AXIS_NATIVE_MUTATION_OBSERVER__||MutationObserver;new MO(queue).observe(sets,{childList:true,subtree:true,characterData:true})}D.addEventListener('click',e=>{const b=e.target.closest('[data-v880-step]');if(b){e.preventDefault();e.stopPropagation();step(b.dataset.v880Step,Number(b.dataset.dir)||1);return}const ed=e.target.closest('[data-v880-edit]');if(ed){e.preventDefault();e.stopPropagation();openNum(ed.dataset.v880Edit);return}const pt=e.target.closest('[data-v880-pattern]');if(pt){e.preventDefault();e.stopPropagation();applyPattern(pt.dataset.v880Pattern);return}requestAnimationFrame(()=>{cleanLegacy();version()})},true);window.addEventListener('pageshow',()=>{cleanLegacy();version()})}
if(D.readyState==='loading')D.addEventListener('DOMContentLoaded',bind,{once:true});else bind();window.__AXIS_880_READY__=true;
})();
