const EQUIPMENT=[['cable','多功能龙门架'],['lat','高位下拉'],['row','坐姿 / 胸托划船'],['pec','飞鸟 / 后三角'],['chest','胸推'],['shoulder','肩推'],['dip','双杠 / 抬腿'],['arms','手臂'],['legpress','坐姿腿推'],['hack','哈克 / 斜腿推'],['legext','腿屈伸'],['legcurl','腿弯举'],['calf','小腿'],['dumbbell','哑铃'],['barbell','杠铃'],['bodyweight','徒手'],['elliptical','椭圆机'],['rower','划船机'],['treadmill','跑步机 / 跑步'],['walk','步行']];
const CATALOG=EQUIPMENT.map(([id,name])=>`${id}=${name}`).join(', '),rate=globalThis.__axisTextRate||(globalThis.__axisTextRate=new Map());
function allow(ip){const now=Date.now(),it=rate.get(ip)||{t:now,n:0};if(now-it.t>60000){it.t=now;it.n=0}it.n++;rate.set(ip,it);return it.n<=20}
function parseJson(text){if(!text)return null;const s=String(text).replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim();try{return JSON.parse(s)}catch{}const a=s.indexOf('{'),b=s.lastIndexOf('}');if(a>=0&&b>a)try{return JSON.parse(s.slice(a,b+1))}catch{}return null}
export default async function handler(req,res){
  res.setHeader('Cache-Control','no-store');const key=process.env.DASHSCOPE_API_KEY||process.env.BAILIAN_API_KEY,model=process.env.BAILIAN_TEXT_MODEL||'qwen-turbo';
  if(req.method==='GET')return res.status(200).json({available:!!key,model});if(req.method!=='POST')return res.status(405).json({error:'method'});if(!key)return res.status(503).json({error:'not_configured'});
  const ip=String(req.headers['x-forwarded-for']||req.socket?.remoteAddress||'unknown').split(',')[0].trim();if(!allow(ip))return res.status(429).json({error:'rate_limited'});
  let body={};try{body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{})}catch{return res.status(400).json({error:'bad_json'})}const text=String(body.text||'').slice(0,180);if(!text)return res.status(400).json({error:'no_text'});
  const recent=Array.isArray(body.recentEquipment)?body.recentEquipment.filter(x=>EQUIPMENT.some(([id])=>id===x)).slice(0,8):[];
  const prompt=`把这句话解析成健身记录：${JSON.stringify(text)}\n器械ID只从以下选择，无法确定就 null：${CATALOG}\n最近使用：${recent.join(', ')||'无'}\n只提取用户明确说出的数字，不补猜。力量字段 weight,reps,sets；有氧字段 duration,intensity。只返回 JSON：{"equipmentId":string|null,"weight":number|null,"reps":number|null,"sets":number|null,"duration":number|null,"intensity":number|null}`;
  const base=(process.env.BAILIAN_BASE_URL||'https://dashscope.aliyuncs.com/compatible-mode/v1').replace(/\/$/,'');
  try{const up=await fetch(`${base}/chat/completions`,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,messages:[{role:'user',content:prompt}],temperature:0,max_tokens:180,response_format:{type:'json_object'}})}),raw=await up.json();if(!up.ok)return res.status(502).json({error:'upstream'});const p=parseJson(raw?.choices?.[0]?.message?.content);if(!p)return res.status(502).json({error:'bad_response'});const id=EQUIPMENT.some(([x])=>x===p.equipmentId)?p.equipmentId:null,num=k=>Number.isFinite(Number(p[k]))?Number(p[k]):null;return res.status(200).json({result:{equipmentId:id,weight:num('weight'),reps:num('reps'),sets:num('sets'),duration:num('duration'),intensity:num('intensity'),model}})}catch(e){console.error('axis parse',e);return res.status(502).json({error:'network'})}
}
